from .absen import Absen
from .akt_code import Akt_code
from .akt_cust import Akt_cust
from .akt_kont import Akt_kont
from .akt_line import Akt_line
from .akthdr import Akthdr
from .aktion import Aktion
from .ap_journal import Ap_journal
from .archieve import Archieve
from .argt_line import Argt_line
from .argtcost import Argtcost
from .argtstat import Argtstat
from .arrangement import Arrangement
from .artikel import Artikel
from .artprice import Artprice
from .b_history import B_history
from .b_oorder import B_oorder
from .b_storno import B_storno
from .ba_rset import Ba_rset
from .ba_setup import Ba_setup
from .ba_typ import Ba_typ
from .bankrep import Bankrep
from .bankres import Bankres
from .bediener import Bediener
from .bill import Bill
from .bill_lin_tax import Bill_lin_tax
from .bill_line import Bill_line
from .billhis import Billhis
from .billjournal import Billjournal
from .bk_beleg import Bk_beleg
from .bk_fsdef import Bk_fsdef
from .bk_func import Bk_func
from .bk_package import Bk_package
from .bk_pause import Bk_pause
from .bk_rart import Bk_rart
from .bk_raum import Bk_raum
from .bk_reser import Bk_reser
from .bk_rset import Bk_rset
from .bk_setup import Bk_setup
from .bk_stat import Bk_stat
from .bk_veran import Bk_veran
from .bl_dates import Bl_dates
from .blinehis import Blinehis
from .bresline import Bresline
from .brief import Brief
from .brieftmp import Brieftmp
from .briefzei import Briefzei
from .budget import Budget
from .calls import Calls
from .cl_bonus import Cl_bonus
from .cl_book import Cl_book
from .cl_checkin import Cl_checkin
from .cl_class import Cl_class
from .cl_enroll import Cl_enroll
from .cl_free import Cl_free
from .cl_histci import Cl_histci
from .cl_histpay import Cl_histpay
from .cl_histstatus import Cl_histstatus
from .cl_histtrain import Cl_histtrain
from .cl_histvisit import Cl_histvisit
from .cl_home import Cl_home
from .cl_location import Cl_location
from .cl_locker import Cl_locker
from .cl_log import Cl_log
from .cl_member import Cl_member
from .cl_memtype import Cl_memtype
from .cl_paysched import Cl_paysched
from .cl_stat import Cl_stat
from .cl_stat1 import Cl_stat1
from .cl_towel import Cl_towel
from .cl_trainer import Cl_trainer
from .cl_upgrade import Cl_upgrade
from .costbudget import Costbudget
from .counters import Counters
from .crm_campaign import Crm_campaign
from .crm_category import Crm_category
from .crm_dept import Crm_dept
from .crm_dtl import Crm_dtl
from .crm_email import Crm_email
from .crm_event import Crm_event
from .crm_feedhdr import Crm_feedhdr
from .crm_fnlresult import Crm_fnlresult
from .crm_language import Crm_language
from .crm_question import Crm_question
from .crm_tamplang import Crm_tamplang
from .crm_template import Crm_template
from .cross_dtl import Cross_dtl
from .cross_hdr import Cross_hdr
from .debitor import Debitor
from .debthis import Debthis
from .desttext import Desttext
from .dml_art import Dml_art
from .dml_artdep import Dml_artdep
from .dml_rate import Dml_rate
from .eg_action import Eg_action
from .eg_alert import Eg_alert
from .eg_budget import Eg_budget
from .eg_cost import Eg_cost
from .eg_duration import Eg_duration
from .eg_location import Eg_location
from .eg_mainstat import Eg_mainstat
from .eg_maintain import Eg_maintain
from .eg_mdetail import Eg_mdetail
from .eg_messageno import Eg_messageno
from .eg_mobilenr import Eg_mobilenr
from .eg_moveproperty import Eg_moveproperty
from .eg_property import Eg_property
from .eg_propmeter import Eg_propmeter
from .eg_queasy import Eg_queasy
from .eg_reqdetail import Eg_reqdetail
from .eg_reqif import Eg_reqif
from .eg_reqstat import Eg_reqstat
from .eg_request import Eg_request
from .eg_resources import Eg_resources
from .eg_staff import Eg_staff
from .eg_stat import Eg_stat
from .eg_subtask import Eg_subtask
from .eg_vendor import Eg_vendor
from .eg_vperform import Eg_vperform
from .ekum import Ekum
from .employee import Employee
from .equiplan import Equiplan
from .exrate import Exrate
from .fa_artikel import Fa_artikel
from .fa_counter import Fa_counter
from .fa_dp import Fa_dp
from .fa_grup import Fa_grup
from .fa_kateg import Fa_kateg
from .fa_lager import Fa_lager
from .fa_op import Fa_op
from .fa_order import Fa_order
from .fa_ordheader import Fa_ordheader
from .fa_quodetail import Fa_quodetail
from .fa_quotation import Fa_quotation
from .fa_user import Fa_user
from .fbstat import Fbstat
from .feiertag import Feiertag
from .ffont import Ffont
from .fixleist import Fixleist
from .gc_giro import Gc_giro
from .gc_jouhdr import Gc_jouhdr
from .gc_journal import Gc_journal
from .gc_pi import Gc_pi
from .gc_piacct import Gc_piacct
from .gc_pibline import Gc_pibline
from .gc_pitype import Gc_pitype
from .genfcast import Genfcast
from .genlayout import Genlayout
from .genstat import Genstat
from .gentable import Gentable
from .gk_field import Gk_field
from .gk_label import Gk_label
from .gk_notes import Gk_notes
from .gl_acct import Gl_acct
from .gl_accthis import Gl_accthis
from .gl_coa import Gl_coa
from .gl_cost import Gl_cost
from .gl_department import Gl_department
from .gl_fstype import Gl_fstype
from .gl_jhdrhis import Gl_jhdrhis
from .gl_jouhdr import Gl_jouhdr
from .gl_jourhis import Gl_jourhis
from .gl_journal import Gl_journal
from .gl_htljournal import Gl_htljournal
from .gl_main import Gl_main
from .guest import Guest
from .guest_pr import Guest_pr
from .guest_queasy import Guest_queasy
from .guest_remark import Guest_remark
from .guestat import Guestat
from .guestat1 import Guestat1
from .guestbook import Guestbook
from .guestbud import Guestbud
from .guestseg import Guestseg
from .h_artcost import H_artcost
from .h_artikel import H_artikel
from .h_bill import H_bill
from .h_bill_line import H_bill_line
from .h_compli import H_compli
from .h_cost import H_cost
from .h_journal import H_journal
from .h_menu import H_menu
from .h_mjourn import H_mjourn
from .h_oldjou import H_oldjou
from .h_queasy import H_queasy
from .h_rezept import H_rezept
from .h_rezlin import H_rezlin
from .h_storno import H_storno
from .h_umsatz import H_umsatz
from .history import History
from .hoteldpt import Hoteldpt
from .hrbeleg import Hrbeleg
from .hrsegement import Hrsegement
from .htparam import Htparam
from .htreport import Htreport
from .iftable import Iftable
from .interface import Interface
from .k_history import K_history
from .kabine import Kabine
from .kalender import Kalender
from .kasse import Kasse
from .katpreis import Katpreis
from .kellne1 import Kellne1
from .kellner import Kellner
from .kontakt import Kontakt
from .kontline import Kontline
from .kontlink import Kontlink
from .kontplan import Kontplan
from .kontstat import Kontstat
from .kresline import Kresline
from .l_artikel import L_artikel
from .l_bestand import L_bestand
from .l_besthis import L_besthis
from .l_hauptgrp import L_hauptgrp
from .l_kredit import L_kredit
from .l_lager import L_lager
from .l_lieferant import L_lieferant
from .l_liefumsatz import L_liefumsatz
from .l_op import L_op
from .l_ophdr import L_ophdr
from .l_ophhis import L_ophhis
from .l_ophis import L_ophis
from .l_order import L_order
from .l_orderhdr import L_orderhdr
from .l_pprice import L_pprice
from .l_quote import L_quote
from .l_segment import L_segment
from .l_umsatz import L_umsatz
from .l_untergrup import L_untergrup
from .l_verbrauch import L_verbrauch
from .l_zahlbed import L_zahlbed
from .landstat import Landstat
from .masseur import Masseur
from .mast_art import Mast_art
from .master import Master
from .mathis import Mathis
from .mc_aclub import Mc_aclub
from .mc_cardhis import Mc_cardhis
from .mc_disc import Mc_disc
from .mc_fee import Mc_fee
from .mc_guest import Mc_guest
from .mc_types import Mc_types
from .mealcoup import Mealcoup
from .messages import Messages
from .messe import Messe
from .mhis_line import Mhis_line
from .nation import Nation
from .nationstat import Nationstat
from .natstat1 import Natstat1
from .nebenst import Nebenst
from .nightaudit import Nightaudit
from .nitehist import Nitehist
from .nitestor import Nitestor
from .notes import Notes
from .outorder import Outorder
from .package import Package
from .parameters import Parameters
from .paramtext import Paramtext
from .pricecod import Pricecod
from .pricegrp import Pricegrp
from .printcod import Printcod
from .printer import Printer
from .prmarket import Prmarket
from .progcat import Progcat
from .progfile import Progfile
from .prtable import Prtable
from .queasy import Queasy
from .ratecode import Ratecode
from .raum import Raum
from .res_history import Res_history
from .res_line import Res_line
from .reservation import Reservation
from .reslin_queasy import Reslin_queasy
from .resplan import Resplan
from .rg_reports import Rg_reports
from .rmbudget import Rmbudget
from .sales import Sales
from .salesbud import Salesbud
from .salestat import Salestat
from .salestim import Salestim
from .segment import Segment
from .segmentstat import Segmentstat
from .sms_bcaster import Sms_bcaster
from .sms_broadcast import Sms_broadcast
from .sms_group import Sms_group
from .sms_groupmbr import Sms_groupmbr
from .sms_received import Sms_received
from .sourccod import Sourccod
from .sources import Sources
from .sourcetext import Sourcetext
from .telephone import Telephone
from .texte import Texte
from .tisch import Tisch
from .tisch_res import Tisch_res
from .uebertrag import Uebertrag
from .umsatz import Umsatz
from .waehrung import Waehrung
from .wakeup import Wakeup
from .wgrpdep import Wgrpdep
from .wgrpgen import Wgrpgen
from .zimkateg import Zimkateg
from .zimmer import Zimmer
from .zimplan import Zimplan
from .zimpreis import Zimpreis
from .zinrstat import Zinrstat
from .zkstat import Zkstat
from .zwkum import Zwkum
from .gl_acctgrp import Gl_acctgrp
from .gl_acctgrphis import Gl_acctgrphis
