#version: 1.0.0.2

from sqlalchemy.dialects.postgresql import ARRAY
import sqlalchemy as sa
from models.base import Base
from functions.additional_functions import get_current_date

class Artikel(Base):
	__tablename__ = 'artikel'

	abbuchung = sa.Column(sa.Integer, default=0)
	abrart = sa.Column(sa.Integer, default=0)
	activeflag = sa.Column(sa.Boolean, default=False)
	anwdauer = sa.Column(sa.Integer, default=0)
	anwkab = sa.Column(ARRAY(sa.Integer),default=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0])
	anwpreis = sa.Column(ARRAY(sa.Numeric),default=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0])
	anwtage = sa.Column(ARRAY(sa.Integer),default=[0,0,0,0,0,0,0])
	anzahl = sa.Column(sa.Integer, default=0)
	anzpunkte = sa.Column(sa.Numeric, default=0)
	aposit = sa.Column(sa.Integer, default=0)
	artart = sa.Column(sa.Integer, default=0)
	artgrp = sa.Column(sa.Integer, default=0)
	artnr = sa.Column(sa.Integer, default=0)
	artnrlager = sa.Column(sa.Integer, default=0)
	artnrrezept = sa.Column(sa.Integer, default=0)
	autofakt = sa.Column(sa.Boolean, default=False)
	autosaldo = sa.Column(sa.Boolean, default=False)
	betriebsnr = sa.Column(sa.Integer, default=0)
	bezaendern = sa.Column(sa.Boolean, default=False)
	bezeich = sa.Column(sa.String, default="")
	bezeich1 = sa.Column(sa.String, default="")
	bezeich2 = sa.Column(sa.String, default="")
	bezeich3 = sa.Column(sa.String, default="")
	bezeich4 = sa.Column(sa.String, default="")
	blockcheck = sa.Column(sa.Boolean, default=False)
	booktyp = sa.Column(sa.Integer, default=0)
	comment = sa.Column(sa.Boolean, default=False)
	departement = sa.Column(sa.Integer, default=0)
	e_gueltig = sa.Column(sa.Date, default=None)
	eigentuemer = sa.Column(sa.Boolean, default=False)
	endkum = sa.Column(sa.Integer, default=0)
	epreis = sa.Column(sa.Numeric, default=0)
	fibukonto = sa.Column(sa.String, default="")
	frontbuchung = sa.Column(sa.Boolean, default=False)
	kassabuch = sa.Column(sa.Boolean, default=False)
	kassarapport = sa.Column(sa.Boolean, default=False)
	lagernr = sa.Column(sa.Integer, default=0)
	mansteuer = sa.Column(sa.Boolean, default=False)
	masseurres = sa.Column(sa.Boolean, default=False)
	mwst_code = sa.Column(sa.Integer, default=0)
	mwst_incl = sa.Column(sa.Boolean, default=False)
	position = sa.Column(sa.String, default="")
	preistabelle = sa.Column(sa.Boolean, default=False)
	pricetab = sa.Column(sa.Boolean, default=False)
	prov_code = sa.Column(sa.Integer, default=0)
	prozent = sa.Column(sa.Numeric, default=0)
	quittung = sa.Column(sa.Boolean, default=False)
	reinigung = sa.Column(sa.Integer, default=0)
	resart = sa.Column(sa.Boolean, default=False)
	reservieren = sa.Column(sa.Boolean, default=False)
	rg_position = sa.Column(sa.Boolean, default=False)
	ruhedauer = sa.Column(sa.Integer, default=0)
	s_gueltig = sa.Column(sa.Date, default=None)
	serv_incl = sa.Column(sa.Boolean, default=False)
	service_code = sa.Column(sa.Integer, default=0)
	umsatzart = sa.Column(sa.Integer, default=0)
	zwkum = sa.Column(sa.Integer, default=0)
	_recid = sa.Column(sa.Integer, primary_key=True)
	def __init__(self, *args, **kwargs):
		kwargs.setdefault('abbuchung', 0)
		kwargs.setdefault('abrart', 0)
		kwargs.setdefault('activeflag', False)
		kwargs.setdefault('anwdauer', 0)
		kwargs.setdefault('anwkab', [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0])
		kwargs.setdefault('anwpreis', [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0])
		kwargs.setdefault('anwtage', [0,0,0,0,0,0,0])
		kwargs.setdefault('anzahl', 0)
		kwargs.setdefault('anzpunkte', 0)
		kwargs.setdefault('aposit', 0)
		kwargs.setdefault('artart', 0)
		kwargs.setdefault('artgrp', 0)
		kwargs.setdefault('artnr', 0)
		kwargs.setdefault('artnrlager', 0)
		kwargs.setdefault('artnrrezept', 0)
		kwargs.setdefault('autofakt', False)
		kwargs.setdefault('autosaldo', False)
		kwargs.setdefault('betriebsnr', 0)
		kwargs.setdefault('bezaendern', False)
		kwargs.setdefault('bezeich', "")
		kwargs.setdefault('bezeich1', "")
		kwargs.setdefault('bezeich2', "")
		kwargs.setdefault('bezeich3', "")
		kwargs.setdefault('bezeich4', "")
		kwargs.setdefault('blockcheck', False)
		kwargs.setdefault('booktyp', 0)
		kwargs.setdefault('comment', False)
		kwargs.setdefault('departement', 0)
		kwargs.setdefault('e_gueltig', None)
		kwargs.setdefault('eigentuemer', False)
		kwargs.setdefault('endkum', 0)
		kwargs.setdefault('epreis', 0)
		kwargs.setdefault('fibukonto', "")
		kwargs.setdefault('frontbuchung', False)
		kwargs.setdefault('kassabuch', False)
		kwargs.setdefault('kassarapport', False)
		kwargs.setdefault('lagernr', 0)
		kwargs.setdefault('mansteuer', False)
		kwargs.setdefault('masseurres', False)
		kwargs.setdefault('mwst_code', 0)
		kwargs.setdefault('mwst_incl', False)
		kwargs.setdefault('position', "")
		kwargs.setdefault('preistabelle', False)
		kwargs.setdefault('pricetab', False)
		kwargs.setdefault('prov_code', 0)
		kwargs.setdefault('prozent', 0)
		kwargs.setdefault('quittung', False)
		kwargs.setdefault('reinigung', 0)
		kwargs.setdefault('resart', False)
		kwargs.setdefault('reservieren', False)
		kwargs.setdefault('rg_position', False)
		kwargs.setdefault('ruhedauer', 0)
		kwargs.setdefault('s_gueltig', None)
		kwargs.setdefault('serv_incl', False)
		kwargs.setdefault('service_code', 0)
		kwargs.setdefault('umsatzart', 0)
		kwargs.setdefault('zwkum', 0)
		super(Artikel, self).__init__(*args, **kwargs)
