#version: 1.0.0.2

from sqlalchemy.dialects.postgresql import ARRAY
import sqlalchemy as sa
from models.base import Base
from functions.additional_functions import get_current_date

class B_history(Base):
	__tablename__ = 'b_history'

	abreise = sa.Column(sa.String, default="")
	adurch = sa.Column(sa.String, default="")
	anlass = sa.Column(ARRAY(sa.String),default=["",""])
	ape__getraenke = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	ape__speisen = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	arrival = sa.Column(ARRAY(sa.String),default=["","","",""])
	artikel_glob = sa.Column(sa.Boolean, default=False)
	artikel_zg1 = sa.Column(ARRAY(sa.Boolean),default=[False,False,False,False,False,False,False,False])
	artikel_zg2 = sa.Column(ARRAY(sa.Boolean),default=[False,False,False,False,False,False,False,False])
	artikel_zg3 = sa.Column(ARRAY(sa.Boolean),default=[False,False,False,False,False,False,False,False])
	auf__datum = sa.Column(sa.Date, default=None)
	bediener_nr = sa.Column(sa.Integer, default=0)
	bemerkung = sa.Column(sa.String, default="")
	bestellt__durch = sa.Column(sa.String, default="")
	betriebsnr = sa.Column(sa.Integer, default=0)
	bis_datum = sa.Column(sa.Date, default=None)
	c_resstatus = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	dance = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	datum = sa.Column(sa.Date, default=None)
	deko2 = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	dekoration = sa.Column(ARRAY(sa.String),default=["","","","","",""])
	departement = sa.Column(sa.Integer, default=0)
	deposit = sa.Column(sa.Numeric, default=0)
	deposit_payment = sa.Column(ARRAY(sa.Numeric),default=[0,0,0,0,0,0,0,0,0])
	digestif = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	dinner = sa.Column(ARRAY(sa.String),default=["","","",""])
	f_menu = sa.Column(ARRAY(sa.String),default=["","","",""])
	f_no = sa.Column(ARRAY(sa.String),default=["","","",""])
	fotograf = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	gaestebuch = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	garderobe = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	gema = sa.Column(sa.String, default="")
	geschenk = sa.Column(sa.String, default="")
	hotel_no = sa.Column(sa.String, default="")
	hotel_yes = sa.Column(sa.String, default="")
	hotelzimmer = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	kaffee = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	kartentext = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	kontaktperson = sa.Column(ARRAY(sa.String),default=["",""])
	kuenstler = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	last_paid_date = sa.Column(sa.Date, default=None)
	limit_date = sa.Column(sa.Date, default=None)
	menue = sa.Column(ARRAY(sa.String),default=["","","","","","","","","","","","","","","","","","","",""])
	menuekarten = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	musik = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	nachtverpflegung = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	nachtzuschlag = sa.Column(sa.String, default="")
	nadkarte = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	ndessen = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	payment_date = sa.Column(ARRAY(sa.Date),default=[None,None,None,None,None,None,None,None,None])
	payment_userinit = sa.Column(ARRAY(sa.String),default=["","","","","","","","",""])
	personen = sa.Column(sa.Integer, default=0)
	personen2 = sa.Column(ARRAY(sa.String),default=["","","","","",""])
	preismenu = sa.Column(sa.String, default="")
	price = sa.Column(sa.String, default="")
	r_resstatus = sa.Column(ARRAY(sa.Integer),default=[0,0,0,0,0,0,0,0])
	raeume = sa.Column(ARRAY(sa.String),default=["","","","","",""])
	raumbezeichnung = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	raummiete = sa.Column(ARRAY(sa.String),default=["","","","","",""])
	rechnungsanschrift = sa.Column(ARRAY(sa.String),default=["","","","",""])
	resnr = sa.Column(ARRAY(sa.Integer),default=[0,0,0,0,0,0,0,0])
	resstatus = sa.Column(sa.Integer, default=0)
	rpersonen = sa.Column(ARRAY(sa.Integer),default=[0,0,0,0,0,0,0,0])
	rpreis = sa.Column(ARRAY(sa.Numeric),default=[0,0,0,0,0,0,0,0])
	segmentcode = sa.Column(sa.Integer, default=0)
	service = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	sonst__bewirt = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	sonstiges = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	technik = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	telefax = sa.Column(sa.String, default="")
	telefon = sa.Column(sa.String, default="")
	tischform = sa.Column(ARRAY(sa.String),default=["","","","","",""])
	tischordnung = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	tischplan = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	tischreden = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	total_paid = sa.Column(sa.Numeric, default=0)
	uhrzeit = sa.Column(sa.String, default="")
	uhrzeiten = sa.Column(ARRAY(sa.String),default=["","","","","",""])
	v_kontaktperson = sa.Column(ARRAY(sa.String),default=["",""])
	v_telefax = sa.Column(sa.String, default="")
	v_telefon = sa.Column(sa.String, default="")
	va_ablauf = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	veran_nr = sa.Column(sa.Integer, default=0)
	veran_seite = sa.Column(sa.Integer, default=0)
	veranstalteranschrift = sa.Column(ARRAY(sa.String),default=["","","","",""])
	vgeschrieben = sa.Column(sa.String, default="")
	vip = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	vkontrolliert = sa.Column(sa.String, default="")
	weine = sa.Column(ARRAY(sa.String),default=["","","","","","","","","","","","","","","","","","","",""])
	wochentag = sa.Column(sa.String, default="")
	zweck = sa.Column(ARRAY(sa.String),default=["","","","","",""])
	_recid = sa.Column(sa.Integer, primary_key=True)
	def __init__(self, *args, **kwargs):
		kwargs.setdefault('abreise', "")
		kwargs.setdefault('adurch', "")
		kwargs.setdefault('anlass', ["",""])
		kwargs.setdefault('ape__getraenke', ["","","","","","","",""])
		kwargs.setdefault('ape__speisen', ["","","","","","","",""])
		kwargs.setdefault('arrival', ["","","",""])
		kwargs.setdefault('artikel_glob', False)
		kwargs.setdefault('artikel_zg1', [False,False,False,False,False,False,False,False])
		kwargs.setdefault('artikel_zg2', [False,False,False,False,False,False,False,False])
		kwargs.setdefault('artikel_zg3', [False,False,False,False,False,False,False,False])
		kwargs.setdefault('auf__datum', None)
		kwargs.setdefault('bediener_nr', 0)
		kwargs.setdefault('bemerkung', "")
		kwargs.setdefault('bestellt__durch', "")
		kwargs.setdefault('betriebsnr', 0)
		kwargs.setdefault('bis_datum', None)
		kwargs.setdefault('c_resstatus', ["","","","","","","",""])
		kwargs.setdefault('dance', ["","","","","","","",""])
		kwargs.setdefault('datum', None)
		kwargs.setdefault('deko2', ["","","","","","","",""])
		kwargs.setdefault('dekoration', ["","","","","",""])
		kwargs.setdefault('departement', 0)
		kwargs.setdefault('deposit', 0)
		kwargs.setdefault('deposit_payment', [0,0,0,0,0,0,0,0,0])
		kwargs.setdefault('digestif', ["","","","","","","",""])
		kwargs.setdefault('dinner', ["","","",""])
		kwargs.setdefault('f_menu', ["","","",""])
		kwargs.setdefault('f_no', ["","","",""])
		kwargs.setdefault('fotograf', ["","","","","","","",""])
		kwargs.setdefault('gaestebuch', ["","","","","","","",""])
		kwargs.setdefault('garderobe', ["","","","","","","",""])
		kwargs.setdefault('gema', "")
		kwargs.setdefault('geschenk', "")
		kwargs.setdefault('hotel_no', "")
		kwargs.setdefault('hotel_yes', "")
		kwargs.setdefault('hotelzimmer', ["","","","","","","",""])
		kwargs.setdefault('kaffee', ["","","","","","","",""])
		kwargs.setdefault('kartentext', ["","","","","","","",""])
		kwargs.setdefault('kontaktperson', ["",""])
		kwargs.setdefault('kuenstler', ["","","","","","","",""])
		kwargs.setdefault('last_paid_date', None)
		kwargs.setdefault('limit_date', None)
		kwargs.setdefault('menue', ["","","","","","","","","","","","","","","","","","","",""])
		kwargs.setdefault('menuekarten', ["","","","","","","",""])
		kwargs.setdefault('musik', ["","","","","","","",""])
		kwargs.setdefault('nachtverpflegung', ["","","","","","","",""])
		kwargs.setdefault('nachtzuschlag', "")
		kwargs.setdefault('nadkarte', ["","","","","","","",""])
		kwargs.setdefault('ndessen', ["","","","","","","",""])
		kwargs.setdefault('payment_date', [None,None,None,None,None,None,None,None,None])
		kwargs.setdefault('payment_userinit', ["","","","","","","","",""])
		kwargs.setdefault('personen', 0)
		kwargs.setdefault('personen2', ["","","","","",""])
		kwargs.setdefault('preismenu', "")
		kwargs.setdefault('price', "")
		kwargs.setdefault('r_resstatus', [0,0,0,0,0,0,0,0])
		kwargs.setdefault('raeume', ["","","","","",""])
		kwargs.setdefault('raumbezeichnung', ["","","","","","","",""])
		kwargs.setdefault('raummiete', ["","","","","",""])
		kwargs.setdefault('rechnungsanschrift', ["","","","",""])
		kwargs.setdefault('resnr', [0,0,0,0,0,0,0,0])
		kwargs.setdefault('resstatus', 0)
		kwargs.setdefault('rpersonen', [0,0,0,0,0,0,0,0])
		kwargs.setdefault('rpreis', [0,0,0,0,0,0,0,0])
		kwargs.setdefault('segmentcode', 0)
		kwargs.setdefault('service', ["","","","","","","",""])
		kwargs.setdefault('sonst__bewirt', ["","","","","","","",""])
		kwargs.setdefault('sonstiges', ["","","","","","","",""])
		kwargs.setdefault('technik', ["","","","","","","",""])
		kwargs.setdefault('telefax', "")
		kwargs.setdefault('telefon', "")
		kwargs.setdefault('tischform', ["","","","","",""])
		kwargs.setdefault('tischordnung', ["","","","","","","",""])
		kwargs.setdefault('tischplan', ["","","","","","","",""])
		kwargs.setdefault('tischreden', ["","","","","","","",""])
		kwargs.setdefault('total_paid', 0)
		kwargs.setdefault('uhrzeit', "")
		kwargs.setdefault('uhrzeiten', ["","","","","",""])
		kwargs.setdefault('v_kontaktperson', ["",""])
		kwargs.setdefault('v_telefax', "")
		kwargs.setdefault('v_telefon', "")
		kwargs.setdefault('va_ablauf', ["","","","","","","",""])
		kwargs.setdefault('veran_nr', 0)
		kwargs.setdefault('veran_seite', 0)
		kwargs.setdefault('veranstalteranschrift', ["","","","",""])
		kwargs.setdefault('vgeschrieben', "")
		kwargs.setdefault('vip', ["","","","","","","",""])
		kwargs.setdefault('vkontrolliert', "")
		kwargs.setdefault('weine', ["","","","","","","","","","","","","","","","","","","",""])
		kwargs.setdefault('wochentag', "")
		kwargs.setdefault('zweck', ["","","","","",""])
		super(B_history, self).__init__(*args, **kwargs)
