#version: 1.0.0.2

from sqlalchemy.dialects.postgresql import ARRAY
import sqlalchemy as sa
from models.base import Base
from functions.additional_functions import get_current_date

class Bk_veran(Base):
	__tablename__ = 'bk_veran'

	activeflag = sa.Column(sa.Integer, default=0)
	anlass = sa.Column(sa.String, default="")
	art = sa.Column(sa.Integer, default=0)
	bediener_nr = sa.Column(sa.Integer, default=0)
	bemerkung = sa.Column(sa.String, default="")
	betrag = sa.Column(sa.Numeric, default=0)
	betrieb_gast = sa.Column(sa.Integer, default=0)
	betrieb_gastver = sa.Column(sa.Integer, default=0)
	betriebsnr = sa.Column(sa.Integer, default=0)
	departement = sa.Column(sa.Integer, default=0)
	deposit = sa.Column(sa.Numeric, default=0)
	deposit_payment = sa.Column(ARRAY(sa.Numeric),default=[0,0,0,0,0,0,0,0,0])
	gastnr = sa.Column(sa.Integer, default=0)
	gastnrver = sa.Column(sa.Integer, default=0)
	infotafel = sa.Column(sa.String, default="")
	kontaktdat = sa.Column(sa.Date, default=get_current_date())
	kontaktfirst = sa.Column(sa.Date, default=None)
	kontnr_res = sa.Column(sa.Integer, default=0)
	kontnr_ver = sa.Column(sa.Integer, default=0)
	last_paid_date = sa.Column(sa.Date, default=None)
	limit_date = sa.Column(sa.Date, default=None)
	payment_date = sa.Column(ARRAY(sa.Date),default=[None,None,None,None,None,None,None,None,None])
	payment_userinit = sa.Column(ARRAY(sa.String),default=["","","","","","","","",""])
	rechnr = sa.Column(sa.Integer, default=0)
	resdat = sa.Column(sa.Date, default=get_current_date())
	resnr = sa.Column(sa.Integer, default=0)
	resstatus = sa.Column(sa.Integer, default=0)
	segmentcode = sa.Column(sa.Integer, default=0)
	stoerung = sa.Column(sa.Boolean, default=False)
	total_paid = sa.Column(sa.Numeric, default=0)
	useridanlage = sa.Column(sa.String, default="")
	useridmutat = sa.Column(sa.String, default="")
	veran_nr = sa.Column(sa.Integer, default=0)
	zinr = sa.Column(sa.String, default="")
	_recid = sa.Column(sa.Integer, primary_key=True)
	def __init__(self, *args, **kwargs):
		kwargs.setdefault('activeflag', 0)
		kwargs.setdefault('anlass', "")
		kwargs.setdefault('art', 0)
		kwargs.setdefault('bediener_nr', 0)
		kwargs.setdefault('bemerkung', "")
		kwargs.setdefault('betrag', 0)
		kwargs.setdefault('betrieb_gast', 0)
		kwargs.setdefault('betrieb_gastver', 0)
		kwargs.setdefault('betriebsnr', 0)
		kwargs.setdefault('departement', 0)
		kwargs.setdefault('deposit', 0)
		kwargs.setdefault('deposit_payment', [0,0,0,0,0,0,0,0,0])
		kwargs.setdefault('gastnr', 0)
		kwargs.setdefault('gastnrver', 0)
		kwargs.setdefault('infotafel', "")
		kwargs.setdefault('kontaktdat', get_current_date())
		kwargs.setdefault('kontaktfirst', None)
		kwargs.setdefault('kontnr_res', 0)
		kwargs.setdefault('kontnr_ver', 0)
		kwargs.setdefault('last_paid_date', None)
		kwargs.setdefault('limit_date', None)
		kwargs.setdefault('payment_date', [None,None,None,None,None,None,None,None,None])
		kwargs.setdefault('payment_userinit', ["","","","","","","","",""])
		kwargs.setdefault('rechnr', 0)
		kwargs.setdefault('resdat', get_current_date())
		kwargs.setdefault('resnr', 0)
		kwargs.setdefault('resstatus', 0)
		kwargs.setdefault('segmentcode', 0)
		kwargs.setdefault('stoerung', False)
		kwargs.setdefault('total_paid', 0)
		kwargs.setdefault('useridanlage', "")
		kwargs.setdefault('useridmutat', "")
		kwargs.setdefault('veran_nr', 0)
		kwargs.setdefault('zinr', "")
		super(Bk_veran, self).__init__(*args, **kwargs)
