#version: 1.0.0.2

from sqlalchemy.dialects.postgresql import ARRAY
import sqlalchemy as sa
from models.base import Base
from functions.additional_functions import get_current_date

class Bresline(Base):
	__tablename__ = 'bresline'

	anzahl = sa.Column(sa.Integer, default=0)
	artnr = sa.Column(sa.Integer, default=0)
	bankettnr = sa.Column(sa.Integer, default=0)
	bemerkung = sa.Column(sa.String, default="")
	betrieb_gast = sa.Column(sa.Integer, default=0)
	betriebsnr = sa.Column(sa.Integer, default=0)
	bis_zeit = sa.Column(sa.String, default="")
	breslinnr = sa.Column(sa.Integer, default=0)
	briefnr = sa.Column(sa.Integer, default=0)
	buchstatus = sa.Column(sa.Boolean, default=False)
	datum = sa.Column(sa.Date, default=get_current_date())
	departement = sa.Column(sa.Integer, default=0)
	fakturiert = sa.Column(sa.Integer, default=0)
	fname = sa.Column(sa.String, default="")
	gastnr = sa.Column(sa.Integer, default=0)
	information = sa.Column(sa.String, default="")
	limitdate = sa.Column(sa.Date, default=None)
	notizen = sa.Column(sa.String, default="")
	personen = sa.Column(sa.Integer, default=0)
	preis = sa.Column(sa.Numeric, default=0)
	r_status = sa.Column(sa.Integer, default=0)
	raum = sa.Column(sa.String, default="")
	raum_line = sa.Column(sa.Integer, default=0)
	setup = sa.Column(sa.String, default="")
	texte = sa.Column(ARRAY(sa.String),default=["","","","","","","","","","","","","","","","","","",""])
	typ = sa.Column(sa.String, default="")
	vname = sa.Column(sa.String, default="")
	von_equipnr = sa.Column(sa.Integer, default=0)
	von_zeit = sa.Column(sa.String, default="")
	zu_equipnr = sa.Column(sa.Integer, default=0)
	zwkum = sa.Column(sa.Integer, default=0)
	_recid = sa.Column(sa.Integer, primary_key=True)
	def __init__(self, *args, **kwargs):
		kwargs.setdefault('anzahl', 0)
		kwargs.setdefault('artnr', 0)
		kwargs.setdefault('bankettnr', 0)
		kwargs.setdefault('bemerkung', "")
		kwargs.setdefault('betrieb_gast', 0)
		kwargs.setdefault('betriebsnr', 0)
		kwargs.setdefault('bis_zeit', "")
		kwargs.setdefault('breslinnr', 0)
		kwargs.setdefault('briefnr', 0)
		kwargs.setdefault('buchstatus', False)
		kwargs.setdefault('datum', get_current_date())
		kwargs.setdefault('departement', 0)
		kwargs.setdefault('fakturiert', 0)
		kwargs.setdefault('fname', "")
		kwargs.setdefault('gastnr', 0)
		kwargs.setdefault('information', "")
		kwargs.setdefault('limitdate', None)
		kwargs.setdefault('notizen', "")
		kwargs.setdefault('personen', 0)
		kwargs.setdefault('preis', 0)
		kwargs.setdefault('r_status', 0)
		kwargs.setdefault('raum', "")
		kwargs.setdefault('raum_line', 0)
		kwargs.setdefault('setup', "")
		kwargs.setdefault('texte', ["","","","","","","","","","","","","","","","","","",""])
		kwargs.setdefault('typ', "")
		kwargs.setdefault('vname', "")
		kwargs.setdefault('von_equipnr', 0)
		kwargs.setdefault('von_zeit', "")
		kwargs.setdefault('zu_equipnr', 0)
		kwargs.setdefault('zwkum', 0)
		super(Bresline, self).__init__(*args, **kwargs)
