#version: 1.0.0.2

from sqlalchemy.dialects.postgresql import ARRAY
import sqlalchemy as sa
from models.base import Base
from functions.additional_functions import get_current_date

class Cl_trainer(Base):
	__tablename__ = 'cl_trainer'

	activeflag = sa.Column(sa.Boolean, default=True)
	adresse1 = sa.Column(sa.String, default="")
	adresse2 = sa.Column(sa.String, default="")
	birthdate = sa.Column(sa.Date, default=None)
	certificate = sa.Column(sa.String, default="")
	char1 = sa.Column(sa.String, default="")
	char2 = sa.Column(sa.String, default="")
	char3 = sa.Column(sa.String, default="")
	city = sa.Column(sa.String, default="")
	date1 = sa.Column(sa.Date, default=None)
	date2 = sa.Column(sa.String, default="")
	date3 = sa.Column(sa.String, default="")
	deci1 = sa.Column(sa.Numeric, default=0)
	deci2 = sa.Column(sa.Numeric, default=0)
	deci3 = sa.Column(sa.Numeric, default=0)
	email = sa.Column(sa.String, default="")
	gender = sa.Column(sa.String, default="M")
	logi1 = sa.Column(sa.Boolean, default=False)
	logi2 = sa.Column(sa.Boolean, default=False)
	logi3 = sa.Column(sa.Boolean, default=False)
	name = sa.Column(sa.String, default="")
	nr = sa.Column(sa.Integer, default=0)
	num1 = sa.Column(sa.Integer, default=0)
	num2 = sa.Column(sa.Integer, default=0)
	num3 = sa.Column(sa.Integer, default=0)
	offdays = sa.Column(ARRAY(sa.Boolean),default=[False,False,False,False,False,False,False])
	phone = sa.Column(sa.String, default="")
	salary = sa.Column(sa.Numeric, default=0)
	startdate = sa.Column(sa.Date, default=None)
	zip = sa.Column(sa.String, default="")
	_recid = sa.Column(sa.Integer, primary_key=True)
	def __init__(self, *args, **kwargs):
		kwargs.setdefault('activeflag', True)
		kwargs.setdefault('adresse1', "")
		kwargs.setdefault('adresse2', "")
		kwargs.setdefault('birthdate', None)
		kwargs.setdefault('certificate', "")
		kwargs.setdefault('char1', "")
		kwargs.setdefault('char2', "")
		kwargs.setdefault('char3', "")
		kwargs.setdefault('city', "")
		kwargs.setdefault('date1', None)
		kwargs.setdefault('date2', "")
		kwargs.setdefault('date3', "")
		kwargs.setdefault('deci1', 0)
		kwargs.setdefault('deci2', 0)
		kwargs.setdefault('deci3', 0)
		kwargs.setdefault('email', "")
		kwargs.setdefault('gender', "M")
		kwargs.setdefault('logi1', False)
		kwargs.setdefault('logi2', False)
		kwargs.setdefault('logi3', False)
		kwargs.setdefault('name', "")
		kwargs.setdefault('nr', 0)
		kwargs.setdefault('num1', 0)
		kwargs.setdefault('num2', 0)
		kwargs.setdefault('num3', 0)
		kwargs.setdefault('offdays', [False,False,False,False,False,False,False])
		kwargs.setdefault('phone', "")
		kwargs.setdefault('salary', 0)
		kwargs.setdefault('startdate', None)
		kwargs.setdefault('zip', "")
		super(Cl_trainer, self).__init__(*args, **kwargs)
