#version: 1.0.0.2

from sqlalchemy.dialects.postgresql import ARRAY
import sqlalchemy as sa
from models.base import Base
from functions.additional_functions import get_current_date

class Crm_tamplang(Base):
	__tablename__ = 'crm_tamplang'

	btn_back = sa.Column(sa.String, default="")
	btn_close = sa.Column(sa.String, default="")
	btn_finish = sa.Column(sa.String, default="")
	btn_next = sa.Column(sa.String, default="")
	categ_nr = sa.Column(sa.Integer, default=0)
	categname = sa.Column(sa.String, default="")
	char1 = sa.Column(sa.String, default="")
	char2 = sa.Column(sa.String, default="")
	char3 = sa.Column(sa.String, default="")
	char4 = sa.Column(sa.String, default="")
	char5 = sa.Column(sa.String, default="")
	char6 = sa.Column(sa.String, default="")
	char7 = sa.Column(sa.String, default="")
	confirmflag = sa.Column(sa.Boolean, default=False)
	date1 = sa.Column(sa.Date, default=None)
	date2 = sa.Column(sa.Date, default=None)
	date3 = sa.Column(sa.Date, default=None)
	date4 = sa.Column(sa.Date, default=None)
	date5 = sa.Column(sa.Date, default=None)
	deci1 = sa.Column(sa.Numeric, default=0)
	deci2 = sa.Column(sa.Numeric, default=0)
	deci3 = sa.Column(sa.Numeric, default=0)
	deci4 = sa.Column(sa.Numeric, default=0)
	deci5 = sa.Column(sa.Numeric, default=0)
	dept_nr = sa.Column(sa.Integer, default=0)
	event_nr = sa.Column(sa.Integer, default=0)
	finishlabel = sa.Column(sa.String, default="")
	int1 = sa.Column(sa.Integer, default=0)
	int2 = sa.Column(sa.Integer, default=0)
	int3 = sa.Column(sa.Integer, default=0)
	int4 = sa.Column(sa.Integer, default=0)
	int5 = sa.Column(sa.Integer, default=0)
	int6 = sa.Column(sa.Integer, default=0)
	int7 = sa.Column(sa.Integer, default=0)
	language_nr = sa.Column(sa.Integer, default=0)
	logi1 = sa.Column(sa.Boolean, default=False)
	logi2 = sa.Column(sa.Boolean, default=False)
	logi3 = sa.Column(sa.Boolean, default=False)
	logi4 = sa.Column(sa.Boolean, default=False)
	logi5 = sa.Column(sa.Boolean, default=False)
	logi6 = sa.Column(sa.Boolean, default=False)
	logi7 = sa.Column(sa.Boolean, default=False)
	qst = sa.Column(sa.String, default="")
	qst_nr = sa.Column(sa.Integer, default=0)
	scoreansw = sa.Column(sa.String, default="")
	sentdate = sa.Column(sa.Date, default=None)
	sentflag = sa.Column(sa.Boolean, default=False)
	senttime = sa.Column(sa.Integer, default=0)
	statusflag = sa.Column(sa.Integer, default=0)
	txt_finish = sa.Column(sa.String, default="")
	txt_start = sa.Column(sa.String, default="")
	warning = sa.Column(sa.String, default="")
	webconfirmflag = sa.Column(sa.Boolean, default=False)
	websentflag = sa.Column(sa.Boolean, default=False)
	webstatusflag = sa.Column(sa.Integer, default=0)
	_recid = sa.Column(sa.Integer, primary_key=True)
	def __init__(self, *args, **kwargs):
		kwargs.setdefault('btn_back', "")
		kwargs.setdefault('btn_close', "")
		kwargs.setdefault('btn_finish', "")
		kwargs.setdefault('btn_next', "")
		kwargs.setdefault('categ_nr', 0)
		kwargs.setdefault('categname', "")
		kwargs.setdefault('char1', "")
		kwargs.setdefault('char2', "")
		kwargs.setdefault('char3', "")
		kwargs.setdefault('char4', "")
		kwargs.setdefault('char5', "")
		kwargs.setdefault('char6', "")
		kwargs.setdefault('char7', "")
		kwargs.setdefault('confirmflag', False)
		kwargs.setdefault('date1', None)
		kwargs.setdefault('date2', None)
		kwargs.setdefault('date3', None)
		kwargs.setdefault('date4', None)
		kwargs.setdefault('date5', None)
		kwargs.setdefault('deci1', 0)
		kwargs.setdefault('deci2', 0)
		kwargs.setdefault('deci3', 0)
		kwargs.setdefault('deci4', 0)
		kwargs.setdefault('deci5', 0)
		kwargs.setdefault('dept_nr', 0)
		kwargs.setdefault('event_nr', 0)
		kwargs.setdefault('finishlabel', "")
		kwargs.setdefault('int1', 0)
		kwargs.setdefault('int2', 0)
		kwargs.setdefault('int3', 0)
		kwargs.setdefault('int4', 0)
		kwargs.setdefault('int5', 0)
		kwargs.setdefault('int6', 0)
		kwargs.setdefault('int7', 0)
		kwargs.setdefault('language_nr', 0)
		kwargs.setdefault('logi1', False)
		kwargs.setdefault('logi2', False)
		kwargs.setdefault('logi3', False)
		kwargs.setdefault('logi4', False)
		kwargs.setdefault('logi5', False)
		kwargs.setdefault('logi6', False)
		kwargs.setdefault('logi7', False)
		kwargs.setdefault('qst', "")
		kwargs.setdefault('qst_nr', 0)
		kwargs.setdefault('scoreansw', "")
		kwargs.setdefault('sentdate', None)
		kwargs.setdefault('sentflag', False)
		kwargs.setdefault('senttime', 0)
		kwargs.setdefault('statusflag', 0)
		kwargs.setdefault('txt_finish', "")
		kwargs.setdefault('txt_start', "")
		kwargs.setdefault('warning', "")
		kwargs.setdefault('webconfirmflag', False)
		kwargs.setdefault('websentflag', False)
		kwargs.setdefault('webstatusflag', 0)
		super(Crm_tamplang, self).__init__(*args, **kwargs)
