#version: 1.0.0.2

from sqlalchemy.dialects.postgresql import ARRAY
import sqlalchemy as sa
from models.base import Base
from functions.additional_functions import get_current_date

class Cross_dtl(Base):
	__tablename__ = 'cross_dtl'

	char1 = sa.Column(sa.String, default="")
	char2 = sa.Column(sa.String, default="")
	char3 = sa.Column(sa.String, default="")
	char4 = sa.Column(sa.String, default="")
	char5 = sa.Column(sa.String, default="")
	date1 = sa.Column(sa.Date, default=None)
	date2 = sa.Column(sa.Date, default=None)
	date3 = sa.Column(sa.Date, default=None)
	date4 = sa.Column(sa.Date, default=None)
	date5 = sa.Column(sa.Date, default=None)
	deci1 = sa.Column(sa.Numeric, default=0)
	deci2 = sa.Column(sa.Numeric, default=0)
	deci3 = sa.Column(sa.Numeric, default=0)
	deci4 = sa.Column(sa.Numeric, default=0)
	deci5 = sa.Column(sa.Numeric, default=0)
	int1 = sa.Column(sa.Integer, default=0)
	int2 = sa.Column(sa.Integer, default=0)
	int3 = sa.Column(sa.Integer, default=0)
	int4 = sa.Column(sa.Integer, default=0)
	int5 = sa.Column(sa.Integer, default=0)
	isautoinc = sa.Column(sa.Boolean, default=False)
	iskey = sa.Column(sa.Boolean, default=False)
	issend = sa.Column(sa.Boolean, default=False)
	logi1 = sa.Column(sa.Boolean, default=False)
	logi2 = sa.Column(sa.Boolean, default=False)
	logi3 = sa.Column(sa.Boolean, default=False)
	logi4 = sa.Column(sa.Boolean, default=False)
	logi5 = sa.Column(sa.Boolean, default=False)
	others_fieldcomments = sa.Column(sa.String, default="")
	others_fielddefault = sa.Column(sa.String, default="")
	others_fieldisnull = sa.Column(sa.Boolean, default=False)
	others_fieldnm = sa.Column(sa.String, default="")
	others_fieldtype = sa.Column(sa.String, default="")
	others_fieldwidth = sa.Column(sa.String, default="")
	variant_db = sa.Column(sa.Integer, default=0)
	vhp_fieldcomments = sa.Column(sa.String, default="")
	vhp_fielddefault = sa.Column(sa.String, default="")
	vhp_fieldisnull = sa.Column(sa.Boolean, default=False)
	vhp_fieldnm = sa.Column(sa.String, default="")
	vhp_fieldorder = sa.Column(sa.Integer, default=0)
	vhp_fieldtype = sa.Column(sa.String, default="")
	vhp_fieldwidth = sa.Column(sa.String, default="")
	vhp_tableid = sa.Column(sa.Integer, default=0)
	_recid = sa.Column(sa.Integer, primary_key=True)
	def __init__(self, *args, **kwargs):
		kwargs.setdefault('char1', "")
		kwargs.setdefault('char2', "")
		kwargs.setdefault('char3', "")
		kwargs.setdefault('char4', "")
		kwargs.setdefault('char5', "")
		kwargs.setdefault('date1', None)
		kwargs.setdefault('date2', None)
		kwargs.setdefault('date3', None)
		kwargs.setdefault('date4', None)
		kwargs.setdefault('date5', None)
		kwargs.setdefault('deci1', 0)
		kwargs.setdefault('deci2', 0)
		kwargs.setdefault('deci3', 0)
		kwargs.setdefault('deci4', 0)
		kwargs.setdefault('deci5', 0)
		kwargs.setdefault('int1', 0)
		kwargs.setdefault('int2', 0)
		kwargs.setdefault('int3', 0)
		kwargs.setdefault('int4', 0)
		kwargs.setdefault('int5', 0)
		kwargs.setdefault('isautoinc', False)
		kwargs.setdefault('iskey', False)
		kwargs.setdefault('issend', False)
		kwargs.setdefault('logi1', False)
		kwargs.setdefault('logi2', False)
		kwargs.setdefault('logi3', False)
		kwargs.setdefault('logi4', False)
		kwargs.setdefault('logi5', False)
		kwargs.setdefault('others_fieldcomments', "")
		kwargs.setdefault('others_fielddefault', "")
		kwargs.setdefault('others_fieldisnull', False)
		kwargs.setdefault('others_fieldnm', "")
		kwargs.setdefault('others_fieldtype', "")
		kwargs.setdefault('others_fieldwidth', "")
		kwargs.setdefault('variant_db', 0)
		kwargs.setdefault('vhp_fieldcomments', "")
		kwargs.setdefault('vhp_fielddefault', "")
		kwargs.setdefault('vhp_fieldisnull', False)
		kwargs.setdefault('vhp_fieldnm', "")
		kwargs.setdefault('vhp_fieldorder', 0)
		kwargs.setdefault('vhp_fieldtype', "")
		kwargs.setdefault('vhp_fieldwidth', "")
		kwargs.setdefault('vhp_tableid', 0)
		super(Cross_dtl, self).__init__(*args, **kwargs)
