#version: 1.0.0.2

from sqlalchemy.dialects.postgresql import ARRAY
import sqlalchemy as sa
from models.base import Base
from functions.additional_functions import get_current_date

class Eg_cost(Base):
	__tablename__ = 'eg_cost'

	char1 = sa.Column(sa.String, default="")
	char2 = sa.Column(sa.String, default="")
	char3 = sa.Column(sa.String, default="")
	close_by = sa.Column(sa.String, default="")
	close_date = sa.Column(sa.Date, default=None)
	close_time = sa.Column(sa.Integer, default=0)
	closeflag = sa.Column(sa.Boolean, default=False)
	cost = sa.Column(sa.Numeric, default=0)
	created_by = sa.Column(sa.String, default="")
	created_date = sa.Column(sa.Date, default=None)
	date1 = sa.Column(sa.Date, default=None)
	date2 = sa.Column(sa.Date, default=None)
	datum = sa.Column(sa.Date, default=None)
	deci1 = sa.Column(sa.Numeric, default=0)
	deci2 = sa.Column(sa.Numeric, default=0)
	logi1 = sa.Column(sa.Boolean, default=False)
	logi2 = sa.Column(sa.Boolean, default=False)
	month = sa.Column(sa.Integer, default=0)
	number1 = sa.Column(sa.Integer, default=0)
	number2 = sa.Column(sa.Integer, default=0)
	number3 = sa.Column(sa.Integer, default=0)
	price = sa.Column(sa.Numeric, default=0)
	resource_nr = sa.Column(sa.Integer, default=0)
	usage = sa.Column(sa.Integer, default=0)
	year = sa.Column(sa.Integer, default=0)
	_recid = sa.Column(sa.Integer, primary_key=True)
	def __init__(self, *args, **kwargs):
		kwargs.setdefault('char1', "")
		kwargs.setdefault('char2', "")
		kwargs.setdefault('char3', "")
		kwargs.setdefault('close_by', "")
		kwargs.setdefault('close_date', None)
		kwargs.setdefault('close_time', 0)
		kwargs.setdefault('closeflag', False)
		kwargs.setdefault('cost', 0)
		kwargs.setdefault('created_by', "")
		kwargs.setdefault('created_date', None)
		kwargs.setdefault('date1', None)
		kwargs.setdefault('date2', None)
		kwargs.setdefault('datum', None)
		kwargs.setdefault('deci1', 0)
		kwargs.setdefault('deci2', 0)
		kwargs.setdefault('logi1', False)
		kwargs.setdefault('logi2', False)
		kwargs.setdefault('month', 0)
		kwargs.setdefault('number1', 0)
		kwargs.setdefault('number2', 0)
		kwargs.setdefault('number3', 0)
		kwargs.setdefault('price', 0)
		kwargs.setdefault('resource_nr', 0)
		kwargs.setdefault('usage', 0)
		kwargs.setdefault('year', 0)
		super(Eg_cost, self).__init__(*args, **kwargs)
