#version: 1.0.0.2

from sqlalchemy.dialects.postgresql import ARRAY
import sqlalchemy as sa
from models.base import Base
from functions.additional_functions import get_current_date

class Eg_property(Base):
	__tablename__ = 'eg_property'

	activeflag = sa.Column(sa.Boolean, default=True)
	asset = sa.Column(sa.String, default="")
	bezeich = sa.Column(sa.String, default="")
	brand = sa.Column(sa.String, default="")
	capacity = sa.Column(sa.String, default="")
	char1 = sa.Column(sa.String, default="")
	char2 = sa.Column(sa.String, default="")
	char3 = sa.Column(sa.String, default="")
	date1 = sa.Column(sa.Date, default=None)
	date2 = sa.Column(sa.Date, default=None)
	datum = sa.Column(sa.Date, default=None)
	deci1 = sa.Column(sa.Numeric, default=0)
	deci2 = sa.Column(sa.Numeric, default=0)
	dimension = sa.Column(sa.String, default="")
	hourmax = sa.Column(sa.Integer, default=0)
	location = sa.Column(sa.Integer, default=0)
	logi1 = sa.Column(sa.Boolean, default=False)
	logi2 = sa.Column(sa.Boolean, default=False)
	maintask = sa.Column(sa.Integer, default=0)
	metermax = sa.Column(sa.Integer, default=0)
	meterrec = sa.Column(sa.Boolean, default=False)
	nr = sa.Column(sa.Integer, default=0)
	number1 = sa.Column(sa.Integer, default=0)
	number2 = sa.Column(sa.Integer, default=0)
	number3 = sa.Column(sa.Integer, default=0)
	price = sa.Column(sa.Numeric, default=0)
	spec = sa.Column(sa.String, default="")
	type = sa.Column(sa.String, default="")
	zinr = sa.Column(sa.String, default="")
	_recid = sa.Column(sa.Integer, primary_key=True)
	def __init__(self, *args, **kwargs):
		kwargs.setdefault('activeflag', True)
		kwargs.setdefault('asset', "")
		kwargs.setdefault('bezeich', "")
		kwargs.setdefault('brand', "")
		kwargs.setdefault('capacity', "")
		kwargs.setdefault('char1', "")
		kwargs.setdefault('char2', "")
		kwargs.setdefault('char3', "")
		kwargs.setdefault('date1', None)
		kwargs.setdefault('date2', None)
		kwargs.setdefault('datum', None)
		kwargs.setdefault('deci1', 0)
		kwargs.setdefault('deci2', 0)
		kwargs.setdefault('dimension', "")
		kwargs.setdefault('hourmax', 0)
		kwargs.setdefault('location', 0)
		kwargs.setdefault('logi1', False)
		kwargs.setdefault('logi2', False)
		kwargs.setdefault('maintask', 0)
		kwargs.setdefault('metermax', 0)
		kwargs.setdefault('meterrec', False)
		kwargs.setdefault('nr', 0)
		kwargs.setdefault('number1', 0)
		kwargs.setdefault('number2', 0)
		kwargs.setdefault('number3', 0)
		kwargs.setdefault('price', 0)
		kwargs.setdefault('spec', "")
		kwargs.setdefault('type', "")
		kwargs.setdefault('zinr', "")
		super(Eg_property, self).__init__(*args, **kwargs)
