#version: 1.0.0.2

from sqlalchemy.dialects.postgresql import ARRAY
import sqlalchemy as sa
from models.base import Base
from functions.additional_functions import get_current_date

class Employee(Base):
	__tablename__ = 'employee'

	accno = sa.Column(sa.String, default="")
	activeflag = sa.Column(sa.Boolean, default=False)
	address1 = sa.Column(sa.String, default="")
	address2 = sa.Column(sa.String, default="")
	allowance = sa.Column(ARRAY(sa.Boolean),default=[False,False,False,False,False,False])
	bank = sa.Column(sa.String, default="")
	ben_eat = sa.Column(sa.Numeric, default=0)
	ben_trans = sa.Column(sa.Numeric, default=0)
	birthdate = sa.Column(sa.Date, default=None)
	branch = sa.Column(sa.String, default="")
	bsalary = sa.Column(sa.Numeric, default=0)
	cbirth = sa.Column(ARRAY(sa.Date),default=[None,None,None,None,None])
	child = sa.Column(ARRAY(sa.String),default=["","","","",""])
	city = sa.Column(sa.String, default="")
	degree = sa.Column(sa.Integer, default=0)
	dept = sa.Column(sa.Integer, default=0)
	doct = sa.Column(sa.Numeric, default=0)
	estat = sa.Column(sa.Integer, default=0)
	fname = sa.Column(sa.String, default="")
	gender = sa.Column(sa.Integer, default=0)
	hdate = sa.Column(sa.Date, default=get_current_date())
	id = sa.Column(sa.String, default="")
	idcard = sa.Column(sa.String, default="")
	imgfile = sa.Column(sa.String, default="")
	mstat = sa.Column(sa.Integer, default=0)
	name = sa.Column(sa.String, default="")
	nation = sa.Column(sa.String, default="")
	partner = sa.Column(sa.String, default="")
	pbirth = sa.Column(sa.Date, default=None)
	position = sa.Column(sa.String, default="")
	religion = sa.Column(sa.Integer, default=0)
	tdate = sa.Column(sa.Date, default=None)
	telephone = sa.Column(sa.String, default="")
	zipcode = sa.Column(sa.String, default="")
	_recid = sa.Column(sa.Integer, primary_key=True)
	def __init__(self, *args, **kwargs):
		kwargs.setdefault('accno', "")
		kwargs.setdefault('activeflag', False)
		kwargs.setdefault('address1', "")
		kwargs.setdefault('address2', "")
		kwargs.setdefault('allowance', [False,False,False,False,False,False])
		kwargs.setdefault('bank', "")
		kwargs.setdefault('ben_eat', 0)
		kwargs.setdefault('ben_trans', 0)
		kwargs.setdefault('birthdate', None)
		kwargs.setdefault('branch', "")
		kwargs.setdefault('bsalary', 0)
		kwargs.setdefault('cbirth', [None,None,None,None,None])
		kwargs.setdefault('child', ["","","","",""])
		kwargs.setdefault('city', "")
		kwargs.setdefault('degree', 0)
		kwargs.setdefault('dept', 0)
		kwargs.setdefault('doct', 0)
		kwargs.setdefault('estat', 0)
		kwargs.setdefault('fname', "")
		kwargs.setdefault('gender', 0)
		kwargs.setdefault('hdate', get_current_date())
		kwargs.setdefault('id', "")
		kwargs.setdefault('idcard', "")
		kwargs.setdefault('imgfile', "")
		kwargs.setdefault('mstat', 0)
		kwargs.setdefault('name', "")
		kwargs.setdefault('nation', "")
		kwargs.setdefault('partner', "")
		kwargs.setdefault('pbirth', None)
		kwargs.setdefault('position', "")
		kwargs.setdefault('religion', 0)
		kwargs.setdefault('tdate', None)
		kwargs.setdefault('telephone', "")
		kwargs.setdefault('zipcode', "")
		super(Employee, self).__init__(*args, **kwargs)
