#version: 1.0.0.2

from sqlalchemy.dialects.postgresql import ARRAY
import sqlalchemy as sa
from models.base import Base
from functions.additional_functions import get_current_date

class Fa_ordheader(Base):
	__tablename__ = 'fa_ordheader'

	activeflag = sa.Column(sa.Integer, default=0)
	approved_1 = sa.Column(sa.Boolean, default=False)
	approved_1_by = sa.Column(sa.String, default="")
	approved_1_date = sa.Column(sa.Date, default=None)
	approved_1_time = sa.Column(sa.Integer, default=0)
	approved_2 = sa.Column(sa.Boolean, default=False)
	approved_2_by = sa.Column(sa.String, default="")
	approved_2_date = sa.Column(sa.Date, default=None)
	approved_2_time = sa.Column(sa.Integer, default=0)
	approved_3 = sa.Column(sa.Boolean, default=False)
	approved_3_by = sa.Column(sa.String, default="")
	approved_3_date = sa.Column(sa.Date, default=None)
	approved_3_time = sa.Column(sa.Integer, default=0)
	cancel_by = sa.Column(sa.String, default="")
	cancel_date = sa.Column(sa.Date, default=None)
	cancel_time = sa.Column(sa.Integer, default=0)
	close_by = sa.Column(sa.String, default="")
	close_date = sa.Column(sa.Date, default=None)
	close_time = sa.Column(sa.Integer, default=0)
	created_by = sa.Column(sa.String, default="")
	created_date = sa.Column(sa.Date, default=None)
	created_time = sa.Column(sa.Integer, default=0)
	credit_term = sa.Column(sa.Integer, default=0)
	currency = sa.Column(sa.Integer, default=0)
	delete_by = sa.Column(sa.String, default="")
	delete_date = sa.Column(sa.Date, default=None)
	delete_time = sa.Column(sa.Integer, default=0)
	dept_nr = sa.Column(sa.Integer, default=0)
	expected_delivery = sa.Column(sa.Date, default=None)
	modified_by = sa.Column(sa.String, default="")
	modified_date = sa.Column(sa.Date, default=None)
	modified_time = sa.Column(sa.Integer, default=0)
	order_date = sa.Column(sa.Date, default=None)
	order_desc = sa.Column(sa.String, default="")
	order_name = sa.Column(sa.String, default="")
	order_nr = sa.Column(sa.String, default="")
	order_type = sa.Column(sa.String, default="")
	paymentdate = sa.Column(sa.Date, default=None)
	pr_flag = sa.Column(sa.Boolean, default=False)
	pr_nr = sa.Column(sa.String, default="")
	printed = sa.Column(sa.Date, default=None)
	printedtime = sa.Column(sa.Integer, default=0)
	released_by = sa.Column(sa.String, default="")
	released_date = sa.Column(sa.Date, default=None)
	released_flag = sa.Column(sa.Boolean, default=False)
	released_time = sa.Column(sa.Integer, default=0)
	statflag = sa.Column(sa.Integer, default=0)
	supplier_nr = sa.Column(sa.Integer, default=0)
	total_amount = sa.Column(sa.Numeric, default=0)
	_recid = sa.Column(sa.Integer, primary_key=True)
	def __init__(self, *args, **kwargs):
		kwargs.setdefault('activeflag', 0)
		kwargs.setdefault('approved_1', False)
		kwargs.setdefault('approved_1_by', "")
		kwargs.setdefault('approved_1_date', None)
		kwargs.setdefault('approved_1_time', 0)
		kwargs.setdefault('approved_2', False)
		kwargs.setdefault('approved_2_by', "")
		kwargs.setdefault('approved_2_date', None)
		kwargs.setdefault('approved_2_time', 0)
		kwargs.setdefault('approved_3', False)
		kwargs.setdefault('approved_3_by', "")
		kwargs.setdefault('approved_3_date', None)
		kwargs.setdefault('approved_3_time', 0)
		kwargs.setdefault('cancel_by', "")
		kwargs.setdefault('cancel_date', None)
		kwargs.setdefault('cancel_time', 0)
		kwargs.setdefault('close_by', "")
		kwargs.setdefault('close_date', None)
		kwargs.setdefault('close_time', 0)
		kwargs.setdefault('created_by', "")
		kwargs.setdefault('created_date', None)
		kwargs.setdefault('created_time', 0)
		kwargs.setdefault('credit_term', 0)
		kwargs.setdefault('currency', 0)
		kwargs.setdefault('delete_by', "")
		kwargs.setdefault('delete_date', None)
		kwargs.setdefault('delete_time', 0)
		kwargs.setdefault('dept_nr', 0)
		kwargs.setdefault('expected_delivery', None)
		kwargs.setdefault('modified_by', "")
		kwargs.setdefault('modified_date', None)
		kwargs.setdefault('modified_time', 0)
		kwargs.setdefault('order_date', None)
		kwargs.setdefault('order_desc', "")
		kwargs.setdefault('order_name', "")
		kwargs.setdefault('order_nr', "")
		kwargs.setdefault('order_type', "")
		kwargs.setdefault('paymentdate', None)
		kwargs.setdefault('pr_flag', False)
		kwargs.setdefault('pr_nr', "")
		kwargs.setdefault('printed', None)
		kwargs.setdefault('printedtime', 0)
		kwargs.setdefault('released_by', "")
		kwargs.setdefault('released_date', None)
		kwargs.setdefault('released_flag', False)
		kwargs.setdefault('released_time', 0)
		kwargs.setdefault('statflag', 0)
		kwargs.setdefault('supplier_nr', 0)
		kwargs.setdefault('total_amount', 0)
		super(Fa_ordheader, self).__init__(*args, **kwargs)
