#version: 1.0.0.2

from sqlalchemy.dialects.postgresql import ARRAY
import sqlalchemy as sa
from models.base import Base
from functions.additional_functions import get_current_date

class Genlayout(Base):
	__tablename__ = 'genlayout'

	activeflag = sa.Column(sa.Boolean, default=True)
	add_height = sa.Column(sa.Numeric, default=0)
	add_width = sa.Column(sa.Numeric, default=0)
	button_ext = sa.Column(ARRAY(sa.String),default=["","","","","",""])
	canc_height = sa.Column(sa.Numeric, default=0)
	canc_width = sa.Column(sa.Numeric, default=0)
	char_ext = sa.Column(ARRAY(sa.String),default=["","","","","","","","",""])
	combo_ext = sa.Column(ARRAY(sa.String),default=["","",""])
	date_ext = sa.Column(ARRAY(sa.String),default=["","","","","","","","",""])
	deci_ext = sa.Column(ARRAY(sa.String),default=["","","","","","","","",""])
	del_height = sa.Column(sa.Numeric, default=0)
	del_width = sa.Column(sa.Numeric, default=0)
	exit_height = sa.Column(sa.Numeric, default=0)
	exit_width = sa.Column(sa.Numeric, default=0)
	frame_height = sa.Column(sa.Numeric, default=0)
	frame_title = sa.Column(sa.String, default="")
	frame_width = sa.Column(sa.Numeric, default=0)
	inte_ext = sa.Column(ARRAY(sa.String),default=["","","","","","","","",""])
	key = sa.Column(sa.String, default="")
	logi_ext = sa.Column(ARRAY(sa.String),default=["","","","","","","","",""])
	string_ext = sa.Column(ARRAY(sa.String),default=["","","","","","","","",""])
	tchar_ext = sa.Column(ARRAY(sa.String),default=["","","","","","","","",""])
	tdate_ext = sa.Column(ARRAY(sa.String),default=["","","","","","","","",""])
	tdeci_ext = sa.Column(ARRAY(sa.String),default=["","","","","","","","",""])
	tinte_ext = sa.Column(ARRAY(sa.String),default=["","","","","","","","",""])
	tlogi_ext = sa.Column(ARRAY(sa.String),default=["","","","","","","","",""])
	_recid = sa.Column(sa.Integer, primary_key=True)
	def __init__(self, *args, **kwargs):
		kwargs.setdefault('activeflag', True)
		kwargs.setdefault('add_height', 0)
		kwargs.setdefault('add_width', 0)
		kwargs.setdefault('button_ext', ["","","","","",""])
		kwargs.setdefault('canc_height', 0)
		kwargs.setdefault('canc_width', 0)
		kwargs.setdefault('char_ext', ["","","","","","","","",""])
		kwargs.setdefault('combo_ext', ["","",""])
		kwargs.setdefault('date_ext', ["","","","","","","","",""])
		kwargs.setdefault('deci_ext', ["","","","","","","","",""])
		kwargs.setdefault('del_height', 0)
		kwargs.setdefault('del_width', 0)
		kwargs.setdefault('exit_height', 0)
		kwargs.setdefault('exit_width', 0)
		kwargs.setdefault('frame_height', 0)
		kwargs.setdefault('frame_title', "")
		kwargs.setdefault('frame_width', 0)
		kwargs.setdefault('inte_ext', ["","","","","","","","",""])
		kwargs.setdefault('key', "")
		kwargs.setdefault('logi_ext', ["","","","","","","","",""])
		kwargs.setdefault('string_ext', ["","","","","","","","",""])
		kwargs.setdefault('tchar_ext', ["","","","","","","","",""])
		kwargs.setdefault('tdate_ext', ["","","","","","","","",""])
		kwargs.setdefault('tdeci_ext', ["","","","","","","","",""])
		kwargs.setdefault('tinte_ext', ["","","","","","","","",""])
		kwargs.setdefault('tlogi_ext', ["","","","","","","","",""])
		super(Genlayout, self).__init__(*args, **kwargs)
