#version: 1.0.0.2

from sqlalchemy.dialects.postgresql import ARRAY
import sqlalchemy as sa
from models.base import Base
from functions.additional_functions import get_current_date

class H_journal(Base):
	__tablename__ = 'h_journal'

	aendertext = sa.Column(sa.String, default="")
	ankauf = sa.Column(sa.Numeric, default=0)
	anzahl = sa.Column(sa.Integer, default=0)
	artart = sa.Column(sa.Integer, default=0)
	artnr = sa.Column(sa.Integer, default=0)
	artnrfront = sa.Column(sa.Integer, default=0)
	artnrlager = sa.Column(sa.Integer, default=0)
	artnrrezept = sa.Column(sa.Integer, default=0)
	betrag = sa.Column(sa.Numeric, default=0)
	betriebsnr = sa.Column(sa.Integer, default=0)
	bezeich = sa.Column(sa.String, default="")
	bill_datum = sa.Column(sa.Date, default=None)
	bon_nr = sa.Column(sa.Integer, default=0)
	bondruckernr = sa.Column(sa.Integer, default=0)
	buchflag = sa.Column(sa.Integer, default=0)
	departement = sa.Column(sa.Integer, default=0)
	endbon = sa.Column(sa.Integer, default=0)
	epreis = sa.Column(sa.Numeric, default=0)
	fremdwaehrng = sa.Column(sa.Numeric, default=0)
	gang = sa.Column(sa.Integer, default=0)
	kellner_nr = sa.Column(sa.Integer, default=0)
	lager_nr = sa.Column(sa.Integer, default=0)
	nachbuchen = sa.Column(sa.Boolean, default=False)
	prtflag = sa.Column(sa.Integer, default=0)
	rechnr = sa.Column(sa.Integer, default=0)
	schankbuch = sa.Column(sa.Integer, default=0)
	segmentcode = sa.Column(sa.Integer, default=0)
	service_code = sa.Column(sa.Integer, default=0)
	service_percent = sa.Column(sa.Numeric, default=0)
	steuer_percent = sa.Column(sa.Numeric, default=0)
	steuercode = sa.Column(sa.Integer, default=0)
	stornogrund = sa.Column(sa.String, default="")
	sysdate = sa.Column(sa.Date, default=get_current_date())
	tischnr = sa.Column(sa.Integer, default=0)
	trinkgeld = sa.Column(sa.Numeric, default=0)
	verkauf = sa.Column(sa.Numeric, default=0)
	wabkurz = sa.Column(sa.String, default="")
	waehrungcode = sa.Column(sa.Integer, default=0)
	waehrungsnr = sa.Column(sa.Integer, default=0)
	zeit = sa.Column(sa.Integer, default=0)
	zinr = sa.Column(sa.String, default="")
	_recid = sa.Column(sa.Integer, primary_key=True)
	def __init__(self, *args, **kwargs):
		kwargs.setdefault('aendertext', "")
		kwargs.setdefault('ankauf', 0)
		kwargs.setdefault('anzahl', 0)
		kwargs.setdefault('artart', 0)
		kwargs.setdefault('artnr', 0)
		kwargs.setdefault('artnrfront', 0)
		kwargs.setdefault('artnrlager', 0)
		kwargs.setdefault('artnrrezept', 0)
		kwargs.setdefault('betrag', 0)
		kwargs.setdefault('betriebsnr', 0)
		kwargs.setdefault('bezeich', "")
		kwargs.setdefault('bill_datum', None)
		kwargs.setdefault('bon_nr', 0)
		kwargs.setdefault('bondruckernr', 0)
		kwargs.setdefault('buchflag', 0)
		kwargs.setdefault('departement', 0)
		kwargs.setdefault('endbon', 0)
		kwargs.setdefault('epreis', 0)
		kwargs.setdefault('fremdwaehrng', 0)
		kwargs.setdefault('gang', 0)
		kwargs.setdefault('kellner_nr', 0)
		kwargs.setdefault('lager_nr', 0)
		kwargs.setdefault('nachbuchen', False)
		kwargs.setdefault('prtflag', 0)
		kwargs.setdefault('rechnr', 0)
		kwargs.setdefault('schankbuch', 0)
		kwargs.setdefault('segmentcode', 0)
		kwargs.setdefault('service_code', 0)
		kwargs.setdefault('service_percent', 0)
		kwargs.setdefault('steuer_percent', 0)
		kwargs.setdefault('steuercode', 0)
		kwargs.setdefault('stornogrund', "")
		kwargs.setdefault('sysdate', get_current_date())
		kwargs.setdefault('tischnr', 0)
		kwargs.setdefault('trinkgeld', 0)
		kwargs.setdefault('verkauf', 0)
		kwargs.setdefault('wabkurz', "")
		kwargs.setdefault('waehrungcode', 0)
		kwargs.setdefault('waehrungsnr', 0)
		kwargs.setdefault('zeit', 0)
		kwargs.setdefault('zinr', "")
		super(H_journal, self).__init__(*args, **kwargs)
