#version: 1.0.0.2

from sqlalchemy.dialects.postgresql import ARRAY
import sqlalchemy as sa
from models.base import Base
from functions.additional_functions import get_current_date

class L_artikel(Base):
	__tablename__ = 'l_artikel'

	alkoholgrad = sa.Column(sa.Numeric, default=0)
	anzverbrauch = sa.Column(sa.Numeric, default=0)
	artnr = sa.Column(sa.Integer, default=0)
	bestellt = sa.Column(sa.Boolean, default=False)
	betriebsnr = sa.Column(sa.Integer, default=0)
	bezeich = sa.Column(sa.String, default="")
	ek_aktuell = sa.Column(sa.Numeric, default=0)
	ek_letzter = sa.Column(sa.Numeric, default=0)
	endkum = sa.Column(sa.Integer, default=0)
	erfass_art = sa.Column(sa.Boolean, default=False)
	fibukonto = sa.Column(sa.String, default="")
	herkunft = sa.Column(sa.String, default="")
	inhalt = sa.Column(sa.Numeric, default=1)
	jahrgang = sa.Column(sa.Integer, default=0)
	letz_ausgang = sa.Column(sa.Date, default=None)
	letz_eingang = sa.Column(sa.Date, default=None)
	lief_artnr = sa.Column(ARRAY(sa.String),default=["","",""])
	lief_einheit = sa.Column(sa.Numeric, default=1)
	lief_nr1 = sa.Column(sa.Integer, default=0)
	lief_nr2 = sa.Column(sa.Integer, default=0)
	lief_nr3 = sa.Column(sa.Integer, default=0)
	lieferfrist = sa.Column(sa.Integer, default=0)
	masseinheit = sa.Column(sa.String, default="")
	min_bestand = sa.Column(sa.Numeric, default=0)
	traubensorte = sa.Column(sa.String, default="")
	vk_preis = sa.Column(sa.Numeric, default=0)
	wert_verbrau = sa.Column(sa.Numeric, default=0)
	zwkum = sa.Column(sa.Integer, default=0)
	_recid = sa.Column(sa.Integer, primary_key=True)
	def __init__(self, *args, **kwargs):
		kwargs.setdefault('alkoholgrad', 0)
		kwargs.setdefault('anzverbrauch', 0)
		kwargs.setdefault('artnr', 0)
		kwargs.setdefault('bestellt', False)
		kwargs.setdefault('betriebsnr', 0)
		kwargs.setdefault('bezeich', "")
		kwargs.setdefault('ek_aktuell', 0)
		kwargs.setdefault('ek_letzter', 0)
		kwargs.setdefault('endkum', 0)
		kwargs.setdefault('erfass_art', False)
		kwargs.setdefault('fibukonto', "")
		kwargs.setdefault('herkunft', "")
		kwargs.setdefault('inhalt', 1)
		kwargs.setdefault('jahrgang', 0)
		kwargs.setdefault('letz_ausgang', None)
		kwargs.setdefault('letz_eingang', None)
		kwargs.setdefault('lief_artnr', ["","",""])
		kwargs.setdefault('lief_einheit', 1)
		kwargs.setdefault('lief_nr1', 0)
		kwargs.setdefault('lief_nr2', 0)
		kwargs.setdefault('lief_nr3', 0)
		kwargs.setdefault('lieferfrist', 0)
		kwargs.setdefault('masseinheit', "")
		kwargs.setdefault('min_bestand', 0)
		kwargs.setdefault('traubensorte', "")
		kwargs.setdefault('vk_preis', 0)
		kwargs.setdefault('wert_verbrau', 0)
		kwargs.setdefault('zwkum', 0)
		super(L_artikel, self).__init__(*args, **kwargs)
