#version: 1.0.0.2

from sqlalchemy.dialects.postgresql import ARRAY
import sqlalchemy as sa
from models.base import Base
from functions.additional_functions import get_current_date

class L_order(Base):
	__tablename__ = 'l_order'

	angebot_lief = sa.Column(ARRAY(sa.Integer),default=[0,0,0])
	anzahl = sa.Column(sa.Numeric, default=0)
	artnr = sa.Column(sa.Integer, default=0)
	bestellart = sa.Column(sa.String, default="")
	bestelldatum = sa.Column(sa.Date, default=get_current_date())
	besteller = sa.Column(sa.String, default="")
	betriebsnr = sa.Column(sa.Integer, default=0)
	docu_nr = sa.Column(sa.String, default="")
	einzelpreis = sa.Column(sa.Numeric, default=0)
	flag = sa.Column(sa.Boolean, default=False)
	gedruckt = sa.Column(sa.Date, default=None)
	gefaxt = sa.Column(sa.Date, default=None)
	geliefert = sa.Column(sa.Numeric, default=0)
	herkunftflag = sa.Column(sa.Integer, default=0)
	lager_nr = sa.Column(sa.Integer, default=0)
	lief_fax = sa.Column(ARRAY(sa.String),default=["","",""])
	lief_nr = sa.Column(sa.Integer, default=0)
	lieferdatum = sa.Column(sa.Date, default=None)
	lieferdatum_eff = sa.Column(sa.Date, default=None)
	loeschflag = sa.Column(sa.Integer, default=0)
	op_art = sa.Column(sa.Integer, default=0)
	pos = sa.Column(sa.Integer, default=0)
	quality = sa.Column(sa.String, default="")
	rechnungspreis = sa.Column(sa.Numeric, default=0)
	rechnungswert = sa.Column(sa.Numeric, default=0)
	rueckgabegrund = sa.Column(sa.Integer, default=0)
	stornogrund = sa.Column(sa.String, default="")
	txtnr = sa.Column(sa.Integer, default=1)
	warenwert = sa.Column(sa.Numeric, default=0)
	zeit = sa.Column(sa.Integer, default=0)
	_recid = sa.Column(sa.Integer, primary_key=True)
	def __init__(self, *args, **kwargs):
		kwargs.setdefault('angebot_lief', [0,0,0])
		kwargs.setdefault('anzahl', 0)
		kwargs.setdefault('artnr', 0)
		kwargs.setdefault('bestellart', "")
		kwargs.setdefault('bestelldatum', get_current_date())
		kwargs.setdefault('besteller', "")
		kwargs.setdefault('betriebsnr', 0)
		kwargs.setdefault('docu_nr', "")
		kwargs.setdefault('einzelpreis', 0)
		kwargs.setdefault('flag', False)
		kwargs.setdefault('gedruckt', None)
		kwargs.setdefault('gefaxt', None)
		kwargs.setdefault('geliefert', 0)
		kwargs.setdefault('herkunftflag', 0)
		kwargs.setdefault('lager_nr', 0)
		kwargs.setdefault('lief_fax', ["","",""])
		kwargs.setdefault('lief_nr', 0)
		kwargs.setdefault('lieferdatum', None)
		kwargs.setdefault('lieferdatum_eff', None)
		kwargs.setdefault('loeschflag', 0)
		kwargs.setdefault('op_art', 0)
		kwargs.setdefault('pos', 0)
		kwargs.setdefault('quality', "")
		kwargs.setdefault('rechnungspreis', 0)
		kwargs.setdefault('rechnungswert', 0)
		kwargs.setdefault('rueckgabegrund', 0)
		kwargs.setdefault('stornogrund', "")
		kwargs.setdefault('txtnr', 1)
		kwargs.setdefault('warenwert', 0)
		kwargs.setdefault('zeit', 0)
		super(L_order, self).__init__(*args, **kwargs)
