#version: 1.0.0.2

from sqlalchemy.dialects.postgresql import ARRAY
import sqlalchemy as sa
from models.base import Base
from functions.additional_functions import get_current_date

class Reservation(Base):
	__tablename__ = 'reservation'

	activeflag = sa.Column(sa.Integer, default=0)
	ankzeit = sa.Column(sa.Integer, default=0)
	bediener_nr = sa.Column(sa.Integer, default=0)
	bemerk = sa.Column(sa.String, default="")
	bestat_datum = sa.Column(sa.Date, default=None)
	betrieb_gast = sa.Column(sa.Integer, default=0)
	betrieb_gastcomm = sa.Column(ARRAY(sa.Integer),default=[0,0,0])
	betrieb_gastherk = sa.Column(sa.Integer, default=0)
	betriebsnr = sa.Column(sa.Integer, default=0)
	briefnr = sa.Column(sa.Integer, default=0)
	deposit_type = sa.Column(sa.Integer, default=0)
	depositbez = sa.Column(sa.Numeric, default=0)
	depositbez2 = sa.Column(sa.Numeric, default=0)
	depositgef = sa.Column(sa.Numeric, default=0)
	depositgef2 = sa.Column(sa.Numeric, default=0)
	deptrans = sa.Column(sa.Date, default=None)
	gastnr = sa.Column(sa.Integer, default=0)
	gastnrherk = sa.Column(sa.Integer, default=0)
	groupname = sa.Column(sa.String, default="")
	grpflag = sa.Column(sa.Boolean, default=False)
	guestnrcom = sa.Column(ARRAY(sa.Integer),default=[0,0,0])
	herkunft = sa.Column(sa.String, default="")
	insurance = sa.Column(sa.Boolean, default=False)
	insurance_pct = sa.Column(sa.Numeric, default=0)
	kontakt_nr = sa.Column(sa.Integer, default=0)
	limitdate = sa.Column(sa.Date, default=None)
	limitdate2 = sa.Column(sa.Date, default=None)
	mutdat = sa.Column(sa.Date, default=None)
	name = sa.Column(sa.String, default="")
	point_resnr = sa.Column(sa.Integer, default=0)
	refdatum = sa.Column(sa.Date, default=get_current_date())
	resart = sa.Column(sa.Integer, default=1)
	resdat = sa.Column(sa.Date, default=get_current_date())
	resnr = sa.Column(sa.Integer, default=0)
	segmentcode = sa.Column(sa.Integer, default=0)
	source_code = sa.Column(sa.Integer, default=0)
	total_price = sa.Column(sa.Numeric, default=0)
	useridanlage = sa.Column(sa.String, default="")
	useridmutat = sa.Column(sa.String, default="")
	verstat = sa.Column(sa.Integer, default=0)
	vesrcod = sa.Column(sa.String, default="")
	vesrdepot = sa.Column(sa.String, default="")
	vesrdepot2 = sa.Column(sa.String, default="")
	zahldatum = sa.Column(sa.Date, default=None)
	zahldatum2 = sa.Column(sa.Date, default=None)
	zahlkonto = sa.Column(sa.Integer, default=0)
	zahlkonto2 = sa.Column(sa.Integer, default=0)
	_recid = sa.Column(sa.Integer, primary_key=True)
	def __init__(self, *args, **kwargs):
		kwargs.setdefault('activeflag', 0)
		kwargs.setdefault('ankzeit', 0)
		kwargs.setdefault('bediener_nr', 0)
		kwargs.setdefault('bemerk', "")
		kwargs.setdefault('bestat_datum', None)
		kwargs.setdefault('betrieb_gast', 0)
		kwargs.setdefault('betrieb_gastcomm', [0,0,0])
		kwargs.setdefault('betrieb_gastherk', 0)
		kwargs.setdefault('betriebsnr', 0)
		kwargs.setdefault('briefnr', 0)
		kwargs.setdefault('deposit_type', 0)
		kwargs.setdefault('depositbez', 0)
		kwargs.setdefault('depositbez2', 0)
		kwargs.setdefault('depositgef', 0)
		kwargs.setdefault('depositgef2', 0)
		kwargs.setdefault('deptrans', None)
		kwargs.setdefault('gastnr', 0)
		kwargs.setdefault('gastnrherk', 0)
		kwargs.setdefault('groupname', "")
		kwargs.setdefault('grpflag', False)
		kwargs.setdefault('guestnrcom', [0,0,0])
		kwargs.setdefault('herkunft', "")
		kwargs.setdefault('insurance', False)
		kwargs.setdefault('insurance_pct', 0)
		kwargs.setdefault('kontakt_nr', 0)
		kwargs.setdefault('limitdate', None)
		kwargs.setdefault('limitdate2', None)
		kwargs.setdefault('mutdat', None)
		kwargs.setdefault('name', "")
		kwargs.setdefault('point_resnr', 0)
		kwargs.setdefault('refdatum', get_current_date())
		kwargs.setdefault('resart', 1)
		kwargs.setdefault('resdat', get_current_date())
		kwargs.setdefault('resnr', 0)
		kwargs.setdefault('segmentcode', 0)
		kwargs.setdefault('source_code', 0)
		kwargs.setdefault('total_price', 0)
		kwargs.setdefault('useridanlage', "")
		kwargs.setdefault('useridmutat', "")
		kwargs.setdefault('verstat', 0)
		kwargs.setdefault('vesrcod', "")
		kwargs.setdefault('vesrdepot', "")
		kwargs.setdefault('vesrdepot2', "")
		kwargs.setdefault('zahldatum', None)
		kwargs.setdefault('zahldatum2', None)
		kwargs.setdefault('zahlkonto', 0)
		kwargs.setdefault('zahlkonto2', 0)
		super(Reservation, self).__init__(*args, **kwargs)
