#version: 1.0.0.2

from sqlalchemy.dialects.postgresql import ARRAY
import sqlalchemy as sa
from models.base import Base
from functions.additional_functions import get_current_date

class Rg_reports(Base):
	__tablename__ = 'rg_reports'

	activeflag = sa.Column(sa.Integer, default=0)
	char1 = sa.Column(sa.String, default="")
	char2 = sa.Column(sa.String, default="")
	char3 = sa.Column(sa.String, default="")
	col_dim = sa.Column(sa.String, default="")
	created_by = sa.Column(sa.String, default="")
	created_date = sa.Column(sa.Date, default=None)
	date1 = sa.Column(sa.Date, default=None)
	date2 = sa.Column(sa.Date, default=None)
	facts_dim = sa.Column(sa.String, default="")
	form_dim = sa.Column(sa.String, default="")
	last_updated = sa.Column(sa.Date, default=None)
	logi1 = sa.Column(sa.Boolean, default=False)
	logi2 = sa.Column(sa.Boolean, default=False)
	metadata_ = sa.Column('metadata', sa.String)
	num1 = sa.Column(sa.Integer, default=0)
	num2 = sa.Column(sa.Integer, default=0)
	num3 = sa.Column(sa.Integer, default=0)
	out_dim = sa.Column(sa.String, default="")
	overwrite_by = sa.Column(sa.String, default="")
	ovwrite_by_group = sa.Column(sa.String, default="")
	report_group = sa.Column(sa.Integer, default=0)
	report_sub = sa.Column(sa.Integer, default=0)
	report_title = sa.Column(sa.String, default="")
	reportnr = sa.Column(sa.Integer, default=0)
	row_dim = sa.Column(sa.String, default="")
	slice_name = sa.Column(ARRAY(sa.String),default=["","","","","","","","",""])
	updated_by = sa.Column(sa.String, default="")
	usercode = sa.Column(sa.String, default="")
	usr_access = sa.Column(sa.String, default="")
	view_name = sa.Column(ARRAY(sa.String),default=["","","","","","","","",""])
	visible_to_group = sa.Column(sa.String, default="")
	_recid = sa.Column(sa.Integer, primary_key=True)
	def __init__(self, *args, **kwargs):
		kwargs.setdefault('activeflag', 0)
		kwargs.setdefault('char1', "")
		kwargs.setdefault('char2', "")
		kwargs.setdefault('char3', "")
		kwargs.setdefault('col_dim', "")
		kwargs.setdefault('created_by', "")
		kwargs.setdefault('created_date', None)
		kwargs.setdefault('date1', None)
		kwargs.setdefault('date2', None)
		kwargs.setdefault('facts_dim', "")
		kwargs.setdefault('form_dim', "")
		kwargs.setdefault('last_updated', None)
		kwargs.setdefault('logi1', False)
		kwargs.setdefault('logi2', False)
		kwargs.setdefault('metadata', False)
		kwargs.setdefault('num1', 0)
		kwargs.setdefault('num2', 0)
		kwargs.setdefault('num3', 0)
		kwargs.setdefault('out_dim', "")
		kwargs.setdefault('overwrite_by', "")
		kwargs.setdefault('ovwrite_by_group', "")
		kwargs.setdefault('report_group', 0)
		kwargs.setdefault('report_sub', 0)
		kwargs.setdefault('report_title', "")
		kwargs.setdefault('reportnr', 0)
		kwargs.setdefault('row_dim', "")
		kwargs.setdefault('slice_name', ["","","","","","","","",""])
		kwargs.setdefault('updated_by', "")
		kwargs.setdefault('usercode', "")
		kwargs.setdefault('usr_access', "")
		kwargs.setdefault('view_name', ["","","","","","","","",""])
		kwargs.setdefault('visible_to_group', "")
		super(Rg_reports, self).__init__(*args, **kwargs)
