#version: 1.0.0.2

from sqlalchemy.dialects.postgresql import ARRAY
import sqlalchemy as sa
from models.base import Base
from functions.additional_functions import get_current_date

class Sms_received(Base):
	__tablename__ = 'sms_received'

	arrival = sa.Column(sa.Date, default=None)
	bemerk = sa.Column(sa.String, default="")
	char1 = sa.Column(sa.String, default="")
	char2 = sa.Column(sa.String, default="")
	char3 = sa.Column(sa.String, default="")
	date1 = sa.Column(sa.Date, default=None)
	date2 = sa.Column(sa.Date, default=None)
	date3 = sa.Column(sa.Date, default=None)
	datum = sa.Column(sa.Date, default=None)
	departure = sa.Column(sa.Date, default=None)
	email = sa.Column(sa.String, default="")
	firstname = sa.Column(sa.String, default="")
	flag = sa.Column(sa.Integer, default=0)
	key = sa.Column(sa.String, default="")
	mobile_phone = sa.Column(sa.String, default="")
	name = sa.Column(sa.String, default="")
	number1 = sa.Column(sa.Integer, default=0)
	number2 = sa.Column(sa.Integer, default=0)
	number3 = sa.Column(sa.Integer, default=0)
	origin_msg = sa.Column(sa.String, default="")
	qty = sa.Column(sa.Integer, default=0)
	reply_str = sa.Column(sa.String, default="")
	resnr = sa.Column(sa.Integer, default=0)
	rmcat = sa.Column(sa.String, default="")
	room_str = sa.Column(sa.String, default="")
	zeit = sa.Column(sa.String, default="")
	_recid = sa.Column(sa.Integer, primary_key=True)
	def __init__(self, *args, **kwargs):
		kwargs.setdefault('arrival', None)
		kwargs.setdefault('bemerk', "")
		kwargs.setdefault('char1', "")
		kwargs.setdefault('char2', "")
		kwargs.setdefault('char3', "")
		kwargs.setdefault('date1', None)
		kwargs.setdefault('date2', None)
		kwargs.setdefault('date3', None)
		kwargs.setdefault('datum', None)
		kwargs.setdefault('departure', None)
		kwargs.setdefault('email', "")
		kwargs.setdefault('firstname', "")
		kwargs.setdefault('flag', 0)
		kwargs.setdefault('key', "")
		kwargs.setdefault('mobile_phone', "")
		kwargs.setdefault('name', "")
		kwargs.setdefault('number1', 0)
		kwargs.setdefault('number2', 0)
		kwargs.setdefault('number3', 0)
		kwargs.setdefault('origin_msg', "")
		kwargs.setdefault('qty', 0)
		kwargs.setdefault('reply_str', "")
		kwargs.setdefault('resnr', 0)
		kwargs.setdefault('rmcat', "")
		kwargs.setdefault('room_str', "")
		kwargs.setdefault('zeit', "")
		super(Sms_received, self).__init__(*args, **kwargs)
