#version: 1.0.0.2

from sqlalchemy.dialects.postgresql import ARRAY
import sqlalchemy as sa
from models.base import Base
from functions.additional_functions import get_current_date

class Zimmer(Base):
	__tablename__ = 'zimmer'

	bediener_nr_stat = sa.Column(sa.Integer, default=0)
	betriebsnr = sa.Column(sa.Integer, default=0)
	bezeich = sa.Column(sa.String, default="")
	build = sa.Column(sa.String, default="")
	code = sa.Column(sa.String, default="")
	etage = sa.Column(sa.Integer, default=0)
	features = sa.Column(sa.String, default="")
	fixpreis = sa.Column(sa.Boolean, default=False)
	flag1 = sa.Column(sa.Integer, default=0)
	flag2 = sa.Column(sa.Integer, default=0)
	flag3 = sa.Column(sa.Integer, default=0)
	flag4 = sa.Column(sa.Integer, default=0)
	himmelsr = sa.Column(sa.String, default="")
	house_status = sa.Column(sa.Integer, default=0)
	kbezeich = sa.Column(sa.String, default="")
	nebenstelle = sa.Column(sa.String, default="")
	nebstflag = sa.Column(sa.Integer, default=0)
	owner_nr = sa.Column(sa.Integer, default=0)
	personal = sa.Column(sa.Boolean, default=False)
	personen = sa.Column(sa.Integer, default=0)
	prioritaet = sa.Column(sa.Integer, default=1)
	reihenfolge = sa.Column(sa.Integer, default=0)
	setup = sa.Column(sa.Integer, default=0)
	sleeping = sa.Column(sa.Boolean, default=False)
	sollflag = sa.Column(sa.Integer, default=0)
	typ = sa.Column(sa.Integer, default=0)
	verbindung = sa.Column(ARRAY(sa.String),default=["","",""])
	vid_actuel = sa.Column(sa.Integer, default=0)
	vid_request = sa.Column(sa.Integer, default=0)
	wertigkeit = sa.Column(sa.Integer, default=1)
	zikatnr = sa.Column(sa.Integer, default=0)
	zikennz = sa.Column(sa.String, default="")
	zinr = sa.Column(sa.String, default="1")
	zistatus = sa.Column(sa.Integer, default=0)
	_recid = sa.Column(sa.Integer, primary_key=True)
	def __init__(self, *args, **kwargs):
		kwargs.setdefault('bediener_nr_stat', 0)
		kwargs.setdefault('betriebsnr', 0)
		kwargs.setdefault('bezeich', "")
		kwargs.setdefault('build', "")
		kwargs.setdefault('code', "")
		kwargs.setdefault('etage', 0)
		kwargs.setdefault('features', "")
		kwargs.setdefault('fixpreis', False)
		kwargs.setdefault('flag1', 0)
		kwargs.setdefault('flag2', 0)
		kwargs.setdefault('flag3', 0)
		kwargs.setdefault('flag4', 0)
		kwargs.setdefault('himmelsr', "")
		kwargs.setdefault('house_status', 0)
		kwargs.setdefault('kbezeich', "")
		kwargs.setdefault('nebenstelle', "")
		kwargs.setdefault('nebstflag', 0)
		kwargs.setdefault('owner_nr', 0)
		kwargs.setdefault('personal', False)
		kwargs.setdefault('personen', 0)
		kwargs.setdefault('prioritaet', 1)
		kwargs.setdefault('reihenfolge', 0)
		kwargs.setdefault('setup', 0)
		kwargs.setdefault('sleeping', False)
		kwargs.setdefault('sollflag', 0)
		kwargs.setdefault('typ', 0)
		kwargs.setdefault('verbindung', ["","",""])
		kwargs.setdefault('vid_actuel', 0)
		kwargs.setdefault('vid_request', 0)
		kwargs.setdefault('wertigkeit', 1)
		kwargs.setdefault('zikatnr', 0)
		kwargs.setdefault('zikennz', "")
		kwargs.setdefault('zinr', "1")
		kwargs.setdefault('zistatus', 0)
		super(Zimmer, self).__init__(*args, **kwargs)
