from sqlalchemy.dialects.postgresql import ARRAY
import sqlalchemy as sa
from models.base import Base
from functions.additional_functions import get_current_date

class Artikel(Base):
	__tablename__ = 'artikel'

	abbuchung = sa.Column(sa.Integer, default=0)
	abrart = sa.Column(sa.Integer, default=0)
	activeflag = sa.Column(sa.Boolean, default=False)
	anwdauer = sa.Column(sa.Integer, default=0)
	anwkab = sa.Column(ARRAY(sa.Integer),default=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0])
	anwpreis = sa.Column(ARRAY(sa.Numeric),default=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0])
	anwtage = sa.Column(ARRAY(sa.Integer),default=[0,0,0,0,0,0,0])
	anzahl = sa.Column(sa.Integer, default=0)
	anzpunkte = sa.Column(sa.Numeric, default=0)
	aposit = sa.Column(sa.Integer, default=0)
	artart = sa.Column(sa.Integer, default=0)
	artgrp = sa.Column(sa.Integer, default=0)
	artnr = sa.Column(sa.Integer, default=0)
	artnrlager = sa.Column(sa.Integer, default=0)
	artnrrezept = sa.Column(sa.Integer, default=0)
	autofakt = sa.Column(sa.Boolean, default=False)
	autosaldo = sa.Column(sa.Boolean, default=False)
	betriebsnr = sa.Column(sa.Integer, default=0)
	bezaendern = sa.Column(sa.Boolean, default=False)
	bezeich = sa.Column(sa.String, default="")
	bezeich1 = sa.Column(sa.String, default="")
	bezeich2 = sa.Column(sa.String, default="")
	bezeich3 = sa.Column(sa.String, default="")
	bezeich4 = sa.Column(sa.String, default="")
	blockcheck = sa.Column(sa.Boolean, default=False)
	booktyp = sa.Column(sa.Integer, default=0)
	comment = sa.Column(sa.Boolean, default=False)
	departement = sa.Column(sa.Integer, default=0)
	e_gueltig = sa.Column(sa.Date, default=None)
	eigentuemer = sa.Column(sa.Boolean, default=False)
	endkum = sa.Column(sa.Integer, default=0)
	epreis = sa.Column(sa.Numeric, default=0)
	fibukonto = sa.Column(sa.String, default="")
	frontbuchung = sa.Column(sa.Boolean, default=False)
	kassabuch = sa.Column(sa.Boolean, default=False)
	kassarapport = sa.Column(sa.Boolean, default=False)
	lagernr = sa.Column(sa.Integer, default=0)
	mansteuer = sa.Column(sa.Boolean, default=False)
	masseurres = sa.Column(sa.Boolean, default=False)
	mwst_code = sa.Column(sa.Integer, default=0)
	mwst_incl = sa.Column(sa.Boolean, default=False)
	position = sa.Column(sa.String, default="")
	preistabelle = sa.Column(sa.Boolean, default=False)
	pricetab = sa.Column(sa.Boolean, default=False)
	prov_code = sa.Column(sa.Integer, default=0)
	prozent = sa.Column(sa.Numeric, default=0)
	quittung = sa.Column(sa.Boolean, default=False)
	reinigung = sa.Column(sa.Integer, default=0)
	resart = sa.Column(sa.Boolean, default=False)
	reservieren = sa.Column(sa.Boolean, default=False)
	rg_position = sa.Column(sa.Boolean, default=False)
	ruhedauer = sa.Column(sa.Integer, default=0)
	s_gueltig = sa.Column(sa.Date, default=None)
	serv_incl = sa.Column(sa.Boolean, default=False)
	service_code = sa.Column(sa.Integer, default=0)
	umsatzart = sa.Column(sa.Integer, default=0)
	zwkum = sa.Column(sa.Integer, default=0)
	_recid = sa.Column(sa.Integer, primary_key=True)
