#version: 1.0.0.3

from sqlalchemy.dialects.postgresql import ARRAY
import sqlalchemy as sa
from models.base import Base
from functions.additional_functions import get_current_date

class Bankrep(Base):
	__tablename__ = 'bankrep'

	adurch = sa.Column(sa.String, default="")
	anlass = sa.Column(ARRAY(sa.String),default=["",""])
	ape__getraenke = sa.Column(ARRAY(sa.String),default=["","",""])
	ape__speisen = sa.Column(ARRAY(sa.String),default=["","",""])
	art = sa.Column(ARRAY(sa.Boolean),default=[False,False,False])
	auf__datum = sa.Column(sa.Date, default=None)
	bankettnr = sa.Column(sa.Integer, default=0)
	bestellt__durch = sa.Column(sa.String, default="")
	betriebsnr = sa.Column(sa.Integer, default=0)
	datum = sa.Column(sa.Date, default=None)
	dekoration = sa.Column(ARRAY(sa.String),default=["","","","","",""])
	departement = sa.Column(sa.Integer, default=0)
	digestif = sa.Column(ARRAY(sa.String),default=["",""])
	fotograf = sa.Column(ARRAY(sa.String),default=["",""])
	gaestebuch = sa.Column(sa.String, default="")
	geschenk = sa.Column(sa.String, default="")
	hotelzimmer = sa.Column(ARRAY(sa.String),default=["",""])
	kaffee = sa.Column(sa.String, default="")
	kartentext = sa.Column(ARRAY(sa.String),default=["","","","",""])
	kontaktperson = sa.Column(ARRAY(sa.String),default=["",""])
	menue = sa.Column(ARRAY(sa.String),default=["","","","","","","","","","","","","","","","",""])
	menuekarten = sa.Column(ARRAY(sa.String),default=["",""])
	musik = sa.Column(ARRAY(sa.String),default=["",""])
	nachtverpflegung = sa.Column(ARRAY(sa.String),default=["","",""])
	nachtzuschlag = sa.Column(sa.String, default="")
	nadkarte = sa.Column(sa.String, default="")
	ndessen = sa.Column(ARRAY(sa.String),default=["","",""])
	personen = sa.Column(sa.Integer, default=0)
	personen2 = sa.Column(ARRAY(sa.String),default=["","","","","",""])
	preismenu = sa.Column(sa.String, default="")
	raeume = sa.Column(ARRAY(sa.String),default=["","","","","",""])
	raummiete = sa.Column(ARRAY(sa.String),default=["","","","","",""])
	rechnungsanschrift = sa.Column(ARRAY(sa.String),default=["","","","",""])
	segmentcode = sa.Column(sa.Integer, default=0)
	seite = sa.Column(sa.Integer, default=0)
	sonst__bewirt = sa.Column(ARRAY(sa.String),default=["",""])
	sonstiges = sa.Column(ARRAY(sa.String),default=["",""])
	technik = sa.Column(ARRAY(sa.String),default=["",""])
	telefax = sa.Column(sa.String, default="")
	telefon = sa.Column(sa.String, default="")
	tischform = sa.Column(ARRAY(sa.String),default=["","","","","",""])
	tischordnung = sa.Column(sa.String, default="")
	tischplan = sa.Column(sa.String, default="")
	tischreden = sa.Column(ARRAY(sa.String),default=["","","","",""])
	uhrzeit = sa.Column(sa.String, default="")
	uhrzeiten = sa.Column(ARRAY(sa.String),default=["","","","","",""])
	verteiler = sa.Column(ARRAY(sa.Boolean),default=[False,False,False,False,False,False,False,False,False,False])
	vgeschrieben = sa.Column(sa.String, default="")
	vkontrolliert = sa.Column(sa.String, default="")
	weine = sa.Column(ARRAY(sa.String),default=["","","","","","","","","","","","","","","","",""])
	wochentag = sa.Column(sa.String, default="")
	zweck = sa.Column(ARRAY(sa.String),default=["","","","","",""])
	_recid = sa.Column(sa.Integer, primary_key=True)
	def __init__(self, *args, **kwargs):
		kwargs.setdefault('adurch', "")
		kwargs.setdefault('anlass', ["",""])
		kwargs.setdefault('ape__getraenke', ["","",""])
		kwargs.setdefault('ape__speisen', ["","",""])
		kwargs.setdefault('art', [False,False,False])
		kwargs.setdefault('auf__datum', None)
		kwargs.setdefault('bankettnr', 0)
		kwargs.setdefault('bestellt__durch', "")
		kwargs.setdefault('betriebsnr', 0)
		kwargs.setdefault('datum', None)
		kwargs.setdefault('dekoration', ["","","","","",""])
		kwargs.setdefault('departement', 0)
		kwargs.setdefault('digestif', ["",""])
		kwargs.setdefault('fotograf', ["",""])
		kwargs.setdefault('gaestebuch', "")
		kwargs.setdefault('geschenk', "")
		kwargs.setdefault('hotelzimmer', ["",""])
		kwargs.setdefault('kaffee', "")
		kwargs.setdefault('kartentext', ["","","","",""])
		kwargs.setdefault('kontaktperson', ["",""])
		kwargs.setdefault('menue', ["","","","","","","","","","","","","","","","",""])
		kwargs.setdefault('menuekarten', ["",""])
		kwargs.setdefault('musik', ["",""])
		kwargs.setdefault('nachtverpflegung', ["","",""])
		kwargs.setdefault('nachtzuschlag', "")
		kwargs.setdefault('nadkarte', "")
		kwargs.setdefault('ndessen', ["","",""])
		kwargs.setdefault('personen', 0)
		kwargs.setdefault('personen2', ["","","","","",""])
		kwargs.setdefault('preismenu', "")
		kwargs.setdefault('raeume', ["","","","","",""])
		kwargs.setdefault('raummiete', ["","","","","",""])
		kwargs.setdefault('rechnungsanschrift', ["","","","",""])
		kwargs.setdefault('segmentcode', 0)
		kwargs.setdefault('seite', 0)
		kwargs.setdefault('sonst__bewirt', ["",""])
		kwargs.setdefault('sonstiges', ["",""])
		kwargs.setdefault('technik', ["",""])
		kwargs.setdefault('telefax', "")
		kwargs.setdefault('telefon', "")
		kwargs.setdefault('tischform', ["","","","","",""])
		kwargs.setdefault('tischordnung', "")
		kwargs.setdefault('tischplan', "")
		kwargs.setdefault('tischreden', ["","","","",""])
		kwargs.setdefault('uhrzeit', "")
		kwargs.setdefault('uhrzeiten', ["","","","","",""])
		kwargs.setdefault('verteiler', [False,False,False,False,False,False,False,False,False,False])
		kwargs.setdefault('vgeschrieben', "")
		kwargs.setdefault('vkontrolliert', "")
		kwargs.setdefault('weine', ["","","","","","","","","","","","","","","","",""])
		kwargs.setdefault('wochentag', "")
		kwargs.setdefault('zweck', ["","","","","",""])
		super(Bankrep, self).__init__(*args, **kwargs)
