from sqlalchemy.dialects.postgresql import ARRAY
import sqlalchemy as sa
from models.base import Base
from functions.additional_functions import get_current_date

class Bill(Base):
	__tablename__ = 'bill'

	argtumsatz = sa.Column(sa.Numeric, default=0)
	arrangemdat = sa.Column(sa.Date, default=None)
	betrieb_gast = sa.Column(sa.Integer, default=0)
	betriebsnr = sa.Column(sa.Integer, default=0)
	billbankett = sa.Column(sa.Boolean, default=False)
	billkur = sa.Column(sa.Boolean, default=False)
	billmaster = sa.Column(sa.Boolean, default=False)
	billnr = sa.Column(sa.Integer, default=1)
	billref = sa.Column(sa.Integer, default=0)
	billtyp = sa.Column(sa.Integer, default=0)
	bilname = sa.Column(sa.String, default="")
	datum = sa.Column(sa.Date, default=lambda: get_current_date())
	f_b_umsatz = sa.Column(sa.Numeric, default=0)
	firstper = sa.Column(sa.Boolean, default=True)
	flag = sa.Column(sa.Integer, default=0)
	gastnr = sa.Column(sa.Integer, default=0)
	gesamtumsatz = sa.Column(sa.Numeric, default=0)
	init_argt = sa.Column(sa.Numeric, default=0)
	kontakt_nr = sa.Column(sa.Integer, default=0)
	logidat = sa.Column(sa.Date, default=None)
	logiernachte = sa.Column(sa.Integer, default=0)
	logisumsatz = sa.Column(sa.Numeric, default=0)
	mwst = sa.Column(ARRAY(sa.Numeric),default=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0])
	name = sa.Column(sa.String, default="")
	nextargt_bookdate = sa.Column(sa.Date, default=None)
	oldzinr = sa.Column(sa.String, default="")
	parent_nr = sa.Column(sa.Integer, default=0)
	printnr = sa.Column(sa.Integer, default=0)
	rechnr = sa.Column(sa.Integer, default=0)
	rechnr2 = sa.Column(sa.Integer, default=0)
	reslinnr = sa.Column(sa.Integer, default=1)
	resnr = sa.Column(sa.Integer, default=0)
	rest_tage = sa.Column(sa.Integer, default=0)
	restargt = sa.Column(sa.Numeric, default=0)
	rgdruck = sa.Column(sa.Integer, default=0)
	roomcharge = sa.Column(sa.Boolean, default=False)
	saldo = sa.Column(sa.Numeric, default=0)
	segmentcode = sa.Column(sa.Integer, default=0)
	service = sa.Column(ARRAY(sa.Numeric),default=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0])
	sonst_umsatz = sa.Column(sa.Numeric, default=0)
	t_rechnr = sa.Column(sa.Integer, default=0)
	taxsumme = sa.Column(sa.Numeric, default=0)
	teleinheit = sa.Column(sa.Integer, default=0)
	telsumme = sa.Column(sa.Numeric, default=0)
	umleit_zinr = sa.Column(sa.String, default="")
	ums_kurz = sa.Column(sa.Numeric, default=0)
	ums_lang = sa.Column(sa.Numeric, default=0)
	verstat = sa.Column(sa.Integer, default=0)
	vesrcod = sa.Column(sa.String, default="")
	vesrdat = sa.Column(sa.Date, default=None)
	vesrdep = sa.Column(sa.Numeric, default=0)
	vesrdepot = sa.Column(sa.String, default="")
	vesrdepot2 = sa.Column(sa.String, default="")
	zinr = sa.Column(sa.String, default="")
	_recid = sa.Column(sa.Integer, primary_key=True)
