from sqlalchemy.dialects.postgresql import ARRAY
import sqlalchemy as sa
from models.base import Base
from functions.additional_functions import get_current_date

class Bk_func(Base):
	__tablename__ = 'bk_func'

	abreise = sa.Column(sa.String, default="")
	adurch = sa.Column(sa.String, default="")
	anlass = sa.Column(ARRAY(sa.String),default=["",""])
	ape__getraenke = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	ape__speisen = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	arrival = sa.Column(ARRAY(sa.String),default=["","","",""])
	artikel_glob = sa.Column(sa.Boolean, default=False)
	artikel_zg1 = sa.Column(ARRAY(sa.Boolean),default=[False,False,False,False,False,False,False,False])
	artikel_zg2 = sa.Column(ARRAY(sa.Boolean),default=[False,False,False,False,False,False,False,False])
	artikel_zg3 = sa.Column(ARRAY(sa.Boolean),default=[False,False,False,False,False,False,False,False])
	auf__datum = sa.Column(sa.Date, default=None)
	bediener_nr = sa.Column(sa.Integer, default=0)
	bemerkung = sa.Column(sa.String, default="")
	bestellt__durch = sa.Column(sa.String, default="")
	betriebsnr = sa.Column(sa.Integer, default=0)
	bis_datum = sa.Column(sa.Date, default=None)
	c_resstatus = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	dance = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	datum = sa.Column(sa.Date, default=None)
	deko2 = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	dekoration = sa.Column(ARRAY(sa.String),default=["","","","","",""])
	departement = sa.Column(sa.Integer, default=0)
	digestif = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	dinner = sa.Column(ARRAY(sa.String),default=["","","",""])
	f_menu = sa.Column(ARRAY(sa.String),default=["","","",""])
	f_no = sa.Column(ARRAY(sa.String),default=["","","",""])
	fotograf = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	gaestebuch = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	garderobe = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	gema = sa.Column(sa.String, default="")
	geschenk = sa.Column(sa.String, default="")
	hotel_no = sa.Column(sa.String, default="")
	hotel_yes = sa.Column(sa.String, default="")
	hotelzimmer = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	kaffee = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	kartentext = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	kontaktperson = sa.Column(ARRAY(sa.String),default=["",""])
	kuenstler = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	menue = sa.Column(ARRAY(sa.String),default=["","","","","","","","","","","","","","","","","","","",""])
	menuekarten = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	musik = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	nachtverpflegung = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	nachtzuschlag = sa.Column(sa.String, default="")
	nadkarte = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	ndessen = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	personen = sa.Column(sa.Integer, default=0)
	personen2 = sa.Column(ARRAY(sa.String),default=["","","","","",""])
	preismenu = sa.Column(sa.String, default="")
	price = sa.Column(sa.String, default="")
	r_resstatus = sa.Column(ARRAY(sa.Integer),default=[0,0,0,0,0,0,0,0])
	raeume = sa.Column(ARRAY(sa.String),default=["","","","","",""])
	raumbezeichnung = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	raummiete = sa.Column(ARRAY(sa.String),default=["","","","","",""])
	rechnungsanschrift = sa.Column(ARRAY(sa.String),default=["","","","",""])
	resnr = sa.Column(ARRAY(sa.Integer),default=[0,0,0,0,0,0,0,0])
	resstatus = sa.Column(sa.Integer, default=0)
	rpersonen = sa.Column(ARRAY(sa.Integer),default=[0,0,0,0,0,0,0,0])
	rpreis = sa.Column(ARRAY(sa.Numeric),default=[0,0,0,0,0,0,0,0])
	segmentcode = sa.Column(sa.Integer, default=0)
	service = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	sonst__bewirt = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	sonstiges = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	technik = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	telefax = sa.Column(sa.String, default="")
	telefon = sa.Column(sa.String, default="")
	tischform = sa.Column(ARRAY(sa.String),default=["","","","","",""])
	tischordnung = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	tischplan = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	tischreden = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	uhrzeit = sa.Column(sa.String, default="")
	uhrzeiten = sa.Column(ARRAY(sa.String),default=["","","","","",""])
	v_kontaktperson = sa.Column(ARRAY(sa.String),default=["",""])
	v_telefax = sa.Column(sa.String, default="")
	v_telefon = sa.Column(sa.String, default="")
	va_ablauf = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	veran_nr = sa.Column(sa.Integer, default=0)
	veran_seite = sa.Column(sa.Integer, default=0)
	veranstalteranschrift = sa.Column(ARRAY(sa.String),default=["","","","",""])
	vgeschrieben = sa.Column(sa.String, default="")
	vip = sa.Column(ARRAY(sa.String),default=["","","","","","","",""])
	vkontrolliert = sa.Column(sa.String, default="")
	weine = sa.Column(ARRAY(sa.String),default=["","","","","","","","","","","","","","","","","","","",""])
	wochentag = sa.Column(sa.String, default="")
	zweck = sa.Column(ARRAY(sa.String),default=["","","","","",""])
	_recid = sa.Column(sa.Integer, primary_key=True)
