#version: 1.0.0.3

from sqlalchemy.dialects.postgresql import ARRAY
import sqlalchemy as sa
from models.base import Base
from functions.additional_functions import get_current_date

class Cl_member(Base):
	__tablename__ = 'cl_member'

	agreenum = sa.Column(sa.String, default="")
	billcycle = sa.Column(sa.Integer, default=0)
	billgastnr = sa.Column(sa.Integer, default=0)
	char1 = sa.Column(sa.String, default="")
	char2 = sa.Column(sa.String, default="")
	char3 = sa.Column(sa.String, default="")
	checked_in = sa.Column(sa.Boolean, default=False)
	ci_time = sa.Column(sa.Integer, default=0)
	co_time = sa.Column(sa.Integer, default=0)
	codenum = sa.Column(sa.String, default="")
	created_date = sa.Column(sa.Date, default=None)
	date1 = sa.Column(sa.Date, default=None)
	date2 = sa.Column(sa.Date, default=None)
	date3 = sa.Column(sa.Date, default=None)
	deci1 = sa.Column(sa.Numeric, default=0)
	deci2 = sa.Column(sa.Numeric, default=0)
	deci3 = sa.Column(sa.Numeric, default=0)
	disc = sa.Column(sa.Numeric, default=0)
	emergency_nm = sa.Column(sa.String, default="")
	emergency_ph = sa.Column(sa.String, default="")
	expired_date = sa.Column(sa.Date, default=None)
	freezeto = sa.Column(sa.Date, default=None)
	gastnr = sa.Column(sa.Integer, default=0)
	group_nm = sa.Column(sa.String, default="")
	homeclub = sa.Column(sa.Integer, default=0)
	income = sa.Column(sa.Numeric, default=0)
	join_date = sa.Column(sa.Date, default=None)
	last_changed = sa.Column(sa.Date, default=None)
	last_renewed = sa.Column(sa.Date, default=None)
	last_update = sa.Column(sa.Date, default=None)
	last_visit = sa.Column(sa.Date, default=None)
	lastbill = sa.Column(sa.Date, default=None)
	load_by = sa.Column(sa.String, default="")
	lock_num = sa.Column(sa.String, default="")
	locker = sa.Column(sa.Integer, default=0)
	lockerdate = sa.Column(sa.Date, default=None)
	logi1 = sa.Column(sa.Boolean, default=False)
	logi2 = sa.Column(sa.Boolean, default=False)
	logi3 = sa.Column(sa.Boolean, default=False)
	main_gastnr = sa.Column(sa.Integer, default=0)
	medicalnote = sa.Column(sa.String, default="")
	membertype = sa.Column(sa.Integer, default=0)
	memstatus = sa.Column(sa.Integer, default=0)
	nextbill = sa.Column(sa.Date, default=None)
	num1 = sa.Column(sa.Integer, default=0)
	num2 = sa.Column(sa.Integer, default=0)
	num3 = sa.Column(sa.Integer, default=0)
	numfreeze = sa.Column(sa.Integer, default=1)
	paysched = sa.Column(sa.Integer, default=0)
	pict_file = sa.Column(sa.String, default="")
	relation = sa.Column(sa.Integer, default=0)
	remarks = sa.Column(sa.String, default="")
	salesid = sa.Column(sa.String, default="")
	segment = sa.Column(sa.Integer, default=0)
	source = sa.Column(sa.Integer, default=0)
	trainer = sa.Column(ARRAY(sa.Integer),default=[0,0,0,0,0,0,0,0,0])
	user_init = sa.Column(sa.String, default="")
	user_init1 = sa.Column(sa.String, default="")
	_recid = sa.Column(sa.Integer, primary_key=True)
	def __init__(self, *args, **kwargs):
		kwargs.setdefault('agreenum', "")
		kwargs.setdefault('billcycle', 0)
		kwargs.setdefault('billgastnr', 0)
		kwargs.setdefault('char1', "")
		kwargs.setdefault('char2', "")
		kwargs.setdefault('char3', "")
		kwargs.setdefault('checked_in', False)
		kwargs.setdefault('ci_time', 0)
		kwargs.setdefault('co_time', 0)
		kwargs.setdefault('codenum', "")
		kwargs.setdefault('created_date', None)
		kwargs.setdefault('date1', None)
		kwargs.setdefault('date2', None)
		kwargs.setdefault('date3', None)
		kwargs.setdefault('deci1', 0)
		kwargs.setdefault('deci2', 0)
		kwargs.setdefault('deci3', 0)
		kwargs.setdefault('disc', 0)
		kwargs.setdefault('emergency_nm', "")
		kwargs.setdefault('emergency_ph', "")
		kwargs.setdefault('expired_date', None)
		kwargs.setdefault('freezeto', None)
		kwargs.setdefault('gastnr', 0)
		kwargs.setdefault('group_nm', "")
		kwargs.setdefault('homeclub', 0)
		kwargs.setdefault('income', 0)
		kwargs.setdefault('join_date', None)
		kwargs.setdefault('last_changed', None)
		kwargs.setdefault('last_renewed', None)
		kwargs.setdefault('last_update', None)
		kwargs.setdefault('last_visit', None)
		kwargs.setdefault('lastbill', None)
		kwargs.setdefault('load_by', "")
		kwargs.setdefault('lock_num', "")
		kwargs.setdefault('locker', 0)
		kwargs.setdefault('lockerdate', None)
		kwargs.setdefault('logi1', False)
		kwargs.setdefault('logi2', False)
		kwargs.setdefault('logi3', False)
		kwargs.setdefault('main_gastnr', 0)
		kwargs.setdefault('medicalnote', "")
		kwargs.setdefault('membertype', 0)
		kwargs.setdefault('memstatus', 0)
		kwargs.setdefault('nextbill', None)
		kwargs.setdefault('num1', 0)
		kwargs.setdefault('num2', 0)
		kwargs.setdefault('num3', 0)
		kwargs.setdefault('numfreeze', 1)
		kwargs.setdefault('paysched', 0)
		kwargs.setdefault('pict_file', "")
		kwargs.setdefault('relation', 0)
		kwargs.setdefault('remarks', "")
		kwargs.setdefault('salesid', "")
		kwargs.setdefault('segment', 0)
		kwargs.setdefault('source', 0)
		kwargs.setdefault('trainer', [0,0,0,0,0,0,0,0,0])
		kwargs.setdefault('user_init', "")
		kwargs.setdefault('user_init1', "")
		super(Cl_member, self).__init__(*args, **kwargs)
