#version: 1.0.0.3

from sqlalchemy.dialects.postgresql import ARRAY
import sqlalchemy as sa
from models.base import Base
from functions.additional_functions import get_current_date

class Crm_category(Base):
	__tablename__ = 'crm_category'

	activeflag = sa.Column(sa.Boolean, default=True)
	categ_nr = sa.Column(sa.Integer, default=0)
	categname = sa.Column(sa.String, default="")
	char1 = sa.Column(sa.String, default="")
	char2 = sa.Column(sa.String, default="")
	char3 = sa.Column(sa.String, default="")
	char4 = sa.Column(sa.String, default="")
	char5 = sa.Column(sa.String, default="")
	confirmflag = sa.Column(sa.Boolean, default=False)
	date1 = sa.Column(sa.Date, default=None)
	date2 = sa.Column(sa.Date, default=None)
	date3 = sa.Column(sa.Date, default=None)
	date4 = sa.Column(sa.Date, default=None)
	date5 = sa.Column(sa.Date, default=None)
	dept_nr = sa.Column(sa.Integer, default=0)
	event_nr = sa.Column(sa.Integer, default=0)
	hiddenflag = sa.Column(sa.Boolean, default=False)
	hno = sa.Column(sa.Integer, default=0)
	logi1 = sa.Column(sa.Boolean, default=False)
	logi2 = sa.Column(sa.Boolean, default=False)
	logi3 = sa.Column(sa.Boolean, default=False)
	logi4 = sa.Column(sa.Boolean, default=False)
	logi5 = sa.Column(sa.Boolean, default=False)
	number1 = sa.Column(sa.Integer, default=0)
	number2 = sa.Column(sa.Integer, default=0)
	number3 = sa.Column(sa.Integer, default=0)
	number4 = sa.Column(sa.Integer, default=0)
	number5 = sa.Column(sa.Integer, default=0)
	remarks = sa.Column(sa.String, default="")
	sentdate = sa.Column(sa.Date, default=None)
	sentflag = sa.Column(sa.Boolean, default=False)
	senttime = sa.Column(sa.Integer, default=0)
	statusflag = sa.Column(sa.Integer, default=0)
	warning = sa.Column(sa.String, default="")
	webconfirmflag = sa.Column(sa.Boolean, default=False)
	websentflag = sa.Column(sa.Boolean, default=False)
	webstatusflag = sa.Column(sa.Integer, default=0)
	_recid = sa.Column(sa.Integer, primary_key=True)
	def __init__(self, *args, **kwargs):
		kwargs.setdefault('activeflag', True)
		kwargs.setdefault('categ_nr', 0)
		kwargs.setdefault('categname', "")
		kwargs.setdefault('char1', "")
		kwargs.setdefault('char2', "")
		kwargs.setdefault('char3', "")
		kwargs.setdefault('char4', "")
		kwargs.setdefault('char5', "")
		kwargs.setdefault('confirmflag', False)
		kwargs.setdefault('date1', None)
		kwargs.setdefault('date2', None)
		kwargs.setdefault('date3', None)
		kwargs.setdefault('date4', None)
		kwargs.setdefault('date5', None)
		kwargs.setdefault('dept_nr', 0)
		kwargs.setdefault('event_nr', 0)
		kwargs.setdefault('hiddenflag', False)
		kwargs.setdefault('hno', 0)
		kwargs.setdefault('logi1', False)
		kwargs.setdefault('logi2', False)
		kwargs.setdefault('logi3', False)
		kwargs.setdefault('logi4', False)
		kwargs.setdefault('logi5', False)
		kwargs.setdefault('number1', 0)
		kwargs.setdefault('number2', 0)
		kwargs.setdefault('number3', 0)
		kwargs.setdefault('number4', 0)
		kwargs.setdefault('number5', 0)
		kwargs.setdefault('remarks', "")
		kwargs.setdefault('sentdate', None)
		kwargs.setdefault('sentflag', False)
		kwargs.setdefault('senttime', 0)
		kwargs.setdefault('statusflag', 0)
		kwargs.setdefault('warning', "")
		kwargs.setdefault('webconfirmflag', False)
		kwargs.setdefault('websentflag', False)
		kwargs.setdefault('webstatusflag', 0)
		super(Crm_category, self).__init__(*args, **kwargs)
