#version: 1.0.0.3

from sqlalchemy.dialects.postgresql import ARRAY
import sqlalchemy as sa
from models.base import Base
from functions.additional_functions import get_current_date

class Crm_template(Base):
	__tablename__ = 'crm_template'

	char1 = sa.Column(sa.String, default="")
	char2 = sa.Column(sa.String, default="")
	char3 = sa.Column(sa.String, default="")
	char4 = sa.Column(sa.String, default="")
	char5 = sa.Column(sa.String, default="")
	confirmflag = sa.Column(sa.Boolean, default=False)
	date1 = sa.Column(sa.Date, default=None)
	date2 = sa.Column(sa.Date, default=None)
	date3 = sa.Column(sa.Date, default=None)
	date4 = sa.Column(sa.Date, default=None)
	date5 = sa.Column(sa.Date, default=None)
	deci1 = sa.Column(sa.Numeric, default=0)
	deci2 = sa.Column(sa.Numeric, default=0)
	deci3 = sa.Column(sa.Numeric, default=0)
	deci4 = sa.Column(sa.Numeric, default=0)
	deci5 = sa.Column(sa.Numeric, default=0)
	hno = sa.Column(sa.Integer, default=0)
	idtemplate = sa.Column(sa.Integer, default=0)
	int1 = sa.Column(sa.Integer, default=0)
	int2 = sa.Column(sa.Integer, default=0)
	int3 = sa.Column(sa.Integer, default=0)
	int4 = sa.Column(sa.Integer, default=0)
	int5 = sa.Column(sa.Integer, default=0)
	language_nr = sa.Column(sa.Integer, default=0)
	logi1 = sa.Column(sa.Boolean, default=False)
	logi2 = sa.Column(sa.Boolean, default=False)
	logi3 = sa.Column(sa.Boolean, default=False)
	logi4 = sa.Column(sa.Boolean, default=False)
	logi5 = sa.Column(sa.Boolean, default=False)
	sentdate = sa.Column(sa.Date, default=None)
	sentflag = sa.Column(sa.Boolean, default=False)
	senttime = sa.Column(sa.Integer, default=0)
	statusflag = sa.Column(sa.Integer, default=0)
	taghtml1 = sa.Column(sa.String, default="")
	taghtml1_1 = sa.Column(sa.String, default="")
	taghtml1_2 = sa.Column(sa.String, default="")
	taghtml1_3 = sa.Column(sa.String, default="")
	taghtml1_4 = sa.Column(sa.String, default="")
	templatename = sa.Column(sa.String, default="")
	templatetype = sa.Column(sa.Integer, default=0)
	webconfirmflag = sa.Column(sa.Boolean, default=False)
	websentflag = sa.Column(sa.Boolean, default=False)
	webstatusflag = sa.Column(sa.Integer, default=0)
	_recid = sa.Column(sa.Integer, primary_key=True)
	def __init__(self, *args, **kwargs):
		kwargs.setdefault('char1', "")
		kwargs.setdefault('char2', "")
		kwargs.setdefault('char3', "")
		kwargs.setdefault('char4', "")
		kwargs.setdefault('char5', "")
		kwargs.setdefault('confirmflag', False)
		kwargs.setdefault('date1', None)
		kwargs.setdefault('date2', None)
		kwargs.setdefault('date3', None)
		kwargs.setdefault('date4', None)
		kwargs.setdefault('date5', None)
		kwargs.setdefault('deci1', 0)
		kwargs.setdefault('deci2', 0)
		kwargs.setdefault('deci3', 0)
		kwargs.setdefault('deci4', 0)
		kwargs.setdefault('deci5', 0)
		kwargs.setdefault('hno', 0)
		kwargs.setdefault('idtemplate', 0)
		kwargs.setdefault('int1', 0)
		kwargs.setdefault('int2', 0)
		kwargs.setdefault('int3', 0)
		kwargs.setdefault('int4', 0)
		kwargs.setdefault('int5', 0)
		kwargs.setdefault('language_nr', 0)
		kwargs.setdefault('logi1', False)
		kwargs.setdefault('logi2', False)
		kwargs.setdefault('logi3', False)
		kwargs.setdefault('logi4', False)
		kwargs.setdefault('logi5', False)
		kwargs.setdefault('sentdate', None)
		kwargs.setdefault('sentflag', False)
		kwargs.setdefault('senttime', 0)
		kwargs.setdefault('statusflag', 0)
		kwargs.setdefault('taghtml1', "")
		kwargs.setdefault('taghtml1_1', "")
		kwargs.setdefault('taghtml1_2', "")
		kwargs.setdefault('taghtml1_3', "")
		kwargs.setdefault('taghtml1_4', "")
		kwargs.setdefault('templatename', "")
		kwargs.setdefault('templatetype', 0)
		kwargs.setdefault('webconfirmflag', False)
		kwargs.setdefault('websentflag', False)
		kwargs.setdefault('webstatusflag', 0)
		super(Crm_template, self).__init__(*args, **kwargs)
