#version: 1.0.0.3

from sqlalchemy.dialects.postgresql import ARRAY
import sqlalchemy as sa
from models.base import Base
from functions.additional_functions import get_current_date

class Crm_question(Base):
	__tablename__ = 'crm_question'

	answtype = sa.Column(sa.String, default="")
	boldflag = sa.Column(sa.Boolean, default=False)
	categ_nr = sa.Column(sa.Integer, default=0)
	char1 = sa.Column(sa.String, default="")
	char2 = sa.Column(sa.String, default="")
	char3 = sa.Column(sa.String, default="")
	char4 = sa.Column(sa.String, default="")
	char5 = sa.Column(sa.String, default="")
	confirmflag = sa.Column(sa.Boolean, default=False)
	date1 = sa.Column(sa.Date, default=None)
	date2 = sa.Column(sa.Date, default=None)
	date3 = sa.Column(sa.Date, default=None)
	date4 = sa.Column(sa.Date, default=None)
	date5 = sa.Column(sa.Date, default=None)
	dept_nr = sa.Column(sa.Integer, default=0)
	event_nr = sa.Column(sa.Integer, default=0)
	hno = sa.Column(sa.Integer, default=0)
	idquestion = sa.Column(sa.Integer, default=0)
	linenum = sa.Column(sa.Integer, default=0)
	linenum1 = sa.Column(sa.Integer, default=0)
	link = sa.Column(sa.String, default="")
	linkexist = sa.Column(sa.Boolean, default=False)
	linkqst = sa.Column(sa.String, default="")
	logi1 = sa.Column(sa.Boolean, default=False)
	logi2 = sa.Column(sa.Boolean, default=False)
	logi3 = sa.Column(sa.Boolean, default=False)
	logi4 = sa.Column(sa.Boolean, default=False)
	logi5 = sa.Column(sa.Boolean, default=False)
	number1 = sa.Column(sa.Integer, default=0)
	number2 = sa.Column(sa.Integer, default=0)
	number3 = sa.Column(sa.Integer, default=0)
	number4 = sa.Column(sa.Integer, default=0)
	number5 = sa.Column(sa.Integer, default=0)
	pageflag = sa.Column(sa.Boolean, default=False)
	pagenum = sa.Column(sa.Integer, default=0)
	pagenum1 = sa.Column(sa.Integer, default=0)
	qst = sa.Column(sa.String, default="")
	qst_nr = sa.Column(sa.Integer, default=0)
	qst2 = sa.Column(sa.String, default="")
	qst3 = sa.Column(sa.String, default="")
	qsttype = sa.Column(sa.String, default="")
	remarkflag = sa.Column(sa.Integer, default=0)
	remarks = sa.Column(sa.String, default="")
	rownum = sa.Column(sa.Integer, default=0)
	rownum1 = sa.Column(sa.Integer, default=0)
	sametype = sa.Column(sa.Boolean, default=False)
	score = sa.Column(sa.Integer, default=1)
	scoreansw = sa.Column(sa.String, default="")
	scoreansw2 = sa.Column(sa.String, default="")
	scoreansw3 = sa.Column(sa.String, default="")
	scoreflag = sa.Column(sa.Integer, default=0)
	sentdate = sa.Column(sa.Date, default=None)
	sentflag = sa.Column(sa.Boolean, default=False)
	senttime = sa.Column(sa.Integer, default=0)
	showflag = sa.Column(sa.Boolean, default=False)
	statusflag = sa.Column(sa.Integer, default=0)
	text_plus = sa.Column(sa.String, default="")
	validation = sa.Column(sa.String, default="")
	webconfirmflag = sa.Column(sa.Boolean, default=False)
	websentflag = sa.Column(sa.Boolean, default=False)
	webstatusflag = sa.Column(sa.Integer, default=0)
	widgetnum1 = sa.Column(sa.Integer, default=0)
	_recid = sa.Column(sa.Integer, primary_key=True)
	def __init__(self, *args, **kwargs):
		kwargs.setdefault('answtype', "")
		kwargs.setdefault('boldflag', False)
		kwargs.setdefault('categ_nr', 0)
		kwargs.setdefault('char1', "")
		kwargs.setdefault('char2', "")
		kwargs.setdefault('char3', "")
		kwargs.setdefault('char4', "")
		kwargs.setdefault('char5', "")
		kwargs.setdefault('confirmflag', False)
		kwargs.setdefault('date1', None)
		kwargs.setdefault('date2', None)
		kwargs.setdefault('date3', None)
		kwargs.setdefault('date4', None)
		kwargs.setdefault('date5', None)
		kwargs.setdefault('dept_nr', 0)
		kwargs.setdefault('event_nr', 0)
		kwargs.setdefault('hno', 0)
		kwargs.setdefault('idquestion', 0)
		kwargs.setdefault('linenum', 0)
		kwargs.setdefault('linenum1', 0)
		kwargs.setdefault('link', "")
		kwargs.setdefault('linkexist', False)
		kwargs.setdefault('linkqst', "")
		kwargs.setdefault('logi1', False)
		kwargs.setdefault('logi2', False)
		kwargs.setdefault('logi3', False)
		kwargs.setdefault('logi4', False)
		kwargs.setdefault('logi5', False)
		kwargs.setdefault('number1', 0)
		kwargs.setdefault('number2', 0)
		kwargs.setdefault('number3', 0)
		kwargs.setdefault('number4', 0)
		kwargs.setdefault('number5', 0)
		kwargs.setdefault('pageflag', False)
		kwargs.setdefault('pagenum', 0)
		kwargs.setdefault('pagenum1', 0)
		kwargs.setdefault('qst', "")
		kwargs.setdefault('qst_nr', 0)
		kwargs.setdefault('qst2', "")
		kwargs.setdefault('qst3', "")
		kwargs.setdefault('qsttype', "")
		kwargs.setdefault('remarkflag', 0)
		kwargs.setdefault('remarks', "")
		kwargs.setdefault('rownum', 0)
		kwargs.setdefault('rownum1', 0)
		kwargs.setdefault('sametype', False)
		kwargs.setdefault('score', 1)
		kwargs.setdefault('scoreansw', "")
		kwargs.setdefault('scoreansw2', "")
		kwargs.setdefault('scoreansw3', "")
		kwargs.setdefault('scoreflag', 0)
		kwargs.setdefault('sentdate', None)
		kwargs.setdefault('sentflag', False)
		kwargs.setdefault('senttime', 0)
		kwargs.setdefault('showflag', False)
		kwargs.setdefault('statusflag', 0)
		kwargs.setdefault('text_plus', "")
		kwargs.setdefault('validation', "")
		kwargs.setdefault('webconfirmflag', False)
		kwargs.setdefault('websentflag', False)
		kwargs.setdefault('webstatusflag', 0)
		kwargs.setdefault('widgetnum1', 0)
		super(Crm_question, self).__init__(*args, **kwargs)
