#version: 1.0.0.3

from sqlalchemy.dialects.postgresql import ARRAY
import sqlalchemy as sa
from models.base import Base
from functions.additional_functions import get_current_date

class Crm_event(Base):
	__tablename__ = 'crm_event'

	activeflag = sa.Column(sa.Boolean, default=True)
	btn_back = sa.Column(sa.String, default="")
	btn_close = sa.Column(sa.String, default="")
	btn_finish = sa.Column(sa.String, default="")
	btn_next = sa.Column(sa.String, default="")
	char1 = sa.Column(sa.String, default="")
	char2 = sa.Column(sa.String, default="")
	char3 = sa.Column(sa.String, default="")
	confirmflag = sa.Column(sa.Boolean, default=False)
	date1 = sa.Column(sa.Date, default=None)
	date2 = sa.Column(sa.Date, default=None)
	date3 = sa.Column(sa.Date, default=None)
	dept_nr = sa.Column(sa.Integer, default=0)
	ename = sa.Column(sa.String, default="")
	event_nr = sa.Column(sa.Integer, default=0)
	finishlabel = sa.Column(sa.String, default="")
	frdate = sa.Column(sa.Date, default=None)
	greetingtemplate = sa.Column(sa.Integer, default=0)
	hno = sa.Column(sa.Integer, default=0)
	linktemplate = sa.Column(sa.Integer, default=0)
	number1 = sa.Column(sa.Integer, default=0)
	number2 = sa.Column(sa.Integer, default=0)
	number3 = sa.Column(sa.Integer, default=0)
	picturehotel = sa.Column(sa.String, default="")
	remarks = sa.Column(sa.String, default="")
	score = sa.Column(sa.String, default="")
	sentdate = sa.Column(sa.Date, default=None)
	sentflag = sa.Column(sa.Boolean, default=False)
	senttime = sa.Column(sa.Integer, default=0)
	statusflag = sa.Column(sa.Integer, default=0)
	todate = sa.Column(sa.Date, default=None)
	txt_finish = sa.Column(sa.String, default="")
	txt_start = sa.Column(sa.String, default="")
	webconfirmflag = sa.Column(sa.Boolean, default=False)
	websentflag = sa.Column(sa.Boolean, default=False)
	webstatusflag = sa.Column(sa.Integer, default=0)
	_recid = sa.Column(sa.Integer, primary_key=True)
	def __init__(self, *args, **kwargs):
		kwargs.setdefault('activeflag', True)
		kwargs.setdefault('btn_back', "")
		kwargs.setdefault('btn_close', "")
		kwargs.setdefault('btn_finish', "")
		kwargs.setdefault('btn_next', "")
		kwargs.setdefault('char1', "")
		kwargs.setdefault('char2', "")
		kwargs.setdefault('char3', "")
		kwargs.setdefault('confirmflag', False)
		kwargs.setdefault('date1', None)
		kwargs.setdefault('date2', None)
		kwargs.setdefault('date3', None)
		kwargs.setdefault('dept_nr', 0)
		kwargs.setdefault('ename', "")
		kwargs.setdefault('event_nr', 0)
		kwargs.setdefault('finishlabel', "")
		kwargs.setdefault('frdate', None)
		kwargs.setdefault('greetingtemplate', 0)
		kwargs.setdefault('hno', 0)
		kwargs.setdefault('linktemplate', 0)
		kwargs.setdefault('number1', 0)
		kwargs.setdefault('number2', 0)
		kwargs.setdefault('number3', 0)
		kwargs.setdefault('picturehotel', "")
		kwargs.setdefault('remarks', "")
		kwargs.setdefault('score', "")
		kwargs.setdefault('sentdate', None)
		kwargs.setdefault('sentflag', False)
		kwargs.setdefault('senttime', 0)
		kwargs.setdefault('statusflag', 0)
		kwargs.setdefault('todate', None)
		kwargs.setdefault('txt_finish', "")
		kwargs.setdefault('txt_start', "")
		kwargs.setdefault('webconfirmflag', False)
		kwargs.setdefault('websentflag', False)
		kwargs.setdefault('webstatusflag', 0)
		super(Crm_event, self).__init__(*args, **kwargs)
