#version: 1.0.0.3

from sqlalchemy.dialects.postgresql import ARRAY
import sqlalchemy as sa
from models.base import Base
from functions.additional_functions import get_current_date

class Crm_feedhdr(Base):
	__tablename__ = 'crm_feedhdr'

	activeflag = sa.Column(sa.Boolean, default=True)
	age = sa.Column(sa.Integer, default=0)
	char1 = sa.Column(sa.String, default="")
	char2 = sa.Column(sa.String, default="")
	char3 = sa.Column(sa.String, default="")
	confirmflag = sa.Column(sa.Boolean, default=False)
	createddate = sa.Column(sa.Date, default=get_current_date())
	createdtime = sa.Column(sa.Integer, default=0)
	date1 = sa.Column(sa.Date, default=None)
	date2 = sa.Column(sa.Date, default=None)
	date3 = sa.Column(sa.Date, default=None)
	datum = sa.Column(sa.Date, default=None)
	deci1 = sa.Column(sa.Numeric, default=0)
	deci2 = sa.Column(sa.Numeric, default=0)
	deci3 = sa.Column(sa.Numeric, default=0)
	dept_nr = sa.Column(sa.Integer, default=0)
	emailaddress = sa.Column(sa.String, default="")
	event_nr = sa.Column(sa.Integer, default=0)
	finishflag = sa.Column(sa.Boolean, default=False)
	gastnr = sa.Column(sa.Integer, default=0)
	gender = sa.Column(sa.String, default="M")
	guestname = sa.Column(sa.String, default="")
	hno = sa.Column(sa.Integer, default=0)
	lastpage = sa.Column(sa.Integer, default=0)
	logi1 = sa.Column(sa.Boolean, default=False)
	logi2 = sa.Column(sa.Boolean, default=False)
	logi3 = sa.Column(sa.Boolean, default=False)
	number1 = sa.Column(sa.Integer, default=0)
	number2 = sa.Column(sa.Integer, default=0)
	number3 = sa.Column(sa.Integer, default=0)
	reslinnr = sa.Column(sa.Integer, default=0)
	resnr = sa.Column(sa.Integer, default=0)
	sentdate = sa.Column(sa.Date, default=None)
	sentflag = sa.Column(sa.Boolean, default=False)
	sentthxflag = sa.Column(sa.Boolean, default=False)
	senttime = sa.Column(sa.Integer, default=0)
	statusflag = sa.Column(sa.Integer, default=0)
	trans_nr = sa.Column(sa.Integer, default=0)
	userinit = sa.Column(sa.String, default="")
	webconfirmflag = sa.Column(sa.Boolean, default=False)
	websentflag = sa.Column(sa.Boolean, default=False)
	webstatusflag = sa.Column(sa.Integer, default=0)
	webtransnr = sa.Column(sa.Integer, default=0)
	zinr = sa.Column(sa.String, default="")
	_recid = sa.Column(sa.Integer, primary_key=True)
	def __init__(self, *args, **kwargs):
		kwargs.setdefault('activeflag', True)
		kwargs.setdefault('age', 0)
		kwargs.setdefault('char1', "")
		kwargs.setdefault('char2', "")
		kwargs.setdefault('char3', "")
		kwargs.setdefault('confirmflag', False)
		kwargs.setdefault('createddate', get_current_date())
		kwargs.setdefault('createdtime', 0)
		kwargs.setdefault('date1', None)
		kwargs.setdefault('date2', None)
		kwargs.setdefault('date3', None)
		kwargs.setdefault('datum', None)
		kwargs.setdefault('deci1', 0)
		kwargs.setdefault('deci2', 0)
		kwargs.setdefault('deci3', 0)
		kwargs.setdefault('dept_nr', 0)
		kwargs.setdefault('emailaddress', "")
		kwargs.setdefault('event_nr', 0)
		kwargs.setdefault('finishflag', False)
		kwargs.setdefault('gastnr', 0)
		kwargs.setdefault('gender', "M")
		kwargs.setdefault('guestname', "")
		kwargs.setdefault('hno', 0)
		kwargs.setdefault('lastpage', 0)
		kwargs.setdefault('logi1', False)
		kwargs.setdefault('logi2', False)
		kwargs.setdefault('logi3', False)
		kwargs.setdefault('number1', 0)
		kwargs.setdefault('number2', 0)
		kwargs.setdefault('number3', 0)
		kwargs.setdefault('reslinnr', 0)
		kwargs.setdefault('resnr', 0)
		kwargs.setdefault('sentdate', None)
		kwargs.setdefault('sentflag', False)
		kwargs.setdefault('sentthxflag', False)
		kwargs.setdefault('senttime', 0)
		kwargs.setdefault('statusflag', 0)
		kwargs.setdefault('trans_nr', 0)
		kwargs.setdefault('userinit', "")
		kwargs.setdefault('webconfirmflag', False)
		kwargs.setdefault('websentflag', False)
		kwargs.setdefault('webstatusflag', 0)
		kwargs.setdefault('webtransnr', 0)
		kwargs.setdefault('zinr', "")
		super(Crm_feedhdr, self).__init__(*args, **kwargs)
