#version: 1.0.0.3

from sqlalchemy.dialects.postgresql import ARRAY
import sqlalchemy as sa
from models.base import Base
from functions.additional_functions import get_current_date

class Eg_maintain(Base):
	__tablename__ = 'eg_maintain'

	cancel_by = sa.Column(sa.String, default="")
	cancel_date = sa.Column(sa.Date, default=None)
	cancel_time = sa.Column(sa.Integer, default=0)
	category = sa.Column(sa.Integer, default=0)
	char1 = sa.Column(sa.String, default="")
	char2 = sa.Column(sa.String, default="")
	char3 = sa.Column(sa.String, default="")
	comments = sa.Column(sa.String, default="")
	created_by = sa.Column(sa.String, default="")
	created_date = sa.Column(sa.Date, default=None)
	date1 = sa.Column(sa.Date, default=None)
	date2 = sa.Column(sa.Date, default=None)
	deci1 = sa.Column(sa.Numeric, default=0)
	deci2 = sa.Column(sa.Numeric, default=0)
	delete_flag = sa.Column(sa.Boolean, default=False)
	donedate = sa.Column(sa.Date, default=None)
	estworkdate = sa.Column(sa.Date, default=None)
	location = sa.Column(sa.Integer, default=0)
	logi1 = sa.Column(sa.Boolean, default=False)
	logi2 = sa.Column(sa.Boolean, default=False)
	maintainnr = sa.Column(sa.Integer, default=0)
	maintask = sa.Column(sa.Integer, default=0)
	memo = sa.Column(sa.String, default="")
	month = sa.Column(sa.Integer, default=0)
	number1 = sa.Column(sa.Integer, default=0)
	number2 = sa.Column(sa.Integer, default=0)
	number3 = sa.Column(sa.Integer, default=0)
	pic = sa.Column(sa.Integer, default=0)
	propertynr = sa.Column(sa.Integer, default=0)
	smsflag = sa.Column(sa.Boolean, default=False)
	type = sa.Column(sa.Integer, default=0)
	typework = sa.Column(sa.Integer, default=0)
	week = sa.Column(sa.Integer, default=0)
	workdate = sa.Column(sa.Date, default=None)
	year = sa.Column(sa.Integer, default=0)
	zinr = sa.Column(sa.String, default="")
	_recid = sa.Column(sa.Integer, primary_key=True)
	def __init__(self, *args, **kwargs):
		kwargs.setdefault('cancel_by', "")
		kwargs.setdefault('cancel_date', None)
		kwargs.setdefault('cancel_time', 0)
		kwargs.setdefault('category', 0)
		kwargs.setdefault('char1', "")
		kwargs.setdefault('char2', "")
		kwargs.setdefault('char3', "")
		kwargs.setdefault('comments', "")
		kwargs.setdefault('created_by', "")
		kwargs.setdefault('created_date', None)
		kwargs.setdefault('date1', None)
		kwargs.setdefault('date2', None)
		kwargs.setdefault('deci1', 0)
		kwargs.setdefault('deci2', 0)
		kwargs.setdefault('delete_flag', False)
		kwargs.setdefault('donedate', None)
		kwargs.setdefault('estworkdate', None)
		kwargs.setdefault('location', 0)
		kwargs.setdefault('logi1', False)
		kwargs.setdefault('logi2', False)
		kwargs.setdefault('maintainnr', 0)
		kwargs.setdefault('maintask', 0)
		kwargs.setdefault('memo', "")
		kwargs.setdefault('month', 0)
		kwargs.setdefault('number1', 0)
		kwargs.setdefault('number2', 0)
		kwargs.setdefault('number3', 0)
		kwargs.setdefault('pic', 0)
		kwargs.setdefault('propertynr', 0)
		kwargs.setdefault('smsflag', False)
		kwargs.setdefault('type', 0)
		kwargs.setdefault('typework', 0)
		kwargs.setdefault('week', 0)
		kwargs.setdefault('workdate', None)
		kwargs.setdefault('year', 0)
		kwargs.setdefault('zinr', "")
		super(Eg_maintain, self).__init__(*args, **kwargs)
