#version: 1.0.0.3

from sqlalchemy.dialects.postgresql import ARRAY
import sqlalchemy as sa
from models.base import Base
from functions.additional_functions import get_current_date

class Eg_reqstat(Base):
	__tablename__ = 'eg_reqstat'

	category = sa.Column(sa.Integer, default=0)
	char1 = sa.Column(sa.String, default="")
	char2 = sa.Column(sa.String, default="")
	char3 = sa.Column(sa.String, default="")
	closedate = sa.Column(sa.Date, default=None)
	closetime = sa.Column(sa.Integer, default=0)
	date1 = sa.Column(sa.Date, default=None)
	date2 = sa.Column(sa.Date, default=None)
	deci1 = sa.Column(sa.Numeric, default=0)
	deci2 = sa.Column(sa.Numeric, default=0)
	deptnum = sa.Column(sa.Integer, default=0)
	donedate = sa.Column(sa.Date, default=None)
	donetime = sa.Column(sa.Integer, default=0)
	estfinishdate = sa.Column(sa.Date, default=None)
	estfinishtime = sa.Column(sa.Integer, default=0)
	location = sa.Column(sa.Integer, default=0)
	logi1 = sa.Column(sa.Boolean, default=False)
	logi2 = sa.Column(sa.Boolean, default=False)
	number1 = sa.Column(sa.Integer, default=0)
	number2 = sa.Column(sa.Integer, default=0)
	number3 = sa.Column(sa.Integer, default=0)
	object = sa.Column(sa.Integer, default=0)
	objectitem = sa.Column(sa.Integer, default=0)
	objecttask = sa.Column(sa.String, default="")
	opendate = sa.Column(sa.Date, default=None)
	opentime = sa.Column(sa.Integer, default=0)
	pic = sa.Column(sa.Integer, default=0)
	processdate = sa.Column(sa.Date, default=None)
	processtime = sa.Column(sa.Integer, default=0)
	reqfrom = sa.Column(sa.Integer, default=0)
	reqstat = sa.Column(sa.Integer, default=0)
	urgency = sa.Column(sa.Integer, default=0)
	zinr = sa.Column(sa.String, default="")
	_recid = sa.Column(sa.Integer, primary_key=True)
	def __init__(self, *args, **kwargs):
		kwargs.setdefault('category', 0)
		kwargs.setdefault('char1', "")
		kwargs.setdefault('char2', "")
		kwargs.setdefault('char3', "")
		kwargs.setdefault('closedate', None)
		kwargs.setdefault('closetime', 0)
		kwargs.setdefault('date1', None)
		kwargs.setdefault('date2', None)
		kwargs.setdefault('deci1', 0)
		kwargs.setdefault('deci2', 0)
		kwargs.setdefault('deptnum', 0)
		kwargs.setdefault('donedate', None)
		kwargs.setdefault('donetime', 0)
		kwargs.setdefault('estfinishdate', None)
		kwargs.setdefault('estfinishtime', 0)
		kwargs.setdefault('location', 0)
		kwargs.setdefault('logi1', False)
		kwargs.setdefault('logi2', False)
		kwargs.setdefault('number1', 0)
		kwargs.setdefault('number2', 0)
		kwargs.setdefault('number3', 0)
		kwargs.setdefault('object', 0)
		kwargs.setdefault('objectitem', 0)
		kwargs.setdefault('objecttask', "")
		kwargs.setdefault('opendate', None)
		kwargs.setdefault('opentime', 0)
		kwargs.setdefault('pic', 0)
		kwargs.setdefault('processdate', None)
		kwargs.setdefault('processtime', 0)
		kwargs.setdefault('reqfrom', 0)
		kwargs.setdefault('reqstat', 0)
		kwargs.setdefault('urgency', 0)
		kwargs.setdefault('zinr', "")
		super(Eg_reqstat, self).__init__(*args, **kwargs)
