#version: 1.0.0.3

from sqlalchemy.dialects.postgresql import ARRAY
import sqlalchemy as sa
from models.base import Base
from functions.additional_functions import get_current_date

class Eg_vperform(Base):
	__tablename__ = 'eg_vperform'

	bezeich = sa.Column(sa.String, default="")
	char1 = sa.Column(sa.String, default="")
	char2 = sa.Column(sa.String, default="")
	char3 = sa.Column(sa.String, default="")
	created_by = sa.Column(sa.String, default="")
	created_date = sa.Column(sa.Date, default=None)
	created_time = sa.Column(sa.Integer, default=0)
	date1 = sa.Column(sa.Date, default=None)
	date2 = sa.Column(sa.Date, default=None)
	deci1 = sa.Column(sa.Numeric, default=0)
	deci2 = sa.Column(sa.Numeric, default=0)
	documentno = sa.Column(sa.String, default="")
	estfinishdate = sa.Column(sa.Date, default=None)
	finishdate = sa.Column(sa.Date, default=None)
	logi1 = sa.Column(sa.Boolean, default=False)
	logi2 = sa.Column(sa.Boolean, default=False)
	number1 = sa.Column(sa.Integer, default=0)
	number2 = sa.Column(sa.Integer, default=0)
	number3 = sa.Column(sa.Integer, default=0)
	perform_nr = sa.Column(sa.String, default="")
	pic = sa.Column(sa.String, default="")
	price = sa.Column(sa.Numeric, default=0)
	reqnr = sa.Column(sa.Integer, default=0)
	startdate = sa.Column(sa.Date, default=None)
	vendor_nr = sa.Column(sa.Integer, default=0)
	_recid = sa.Column(sa.Integer, primary_key=True)
	def __init__(self, *args, **kwargs):
		kwargs.setdefault('bezeich', "")
		kwargs.setdefault('char1', "")
		kwargs.setdefault('char2', "")
		kwargs.setdefault('char3', "")
		kwargs.setdefault('created_by', "")
		kwargs.setdefault('created_date', None)
		kwargs.setdefault('created_time', 0)
		kwargs.setdefault('date1', None)
		kwargs.setdefault('date2', None)
		kwargs.setdefault('deci1', 0)
		kwargs.setdefault('deci2', 0)
		kwargs.setdefault('documentno', "")
		kwargs.setdefault('estfinishdate', None)
		kwargs.setdefault('finishdate', None)
		kwargs.setdefault('logi1', False)
		kwargs.setdefault('logi2', False)
		kwargs.setdefault('number1', 0)
		kwargs.setdefault('number2', 0)
		kwargs.setdefault('number3', 0)
		kwargs.setdefault('perform_nr', "")
		kwargs.setdefault('pic', "")
		kwargs.setdefault('price', 0)
		kwargs.setdefault('reqnr', 0)
		kwargs.setdefault('startdate', None)
		kwargs.setdefault('vendor_nr', 0)
		super(Eg_vperform, self).__init__(*args, **kwargs)
