from sqlalchemy.dialects.postgresql import ARRAY
import sqlalchemy as sa
from models.base import Base
from functions.additional_functions import get_current_date

class Gc_pi(Base):
	__tablename__ = 'gc_pi'

	add_amt_flag = sa.Column(sa.Boolean, default=False)
	amount_array = sa.Column(ARRAY(sa.Numeric),default=[0,0,0,0,0,0,0,0,0,0])
	approved1 = sa.Column(ARRAY(sa.Boolean),default=[False,False,False])
	approved2 = sa.Column(ARRAY(sa.Boolean),default=[False,False,False])
	bankname = sa.Column(sa.String, default="")
	bemerk = sa.Column(sa.String, default="")
	betrag = sa.Column(sa.Numeric, default=0)
	bez_array = sa.Column(ARRAY(sa.String),default=["","","","","","","","","",""])
	canceldate = sa.Column(sa.Date, default=None)
	cancelid = sa.Column(sa.String, default="")
	cancelzeit = sa.Column(sa.Integer, default=0)
	chequeno = sa.Column(sa.String, default="")
	cid = sa.Column(sa.String, default="")
	created = sa.Column(sa.Date, default=lambda: get_current_date())
	credit_fibu = sa.Column(sa.String, default="")
	datum = sa.Column(sa.Date, default=lambda: get_current_date())
	datum2 = sa.Column(sa.Date, default=None)
	debit_fibu = sa.Column(sa.String, default="")
	deptno = sa.Column(sa.Integer, default=0)
	docu_nr = sa.Column(sa.String, default="")
	docu_nr2 = sa.Column(sa.String, default="")
	duedate = sa.Column(sa.Date, default=None)
	mid = sa.Column(sa.String, default="")
	modified = sa.Column(sa.Date, default=None)
	pay_datum = sa.Column(sa.Date, default=None)
	pay_type = sa.Column(sa.Integer, default=1)
	pi_status = sa.Column(sa.Integer, default=0)
	pi_type = sa.Column(sa.Integer, default=0)
	postdate = sa.Column(sa.Date, default=None)
	printed1 = sa.Column(sa.Boolean, default=False)
	printed1a = sa.Column(sa.Boolean, default=False)
	printed2 = sa.Column(sa.Boolean, default=False)
	printed2a = sa.Column(sa.Boolean, default=False)
	rcvid = sa.Column(sa.String, default="")
	rcvname = sa.Column(sa.String, default="")
	res_char = sa.Column(ARRAY(sa.String),default=["","",""])
	res_deci = sa.Column(ARRAY(sa.Numeric),default=[0,0,0])
	res_int = sa.Column(ARRAY(sa.Integer),default=[0,0,0])
	res_logi = sa.Column(ARRAY(sa.Boolean),default=[False,False,False])
	return_fibu = sa.Column(sa.String, default="000000000000")
	returnamt = sa.Column(sa.Numeric, default=0)
	_recid = sa.Column(sa.Integer, primary_key=True)
