#version: 1.0.0.3

from sqlalchemy.dialects.postgresql import ARRAY
import sqlalchemy as sa
from models.base import Base
from functions.additional_functions import get_current_date

class Gc_pi(Base):
	__tablename__ = 'gc_pi'

	add_amt_flag = sa.Column(sa.Boolean, default=False)
	amount_array = sa.Column(ARRAY(sa.Numeric),default=[0,0,0,0,0,0,0,0,0,0])
	approved1 = sa.Column(ARRAY(sa.Boolean),default=[False,False,False])
	approved2 = sa.Column(ARRAY(sa.Boolean),default=[False,False,False])
	bankname = sa.Column(sa.String, default="")
	bemerk = sa.Column(sa.String, default="")
	betrag = sa.Column(sa.Numeric, default=0)
	bez_array = sa.Column(ARRAY(sa.String),default=["","","","","","","","","",""])
	canceldate = sa.Column(sa.Date, default=None)
	cancelid = sa.Column(sa.String, default="")
	cancelzeit = sa.Column(sa.Integer, default=0)
	chequeno = sa.Column(sa.String, default="")
	cid = sa.Column(sa.String, default="")
	created = sa.Column(sa.Date, default=get_current_date())
	credit_fibu = sa.Column(sa.String, default="")
	datum = sa.Column(sa.Date, default=get_current_date())
	datum2 = sa.Column(sa.Date, default=None)
	debit_fibu = sa.Column(sa.String, default="")
	deptno = sa.Column(sa.Integer, default=0)
	docu_nr = sa.Column(sa.String, default="")
	docu_nr2 = sa.Column(sa.String, default="")
	duedate = sa.Column(sa.Date, default=None)
	mid = sa.Column(sa.String, default="")
	modified = sa.Column(sa.Date, default=None)
	pay_datum = sa.Column(sa.Date, default=None)
	pay_type = sa.Column(sa.Integer, default=1)
	pi_status = sa.Column(sa.Integer, default=0)
	pi_type = sa.Column(sa.Integer, default=0)
	postdate = sa.Column(sa.Date, default=None)
	printed1 = sa.Column(sa.Boolean, default=False)
	printed1a = sa.Column(sa.Boolean, default=False)
	printed2 = sa.Column(sa.Boolean, default=False)
	printed2a = sa.Column(sa.Boolean, default=False)
	rcvid = sa.Column(sa.String, default="")
	rcvname = sa.Column(sa.String, default="")
	res_char = sa.Column(ARRAY(sa.String),default=["","",""])
	res_deci = sa.Column(ARRAY(sa.Numeric),default=[0,0,0])
	res_int = sa.Column(ARRAY(sa.Integer),default=[0,0,0])
	res_logi = sa.Column(ARRAY(sa.Boolean),default=[False,False,False])
	return_fibu = sa.Column(sa.String, default="000000000000")
	returnamt = sa.Column(sa.Numeric, default=0)
	_recid = sa.Column(sa.Integer, primary_key=True)
	def __init__(self, *args, **kwargs):
		kwargs.setdefault('add_amt_flag', False)
		kwargs.setdefault('amount_array', [0,0,0,0,0,0,0,0,0,0])
		kwargs.setdefault('approved1', [False,False,False])
		kwargs.setdefault('approved2', [False,False,False])
		kwargs.setdefault('bankname', "")
		kwargs.setdefault('bemerk', "")
		kwargs.setdefault('betrag', 0)
		kwargs.setdefault('bez_array', ["","","","","","","","","",""])
		kwargs.setdefault('canceldate', None)
		kwargs.setdefault('cancelid', "")
		kwargs.setdefault('cancelzeit', 0)
		kwargs.setdefault('chequeno', "")
		kwargs.setdefault('cid', "")
		kwargs.setdefault('created', get_current_date())
		kwargs.setdefault('credit_fibu', "")
		kwargs.setdefault('datum', get_current_date())
		kwargs.setdefault('datum2', None)
		kwargs.setdefault('debit_fibu', "")
		kwargs.setdefault('deptno', 0)
		kwargs.setdefault('docu_nr', "")
		kwargs.setdefault('docu_nr2', "")
		kwargs.setdefault('duedate', None)
		kwargs.setdefault('mid', "")
		kwargs.setdefault('modified', None)
		kwargs.setdefault('pay_datum', None)
		kwargs.setdefault('pay_type', 1)
		kwargs.setdefault('pi_status', 0)
		kwargs.setdefault('pi_type', 0)
		kwargs.setdefault('postdate', None)
		kwargs.setdefault('printed1', False)
		kwargs.setdefault('printed1a', False)
		kwargs.setdefault('printed2', False)
		kwargs.setdefault('printed2a', False)
		kwargs.setdefault('rcvid', "")
		kwargs.setdefault('rcvname', "")
		kwargs.setdefault('res_char', ["","",""])
		kwargs.setdefault('res_deci', [0,0,0])
		kwargs.setdefault('res_int', [0,0,0])
		kwargs.setdefault('res_logi', [False,False,False])
		kwargs.setdefault('return_fibu', "000000000000")
		kwargs.setdefault('returnamt', 0)
		super(Gc_pi, self).__init__(*args, **kwargs)
