#version: 1.0.0.3

from sqlalchemy.dialects.postgresql import ARRAY
import sqlalchemy as sa
from models.base import Base
from functions.additional_functions import get_current_date

class H_artikel(Base):
	__tablename__ = 'h_artikel'

	abbuchung = sa.Column(sa.Integer, default=0)
	activeflag = sa.Column(sa.Boolean, default=False)
	aenderwunsch = sa.Column(sa.Boolean, default=False)
	artart = sa.Column(sa.Integer, default=0)
	artnr = sa.Column(sa.Integer, default=0)
	artnrfront = sa.Column(sa.Integer, default=0)
	artnrlager = sa.Column(sa.Integer, default=0)
	artnrrezept = sa.Column(sa.Integer, default=0)
	autosaldo = sa.Column(sa.Boolean, default=False)
	betriebsnr = sa.Column(sa.Integer, default=0)
	bezaendern = sa.Column(sa.Boolean, default=False)
	bezeich = sa.Column(sa.String, default="")
	bondruckernr = sa.Column(ARRAY(sa.Integer),default=[0,0,0,0])
	departement = sa.Column(sa.Integer, default=0)
	e_gueltig = sa.Column(sa.Date, default=None)
	endkum = sa.Column(sa.Integer, default=0)
	epreis1 = sa.Column(sa.Numeric, default=0)
	epreis2 = sa.Column(sa.Numeric, default=0)
	gang = sa.Column(sa.Integer, default=0)
	lagernr = sa.Column(sa.Integer, default=0)
	mwst_code = sa.Column(sa.Integer, default=0)
	prozent = sa.Column(sa.Numeric, default=0)
	s_gueltig = sa.Column(sa.Date, default=None)
	service_code = sa.Column(sa.Integer, default=0)
	zwkum = sa.Column(sa.Integer, default=0)
	_recid = sa.Column(sa.Integer, primary_key=True)
	def __init__(self, *args, **kwargs):
		kwargs.setdefault('abbuchung', 0)
		kwargs.setdefault('activeflag', False)
		kwargs.setdefault('aenderwunsch', False)
		kwargs.setdefault('artart', 0)
		kwargs.setdefault('artnr', 0)
		kwargs.setdefault('artnrfront', 0)
		kwargs.setdefault('artnrlager', 0)
		kwargs.setdefault('artnrrezept', 0)
		kwargs.setdefault('autosaldo', False)
		kwargs.setdefault('betriebsnr', 0)
		kwargs.setdefault('bezaendern', False)
		kwargs.setdefault('bezeich', "")
		kwargs.setdefault('bondruckernr', [0,0,0,0])
		kwargs.setdefault('departement', 0)
		kwargs.setdefault('e_gueltig', None)
		kwargs.setdefault('endkum', 0)
		kwargs.setdefault('epreis1', 0)
		kwargs.setdefault('epreis2', 0)
		kwargs.setdefault('gang', 0)
		kwargs.setdefault('lagernr', 0)
		kwargs.setdefault('mwst_code', 0)
		kwargs.setdefault('prozent', 0)
		kwargs.setdefault('s_gueltig', None)
		kwargs.setdefault('service_code', 0)
		kwargs.setdefault('zwkum', 0)
		super(H_artikel, self).__init__(*args, **kwargs)
