from sqlalchemy.dialects.postgresql import ARRAY
import sqlalchemy as sa
from models.base import Base
from functions.additional_functions import get_current_date

class H_journal(Base):
	__tablename__ = 'h_journal'

	aendertext = sa.Column(sa.String, default="")
	ankauf = sa.Column(sa.Numeric, default=0)
	anzahl = sa.Column(sa.Integer, default=0)
	artart = sa.Column(sa.Integer, default=0)
	artnr = sa.Column(sa.Integer, default=0)
	artnrfront = sa.Column(sa.Integer, default=0)
	artnrlager = sa.Column(sa.Integer, default=0)
	artnrrezept = sa.Column(sa.Integer, default=0)
	betrag = sa.Column(sa.Numeric, default=0)
	betriebsnr = sa.Column(sa.Integer, default=0)
	bezeich = sa.Column(sa.String, default="")
	bill_datum = sa.Column(sa.Date, default=None)
	bon_nr = sa.Column(sa.Integer, default=0)
	bondruckernr = sa.Column(sa.Integer, default=0)
	buchflag = sa.Column(sa.Integer, default=0)
	departement = sa.Column(sa.Integer, default=0)
	endbon = sa.Column(sa.Integer, default=0)
	epreis = sa.Column(sa.Numeric, default=0)
	fremdwaehrng = sa.Column(sa.Numeric, default=0)
	gang = sa.Column(sa.Integer, default=0)
	kellner_nr = sa.Column(sa.Integer, default=0)
	lager_nr = sa.Column(sa.Integer, default=0)
	nachbuchen = sa.Column(sa.Boolean, default=False)
	prtflag = sa.Column(sa.Integer, default=0)
	rechnr = sa.Column(sa.Integer, default=0)
	schankbuch = sa.Column(sa.Integer, default=0)
	segmentcode = sa.Column(sa.Integer, default=0)
	service_code = sa.Column(sa.Integer, default=0)
	service_percent = sa.Column(sa.Numeric, default=0)
	steuer_percent = sa.Column(sa.Numeric, default=0)
	steuercode = sa.Column(sa.Integer, default=0)
	stornogrund = sa.Column(sa.String, default="")
	sysdate = sa.Column(sa.Date, default=lambda: get_current_date())
	tischnr = sa.Column(sa.Integer, default=0)
	trinkgeld = sa.Column(sa.Numeric, default=0)
	verkauf = sa.Column(sa.Numeric, default=0)
	wabkurz = sa.Column(sa.String, default="")
	waehrungcode = sa.Column(sa.Integer, default=0)
	waehrungsnr = sa.Column(sa.Integer, default=0)
	zeit = sa.Column(sa.Integer, default=0)
	zinr = sa.Column(sa.String, default="")
	_recid = sa.Column(sa.Integer, primary_key=True)
