#version: 1.0.0.3

from sqlalchemy.dialects.postgresql import ARRAY
import sqlalchemy as sa
from models.base import Base
from functions.additional_functions import get_current_date

class L_lieferant(Base):
	__tablename__ = 'l_lieferant'

	adresse1 = sa.Column(sa.String, default="")
	adresse2 = sa.Column(sa.String, default="")
	adresse3 = sa.Column(sa.String, default="")
	anrede1 = sa.Column(sa.String, default="")
	anredefirma = sa.Column(sa.String, default="")
	bank = sa.Column(sa.String, default="")
	betriebsnr = sa.Column(sa.Integer, default=0)
	blz = sa.Column(sa.String, default="")
	fax = sa.Column(sa.String, default="")
	firma = sa.Column(sa.String, default="")
	kontonr = sa.Column(sa.String, default="")
	land = sa.Column(sa.String, default="")
	lief_nr = sa.Column(sa.Integer, default=0)
	lieferdatum = sa.Column(sa.Date, default=None)
	namekontakt = sa.Column(sa.String, default="")
	notizen = sa.Column(ARRAY(sa.String),default=["","",""])
	plz = sa.Column(sa.String, default="")
	rabatt = sa.Column(sa.Numeric, default=0)
	segment1 = sa.Column(sa.Integer, default=0)
	skonto = sa.Column(sa.Numeric, default=0)
	telefon = sa.Column(sa.String, default="")
	telex = sa.Column(sa.String, default="")
	vorname1 = sa.Column(sa.String, default="")
	wohnort = sa.Column(sa.String, default="")
	z_code = sa.Column(sa.String, default="")
	ziel = sa.Column(sa.Integer, default=0)
	_recid = sa.Column(sa.Integer, primary_key=True)
	def __init__(self, *args, **kwargs):
		kwargs.setdefault('adresse1', "")
		kwargs.setdefault('adresse2', "")
		kwargs.setdefault('adresse3', "")
		kwargs.setdefault('anrede1', "")
		kwargs.setdefault('anredefirma', "")
		kwargs.setdefault('bank', "")
		kwargs.setdefault('betriebsnr', 0)
		kwargs.setdefault('blz', "")
		kwargs.setdefault('fax', "")
		kwargs.setdefault('firma', "")
		kwargs.setdefault('kontonr', "")
		kwargs.setdefault('land', "")
		kwargs.setdefault('lief_nr', 0)
		kwargs.setdefault('lieferdatum', None)
		kwargs.setdefault('namekontakt', "")
		kwargs.setdefault('notizen', ["","",""])
		kwargs.setdefault('plz', "")
		kwargs.setdefault('rabatt', 0)
		kwargs.setdefault('segment1', 0)
		kwargs.setdefault('skonto', 0)
		kwargs.setdefault('telefon', "")
		kwargs.setdefault('telex', "")
		kwargs.setdefault('vorname1', "")
		kwargs.setdefault('wohnort', "")
		kwargs.setdefault('z_code', "")
		kwargs.setdefault('ziel', 0)
		super(L_lieferant, self).__init__(*args, **kwargs)
