#version: 1.0.0.3

from sqlalchemy.dialects.postgresql import ARRAY
import sqlalchemy as sa
from models.base import Base
from functions.additional_functions import get_current_date

class Res_line(Base):
	__tablename__ = 'res_line'

	abreise = sa.Column(sa.Date, default=get_current_date())
	abreisezeit = sa.Column(sa.Integer, default=0)
	active_flag = sa.Column(sa.Integer, default=0)
	adrflag = sa.Column(sa.Boolean, default=False)
	ankunft = sa.Column(sa.Date, default=get_current_date())
	ankzeit = sa.Column(sa.Integer, default=0)
	anztage = sa.Column(sa.Integer, default=1)
	argt_typ = sa.Column(sa.Integer, default=2)
	arrangement = sa.Column(sa.String, default="")
	bemerk = sa.Column(sa.String, default="")
	bestaet_bis = sa.Column(sa.Date, default=None)
	betrieb_gast = sa.Column(sa.Integer, default=0)
	betrieb_gastmem = sa.Column(sa.Integer, default=0)
	betrieb_gastpay = sa.Column(sa.Integer, default=0)
	betriebsnr = sa.Column(sa.Integer, default=0)
	cancelled = sa.Column(sa.Date, default=None)
	cancelled_id = sa.Column(sa.String, default="")
	changed = sa.Column(sa.Date, default=None)
	changed_id = sa.Column(sa.String, default="")
	code = sa.Column(sa.String, default="")
	erwachs = sa.Column(sa.Integer, default=1)
	flight_nr = sa.Column(sa.String, default="")
	gastnr = sa.Column(sa.Integer, default=0)
	gastnrmember = sa.Column(sa.Integer, default=0)
	gastnrpay = sa.Column(sa.Integer, default=0)
	gratis = sa.Column(sa.Integer, default=0)
	grpflag = sa.Column(sa.Boolean, default=False)
	handtuch = sa.Column(sa.Integer, default=0)
	kind1 = sa.Column(sa.Integer, default=0)
	kind2 = sa.Column(sa.Integer, default=0)
	kontakt_nr = sa.Column(sa.Integer, default=0)
	kontignr = sa.Column(sa.Integer, default=0)
	l_zuordnung = sa.Column(ARRAY(sa.Integer),default=[0,0,0,0,0])
	memodatum = sa.Column(sa.Date, default=get_current_date())
	memousercode = sa.Column(sa.String, default="")
	memozeit = sa.Column(sa.Integer, default=0)
	memozinr = sa.Column(sa.String, default="")
	name = sa.Column(sa.String, default="")
	old_zinr = sa.Column(sa.String, default="")
	pin_code = sa.Column(sa.String, default="")
	prov_till = sa.Column(sa.Date, default=None)
	pseudofix = sa.Column(sa.Boolean, default=False)
	reserve_char = sa.Column(sa.String, default="")
	reserve_dec = sa.Column(sa.Numeric, default=0)
	reserve_int = sa.Column(sa.Integer, default=0)
	resflag = sa.Column(sa.Integer, default=0)
	reslinnr = sa.Column(sa.Integer, default=1)
	resname = sa.Column(sa.String, default="")
	resnext = sa.Column(sa.Integer, default=0)
	resnr = sa.Column(sa.Integer, default=0)
	resprev = sa.Column(sa.Integer, default=0)
	resstatus = sa.Column(sa.Integer, default=1)
	setup = sa.Column(sa.Integer, default=0)
	share_connect = sa.Column(sa.String, default="")
	storno_nr = sa.Column(sa.Integer, default=0)
	stornogrund = sa.Column(sa.String, default="")
	voucher_nr = sa.Column(sa.String, default="")
	wabkurz = sa.Column(sa.String, default="")
	waeschewechsel = sa.Column(sa.Integer, default=0)
	was_status = sa.Column(sa.Integer, default=0)
	zikatnr = sa.Column(sa.Integer, default=0)
	zimmer_wunsch = sa.Column(sa.String, default="")
	zimmeranz = sa.Column(sa.Integer, default=1)
	zimmerfix = sa.Column(sa.Boolean, default=False)
	zinr = sa.Column(sa.String, default="")
	zipreis = sa.Column(sa.Numeric, default=0)
	ziwech_zeit = sa.Column(sa.Integer, default=0)
	ziwechseldat = sa.Column(sa.Date, default=None)
	_recid = sa.Column(sa.Integer, primary_key=True)
	def __init__(self, *args, **kwargs):
		kwargs.setdefault('abreise', get_current_date())
		kwargs.setdefault('abreisezeit', 0)
		kwargs.setdefault('active_flag', 0)
		kwargs.setdefault('adrflag', False)
		kwargs.setdefault('ankunft', get_current_date())
		kwargs.setdefault('ankzeit', 0)
		kwargs.setdefault('anztage', 1)
		kwargs.setdefault('argt_typ', 2)
		kwargs.setdefault('arrangement', "")
		kwargs.setdefault('bemerk', "")
		kwargs.setdefault('bestaet_bis', None)
		kwargs.setdefault('betrieb_gast', 0)
		kwargs.setdefault('betrieb_gastmem', 0)
		kwargs.setdefault('betrieb_gastpay', 0)
		kwargs.setdefault('betriebsnr', 0)
		kwargs.setdefault('cancelled', None)
		kwargs.setdefault('cancelled_id', "")
		kwargs.setdefault('changed', None)
		kwargs.setdefault('changed_id', "")
		kwargs.setdefault('code', "")
		kwargs.setdefault('erwachs', 1)
		kwargs.setdefault('flight_nr', "")
		kwargs.setdefault('gastnr', 0)
		kwargs.setdefault('gastnrmember', 0)
		kwargs.setdefault('gastnrpay', 0)
		kwargs.setdefault('gratis', 0)
		kwargs.setdefault('grpflag', False)
		kwargs.setdefault('handtuch', 0)
		kwargs.setdefault('kind1', 0)
		kwargs.setdefault('kind2', 0)
		kwargs.setdefault('kontakt_nr', 0)
		kwargs.setdefault('kontignr', 0)
		kwargs.setdefault('l_zuordnung', [0,0,0,0,0])
		kwargs.setdefault('memodatum', get_current_date())
		kwargs.setdefault('memousercode', "")
		kwargs.setdefault('memozeit', 0)
		kwargs.setdefault('memozinr', "")
		kwargs.setdefault('name', "")
		kwargs.setdefault('old_zinr', "")
		kwargs.setdefault('pin_code', "")
		kwargs.setdefault('prov_till', None)
		kwargs.setdefault('pseudofix', False)
		kwargs.setdefault('reserve_char', "")
		kwargs.setdefault('reserve_dec', 0)
		kwargs.setdefault('reserve_int', 0)
		kwargs.setdefault('resflag', 0)
		kwargs.setdefault('reslinnr', 1)
		kwargs.setdefault('resname', "")
		kwargs.setdefault('resnext', 0)
		kwargs.setdefault('resnr', 0)
		kwargs.setdefault('resprev', 0)
		kwargs.setdefault('resstatus', 1)
		kwargs.setdefault('setup', 0)
		kwargs.setdefault('share_connect', "")
		kwargs.setdefault('storno_nr', 0)
		kwargs.setdefault('stornogrund', "")
		kwargs.setdefault('voucher_nr', "")
		kwargs.setdefault('wabkurz', "")
		kwargs.setdefault('waeschewechsel', 0)
		kwargs.setdefault('was_status', 0)
		kwargs.setdefault('zikatnr', 0)
		kwargs.setdefault('zimmer_wunsch', "")
		kwargs.setdefault('zimmeranz', 1)
		kwargs.setdefault('zimmerfix', False)
		kwargs.setdefault('zinr', "")
		kwargs.setdefault('zipreis', 0)
		kwargs.setdefault('ziwech_zeit', 0)
		kwargs.setdefault('ziwechseldat', None)
		super(Res_line, self).__init__(*args, **kwargs)
