#version: 1.0.0.3

from sqlalchemy.dialects.postgresql import ARRAY
import sqlalchemy as sa
from models.base import Base
from functions.additional_functions import get_current_date

class Bankres(Base):
	__tablename__ = 'bankres'

	activeflag = sa.Column(sa.Integer, default=0)
	anlass = sa.Column(sa.String, default="")
	bankettnr = sa.Column(sa.Integer, default=0)
	bediener_nr = sa.Column(sa.Integer, default=0)
	bemerkung = sa.Column(sa.String, default="")
	betrag = sa.Column(sa.Numeric, default=0)
	betrieb_gast = sa.Column(sa.Integer, default=0)
	betrieb_gastres = sa.Column(sa.Integer, default=0)
	betriebsnr = sa.Column(sa.Integer, default=0)
	durchgehend = sa.Column(sa.Boolean, default=False)
	gastnr = sa.Column(sa.Integer, default=0)
	gastnrres = sa.Column(sa.Integer, default=0)
	kontaktdat = sa.Column(sa.Date, default=get_current_date())
	kontaktfirst = sa.Column(sa.Date, default=None)
	kontnr_res = sa.Column(sa.Integer, default=0)
	kontnr_ver = sa.Column(sa.Integer, default=0)
	notizen = sa.Column(ARRAY(sa.String),default=["","","","",""])
	rechnr = sa.Column(sa.Integer, default=0)
	resdat = sa.Column(sa.Date, default=get_current_date())
	stoerung = sa.Column(sa.Boolean, default=False)
	tafel = sa.Column(sa.String, default="")
	useridanlage = sa.Column(sa.String, default="")
	useridmutat = sa.Column(sa.String, default="")
	zinr = sa.Column(sa.String, default="")
	_recid = sa.Column(sa.Integer, primary_key=True)
	def __init__(self, *args, **kwargs):
		kwargs.setdefault('activeflag', 0)
		kwargs.setdefault('anlass', "")
		kwargs.setdefault('bankettnr', 0)
		kwargs.setdefault('bediener_nr', 0)
		kwargs.setdefault('bemerkung', "")
		kwargs.setdefault('betrag', 0)
		kwargs.setdefault('betrieb_gast', 0)
		kwargs.setdefault('betrieb_gastres', 0)
		kwargs.setdefault('betriebsnr', 0)
		kwargs.setdefault('durchgehend', False)
		kwargs.setdefault('gastnr', 0)
		kwargs.setdefault('gastnrres', 0)
		kwargs.setdefault('kontaktdat', get_current_date())
		kwargs.setdefault('kontaktfirst', None)
		kwargs.setdefault('kontnr_res', 0)
		kwargs.setdefault('kontnr_ver', 0)
		kwargs.setdefault('notizen', ["","","","",""])
		kwargs.setdefault('rechnr', 0)
		kwargs.setdefault('resdat', get_current_date())
		kwargs.setdefault('stoerung', False)
		kwargs.setdefault('tafel', "")
		kwargs.setdefault('useridanlage', "")
		kwargs.setdefault('useridmutat', "")
		kwargs.setdefault('zinr', "")
		super(Bankres, self).__init__(*args, **kwargs)
