#version: 1.0.0.3

from sqlalchemy.dialects.postgresql import ARRAY
import sqlalchemy as sa
from models.base import Base
from functions.additional_functions import get_current_date

class Bill_line(Base):
	__tablename__ = 'bill_line'

	anzahl = sa.Column(sa.Integer, default=0)
	arrangement = sa.Column(sa.String, default="")
	artnr = sa.Column(sa.Integer, default=0)
	bediener_nr = sa.Column(sa.Integer, default=0)
	betrag = sa.Column(sa.Numeric, default=0)
	betrieb_gast = sa.Column(sa.Integer, default=0)
	betriebsnr = sa.Column(sa.Integer, default=0)
	bezeich = sa.Column(sa.String, default="")
	bill_datum = sa.Column(sa.Date, default=None)
	billin_nr = sa.Column(sa.Integer, default=0)
	departement = sa.Column(sa.Integer, default=0)
	epreis = sa.Column(sa.Numeric, default=0)
	fremdwbetrag = sa.Column(sa.Numeric, default=0)
	gastnr = sa.Column(sa.Integer, default=0)
	massnr = sa.Column(sa.Integer, default=0)
	mwstsplit = sa.Column(sa.Boolean, default=False)
	nettobetrag = sa.Column(sa.Numeric, default=0)
	origin_id = sa.Column(sa.String, default="")
	orts_tax = sa.Column(sa.Numeric, default=0)
	printflag = sa.Column(sa.Integer, default=0)
	prtflag = sa.Column(sa.Integer, default=0)
	rechnr = sa.Column(sa.Integer, default=0)
	steuercode = sa.Column(sa.Integer, default=0)
	sysdate = sa.Column(sa.Date, default=get_current_date())
	tax_booked = sa.Column(sa.Boolean, default=False)
	typ = sa.Column(sa.Integer, default=0)
	userinit = sa.Column(sa.String, default="")
	waehrungsnr = sa.Column(sa.Integer, default=0)
	zeit = sa.Column(sa.Integer, default=0)
	zinr = sa.Column(sa.String, default="")
	_recid = sa.Column(sa.Integer, primary_key=True)
	def __init__(self, *args, **kwargs):
		kwargs.setdefault('anzahl', 0)
		kwargs.setdefault('arrangement', "")
		kwargs.setdefault('artnr', 0)
		kwargs.setdefault('bediener_nr', 0)
		kwargs.setdefault('betrag', 0)
		kwargs.setdefault('betrieb_gast', 0)
		kwargs.setdefault('betriebsnr', 0)
		kwargs.setdefault('bezeich', "")
		kwargs.setdefault('bill_datum', None)
		kwargs.setdefault('billin_nr', 0)
		kwargs.setdefault('departement', 0)
		kwargs.setdefault('epreis', 0)
		kwargs.setdefault('fremdwbetrag', 0)
		kwargs.setdefault('gastnr', 0)
		kwargs.setdefault('massnr', 0)
		kwargs.setdefault('mwstsplit', False)
		kwargs.setdefault('nettobetrag', 0)
		kwargs.setdefault('origin_id', "")
		kwargs.setdefault('orts_tax', 0)
		kwargs.setdefault('printflag', 0)
		kwargs.setdefault('prtflag', 0)
		kwargs.setdefault('rechnr', 0)
		kwargs.setdefault('steuercode', 0)
		kwargs.setdefault('sysdate', get_current_date())
		kwargs.setdefault('tax_booked', False)
		kwargs.setdefault('typ', 0)
		kwargs.setdefault('userinit', "")
		kwargs.setdefault('waehrungsnr', 0)
		kwargs.setdefault('zeit', 0)
		kwargs.setdefault('zinr', "")
		super(Bill_line, self).__init__(*args, **kwargs)
