#version: 1.0.0.3

from sqlalchemy.dialects.postgresql import ARRAY
import sqlalchemy as sa
from models.base import Base
from functions.additional_functions import get_current_date

class Eg_request(Base):
	__tablename__ = 'eg_request'

	assign_to = sa.Column(sa.Integer, default=0)
	assign_to2 = sa.Column(sa.String, default="")
	cancel_by = sa.Column(sa.String, default="")
	cancel_date = sa.Column(sa.Date, default=None)
	cancel_time = sa.Column(sa.Integer, default=0)
	category = sa.Column(sa.Integer, default=0)
	char1 = sa.Column(sa.String, default="")
	char2 = sa.Column(sa.String, default="")
	char3 = sa.Column(sa.String, default="")
	closed_by = sa.Column(sa.String, default="")
	closed_date = sa.Column(sa.Date, default=None)
	closed_time = sa.Column(sa.Integer, default=0)
	created_by = sa.Column(sa.String, default="")
	created_date = sa.Column(sa.Date, default=None)
	date1 = sa.Column(sa.Date, default=None)
	date2 = sa.Column(sa.Date, default=None)
	date3 = sa.Column(sa.Date, default=None)
	deci1 = sa.Column(sa.Numeric, default=0)
	deci2 = sa.Column(sa.Numeric, default=0)
	deci3 = sa.Column(sa.Numeric, default=0)
	delete_flag = sa.Column(sa.Boolean, default=False)
	deptnum = sa.Column(sa.Integer, default=0)
	done_by = sa.Column(sa.String, default="")
	done_date = sa.Column(sa.Date, default=None)
	done_time = sa.Column(sa.Integer, default=0)
	ex_finishdate = sa.Column(sa.Date, default=None)
	ex_finishdate1 = sa.Column(sa.Date, default=None)
	ex_finishtime = sa.Column(sa.Integer, default=0)
	ex_finishtime1 = sa.Column(sa.Integer, default=0)
	from_date = sa.Column(sa.Date, default=None)
	from_dept = sa.Column(sa.Integer, default=0)
	gastnr = sa.Column(sa.Integer, default=0)
	location = sa.Column(sa.Integer, default=0)
	logi1 = sa.Column(sa.Boolean, default=False)
	logi2 = sa.Column(sa.Boolean, default=False)
	logi3 = sa.Column(sa.Boolean, default=False)
	maintask = sa.Column(sa.Integer, default=0)
	memo = sa.Column(sa.String, default="")
	number1 = sa.Column(sa.Integer, default=0)
	number2 = sa.Column(sa.Integer, default=0)
	number3 = sa.Column(sa.Integer, default=0)
	opened_by = sa.Column(sa.String, default="")
	opened_date = sa.Column(sa.Date, default=None)
	opened_time = sa.Column(sa.Integer, default=0)
	other_cost = sa.Column(sa.Numeric, default=0)
	outsourceflag = sa.Column(sa.Boolean, default=False)
	process_by = sa.Column(sa.String, default="")
	process_date = sa.Column(sa.Date, default=None)
	process_time = sa.Column(sa.Integer, default=0)
	propertynr = sa.Column(sa.Integer, default=0)
	reasondonetime = sa.Column(sa.String, default="")
	reasonstatus = sa.Column(sa.String, default="")
	reqnr = sa.Column(sa.Integer, default=0)
	reqstatus = sa.Column(sa.Integer, default=0)
	reserve_char = sa.Column(sa.String, default="")
	reserve_date = sa.Column(sa.Date, default=None)
	reserve_int = sa.Column(sa.Integer, default=0)
	reserve_log = sa.Column(sa.Boolean, default=False)
	reslinnr = sa.Column(sa.Integer, default=0)
	resnr = sa.Column(sa.Integer, default=0)
	source = sa.Column(sa.Integer, default=0)
	source_name = sa.Column(sa.String, default="")
	sppart_cost = sa.Column(sa.Numeric, default=0)
	sub_task = sa.Column(sa.String, default="")
	subtask_bezeich = sa.Column(sa.String, default="")
	subtask_duration = sa.Column(sa.String, default="")
	task_def = sa.Column(sa.String, default="")
	task_solv = sa.Column(sa.String, default="")
	to_date = sa.Column(sa.Date, default=None)
	urgency = sa.Column(sa.Integer, default=0)
	zinr = sa.Column(sa.String, default="")
	_recid = sa.Column(sa.Integer, primary_key=True)
	def __init__(self, *args, **kwargs):
		kwargs.setdefault('assign_to', 0)
		kwargs.setdefault('assign_to2', "")
		kwargs.setdefault('cancel_by', "")
		kwargs.setdefault('cancel_date', None)
		kwargs.setdefault('cancel_time', 0)
		kwargs.setdefault('category', 0)
		kwargs.setdefault('char1', "")
		kwargs.setdefault('char2', "")
		kwargs.setdefault('char3', "")
		kwargs.setdefault('closed_by', "")
		kwargs.setdefault('closed_date', None)
		kwargs.setdefault('closed_time', 0)
		kwargs.setdefault('created_by', "")
		kwargs.setdefault('created_date', None)
		kwargs.setdefault('date1', None)
		kwargs.setdefault('date2', None)
		kwargs.setdefault('date3', None)
		kwargs.setdefault('deci1', 0)
		kwargs.setdefault('deci2', 0)
		kwargs.setdefault('deci3', 0)
		kwargs.setdefault('delete_flag', False)
		kwargs.setdefault('deptnum', 0)
		kwargs.setdefault('done_by', "")
		kwargs.setdefault('done_date', None)
		kwargs.setdefault('done_time', 0)
		kwargs.setdefault('ex_finishdate', None)
		kwargs.setdefault('ex_finishdate1', None)
		kwargs.setdefault('ex_finishtime', 0)
		kwargs.setdefault('ex_finishtime1', 0)
		kwargs.setdefault('from_date', None)
		kwargs.setdefault('from_dept', 0)
		kwargs.setdefault('gastnr', 0)
		kwargs.setdefault('location', 0)
		kwargs.setdefault('logi1', False)
		kwargs.setdefault('logi2', False)
		kwargs.setdefault('logi3', False)
		kwargs.setdefault('maintask', 0)
		kwargs.setdefault('memo', "")
		kwargs.setdefault('number1', 0)
		kwargs.setdefault('number2', 0)
		kwargs.setdefault('number3', 0)
		kwargs.setdefault('opened_by', "")
		kwargs.setdefault('opened_date', None)
		kwargs.setdefault('opened_time', 0)
		kwargs.setdefault('other_cost', 0)
		kwargs.setdefault('outsourceflag', False)
		kwargs.setdefault('process_by', "")
		kwargs.setdefault('process_date', None)
		kwargs.setdefault('process_time', 0)
		kwargs.setdefault('propertynr', 0)
		kwargs.setdefault('reasondonetime', "")
		kwargs.setdefault('reasonstatus', "")
		kwargs.setdefault('reqnr', 0)
		kwargs.setdefault('reqstatus', 0)
		kwargs.setdefault('reserve_char', "")
		kwargs.setdefault('reserve_date', None)
		kwargs.setdefault('reserve_int', 0)
		kwargs.setdefault('reserve_log', False)
		kwargs.setdefault('reslinnr', 0)
		kwargs.setdefault('resnr', 0)
		kwargs.setdefault('source', 0)
		kwargs.setdefault('source_name', "")
		kwargs.setdefault('sppart_cost', 0)
		kwargs.setdefault('sub_task', "")
		kwargs.setdefault('subtask_bezeich', "")
		kwargs.setdefault('subtask_duration', "")
		kwargs.setdefault('task_def', "")
		kwargs.setdefault('task_solv', "")
		kwargs.setdefault('to_date', None)
		kwargs.setdefault('urgency', 0)
		kwargs.setdefault('zinr', "")
		super(Eg_request, self).__init__(*args, **kwargs)
