#version: 1.0.0.3

from sqlalchemy.dialects.postgresql import ARRAY
import sqlalchemy as sa
from models.base import Base
from functions.additional_functions import get_current_date

class Guest(Base):
	__tablename__ = 'guest'

	adresse1 = sa.Column(sa.String, default="")
	adresse2 = sa.Column(sa.String, default="")
	adresse3 = sa.Column(sa.String, default="")
	anlage_datum = sa.Column(sa.Date, default=get_current_date())
	anrede1 = sa.Column(sa.String, default="")
	anrede2 = sa.Column(sa.String, default="")
	anredefirma = sa.Column(sa.String, default="")
	argt_doppel = sa.Column(sa.String, default="")
	argt_einzel = sa.Column(sa.String, default="")
	argtumsatz = sa.Column(sa.Numeric, default=0)
	arzt1 = sa.Column(sa.Integer, default=0)
	arzt2 = sa.Column(sa.Integer, default=0)
	aufenthalte = sa.Column(sa.Integer, default=0)
	ausweis_art = sa.Column(sa.String, default="")
	ausweis_nr1 = sa.Column(sa.String, default="")
	ausweis_nr2 = sa.Column(sa.String, default="")
	autonr = sa.Column(sa.String, default="")
	bemerkung = sa.Column(sa.String, default="")
	beruf = sa.Column(sa.String, default="")
	betrieb_gastmaster = sa.Column(sa.Integer, default=0)
	betrieb_gastpoint = sa.Column(sa.Integer, default=0)
	betriebsnr = sa.Column(sa.Integer, default=0)
	blumen = sa.Column(sa.Boolean, default=False)
	briefanrede = sa.Column(sa.String, default="")
	cardnr = sa.Column(sa.String, default="")
	champagner = sa.Column(sa.Boolean, default=False)
	char1 = sa.Column(sa.String, default="")
	char2 = sa.Column(sa.String, default="")
	code = sa.Column(sa.String, default="")
	com_argt = sa.Column(sa.Numeric, default=0)
	com_f_b = sa.Column(sa.Numeric, default=0)
	com_logis = sa.Column(sa.Numeric, default=0)
	com_sonst = sa.Column(sa.Numeric, default=0)
	credablauf = sa.Column(sa.Date, default=None)
	date1 = sa.Column(sa.Date, default=None)
	date2 = sa.Column(sa.Date, default=None)
	deci1 = sa.Column(sa.Numeric, default=0)
	deci2 = sa.Column(sa.Numeric, default=0)
	email_adr = sa.Column(sa.String, default="")
	endkur = sa.Column(sa.String, default="0000")
	endperiode = sa.Column(sa.Date, default=None)
	erstaufent = sa.Column(sa.Date, default=None)
	erste_res = sa.Column(sa.Date, default=None)
	f_b_umsatz = sa.Column(sa.Numeric, default=0)
	fax = sa.Column(sa.String, default="")
	finanzamt = sa.Column(sa.String, default="")
	firmen_nr = sa.Column(sa.Integer, default=0)
	gastnr = sa.Column(sa.Integer, default=None)
	geburt_ort1 = sa.Column(sa.String, default="")
	geburt_ort2 = sa.Column(sa.String, default="")
	geburtdatum1 = sa.Column(sa.Date, default=None)
	geburtdatum2 = sa.Column(sa.Date, default=None)
	geburtkind = sa.Column(ARRAY(sa.Date),default=[None,None,None,None,None,None])
	gesamtumsatz = sa.Column(sa.Numeric, default=0)
	gesamtumsatz_old = sa.Column(sa.Integer, default=0)
	geschlecht = sa.Column(sa.String, default="M")
	geschlecht2 = sa.Column(sa.String, default="W")
	gewicht = sa.Column(sa.Integer, default=0)
	gewicht2 = sa.Column(sa.Integer, default=0)
	groesse = sa.Column(sa.Integer, default=0)
	groesse2 = sa.Column(sa.Integer, default=0)
	interessen = sa.Column(sa.String, default="")
	karteityp = sa.Column(sa.Integer, default=0)
	kontaktdat = sa.Column(sa.Date, default=get_current_date())
	kreditlimit = sa.Column(sa.Numeric, default=0)
	kreditlimit_old = sa.Column(sa.Integer, default=0)
	land = sa.Column(sa.String, default="")
	letzte_abreise = sa.Column(sa.Date, default=None)
	letzte_res = sa.Column(sa.Date, default=None)
	logi1 = sa.Column(sa.Boolean, default=False)
	logi2 = sa.Column(sa.Boolean, default=False)
	logier_min = sa.Column(sa.Integer, default=0)
	logiernachte = sa.Column(sa.Integer, default=0)
	logisumsatz = sa.Column(sa.Numeric, default=0)
	mahnsperre = sa.Column(sa.Integer, default=0)
	massnr = sa.Column(sa.Integer, default=0)
	massnr2 = sa.Column(sa.Integer, default=0)
	master_gastnr = sa.Column(sa.Integer, default=0)
	mobil_telefon = sa.Column(sa.String, default="")
	modif_datum = sa.Column(sa.Date, default=None)
	naechste_res = sa.Column(sa.Date, default=None)
	name = sa.Column(sa.String, default="")
	namekontakt = sa.Column(sa.String, default="")
	nation1 = sa.Column(sa.String, default="")
	nation2 = sa.Column(sa.String, default="")
	noshows = sa.Column(sa.Integer, default=0)
	notizen = sa.Column(ARRAY(sa.String),default=["","",""])
	number1 = sa.Column(sa.Integer, default=0)
	number2 = sa.Column(sa.Integer, default=0)
	pass_aust1 = sa.Column(sa.String, default="")
	pass_aust2 = sa.Column(sa.String, default="")
	phonetik1 = sa.Column(sa.String, default="")
	phonetik2 = sa.Column(sa.String, default="")
	phonetik3 = sa.Column(sa.String, default="")
	plz = sa.Column(sa.String, default="")
	point_gastnr = sa.Column(sa.Integer, default=0)
	preis_doppel = sa.Column(sa.Numeric, default=0)
	preis_einzel = sa.Column(sa.Numeric, default=0)
	rabatt = sa.Column(sa.Numeric, default=0)
	resflag = sa.Column(sa.Integer, default=0)
	segment1 = sa.Column(sa.Integer, default=0)
	segment2 = sa.Column(sa.Integer, default=0)
	segment3 = sa.Column(sa.Integer, default=0)
	sonst_umsatz = sa.Column(sa.Numeric, default=0)
	sprachcode = sa.Column(sa.Integer, default=1)
	startkur = sa.Column(sa.String, default="0000")
	startperiode = sa.Column(sa.Date, default=get_current_date())
	sternzeichen = sa.Column(sa.String, default="")
	steuernr = sa.Column(sa.String, default="")
	stornos = sa.Column(sa.Integer, default=0)
	telefon = sa.Column(sa.String, default="")
	telefon_privat = sa.Column(sa.String, default="")
	telex = sa.Column(sa.String, default="")
	trans_datum = sa.Column(sa.Date, default=None)
	tv_checkout = sa.Column(sa.Boolean, default=True)
	tv_pay = sa.Column(sa.Boolean, default=True)
	tv_see_bill = sa.Column(sa.Boolean, default=True)
	vorname_haupt = sa.Column(sa.String, default="")
	vorname1 = sa.Column(sa.String, default="")
	vorname2 = sa.Column(sa.String, default="")
	vornamekind = sa.Column(ARRAY(sa.String),default=["","","","","",""])
	wohnort = sa.Column(sa.String, default="")
	zahlungsart = sa.Column(sa.Integer, default=0)
	zimmer_min = sa.Column(sa.Integer, default=0)
	zimmeranz = sa.Column(sa.Integer, default=0)
	_recid = sa.Column(sa.Integer, primary_key=True)
	def __init__(self, *args, **kwargs):
		kwargs.setdefault('adresse1', "")
		kwargs.setdefault('adresse2', "")
		kwargs.setdefault('adresse3', "")
		kwargs.setdefault('anlage_datum', get_current_date())
		kwargs.setdefault('anrede1', "")
		kwargs.setdefault('anrede2', "")
		kwargs.setdefault('anredefirma', "")
		kwargs.setdefault('argt_doppel', "")
		kwargs.setdefault('argt_einzel', "")
		kwargs.setdefault('argtumsatz', 0)
		kwargs.setdefault('arzt1', 0)
		kwargs.setdefault('arzt2', 0)
		kwargs.setdefault('aufenthalte', 0)
		kwargs.setdefault('ausweis_art', "")
		kwargs.setdefault('ausweis_nr1', "")
		kwargs.setdefault('ausweis_nr2', "")
		kwargs.setdefault('autonr', "")
		kwargs.setdefault('bemerkung', "")
		kwargs.setdefault('beruf', "")
		kwargs.setdefault('betrieb_gastmaster', 0)
		kwargs.setdefault('betrieb_gastpoint', 0)
		kwargs.setdefault('betriebsnr', 0)
		kwargs.setdefault('blumen', False)
		kwargs.setdefault('briefanrede', "")
		kwargs.setdefault('cardnr', "")
		kwargs.setdefault('champagner', False)
		kwargs.setdefault('char1', "")
		kwargs.setdefault('char2', "")
		kwargs.setdefault('code', "")
		kwargs.setdefault('com_argt', 0)
		kwargs.setdefault('com_f_b', 0)
		kwargs.setdefault('com_logis', 0)
		kwargs.setdefault('com_sonst', 0)
		kwargs.setdefault('credablauf', None)
		kwargs.setdefault('date1', None)
		kwargs.setdefault('date2', None)
		kwargs.setdefault('deci1', 0)
		kwargs.setdefault('deci2', 0)
		kwargs.setdefault('email_adr', "")
		kwargs.setdefault('endkur', "0000")
		kwargs.setdefault('endperiode', None)
		kwargs.setdefault('erstaufent', None)
		kwargs.setdefault('erste_res', None)
		kwargs.setdefault('f_b_umsatz', 0)
		kwargs.setdefault('fax', "")
		kwargs.setdefault('finanzamt', "")
		kwargs.setdefault('firmen_nr', 0)
		kwargs.setdefault('gastnr', None)
		kwargs.setdefault('geburt_ort1', "")
		kwargs.setdefault('geburt_ort2', "")
		kwargs.setdefault('geburtdatum1', None)
		kwargs.setdefault('geburtdatum2', None)
		kwargs.setdefault('geburtkind', [None,None,None,None,None,None])
		kwargs.setdefault('gesamtumsatz', 0)
		kwargs.setdefault('gesamtumsatz_old', 0)
		kwargs.setdefault('geschlecht', "M")
		kwargs.setdefault('geschlecht2', "W")
		kwargs.setdefault('gewicht', 0)
		kwargs.setdefault('gewicht2', 0)
		kwargs.setdefault('groesse', 0)
		kwargs.setdefault('groesse2', 0)
		kwargs.setdefault('interessen', "")
		kwargs.setdefault('karteityp', 0)
		kwargs.setdefault('kontaktdat', get_current_date())
		kwargs.setdefault('kreditlimit', 0)
		kwargs.setdefault('kreditlimit_old', 0)
		kwargs.setdefault('land', "")
		kwargs.setdefault('letzte_abreise', None)
		kwargs.setdefault('letzte_res', None)
		kwargs.setdefault('logi1', False)
		kwargs.setdefault('logi2', False)
		kwargs.setdefault('logier_min', 0)
		kwargs.setdefault('logiernachte', 0)
		kwargs.setdefault('logisumsatz', 0)
		kwargs.setdefault('mahnsperre', 0)
		kwargs.setdefault('massnr', 0)
		kwargs.setdefault('massnr2', 0)
		kwargs.setdefault('master_gastnr', 0)
		kwargs.setdefault('mobil_telefon', "")
		kwargs.setdefault('modif_datum', None)
		kwargs.setdefault('naechste_res', None)
		kwargs.setdefault('name', "")
		kwargs.setdefault('namekontakt', "")
		kwargs.setdefault('nation1', "")
		kwargs.setdefault('nation2', "")
		kwargs.setdefault('noshows', 0)
		kwargs.setdefault('notizen', ["","",""])
		kwargs.setdefault('number1', 0)
		kwargs.setdefault('number2', 0)
		kwargs.setdefault('pass_aust1', "")
		kwargs.setdefault('pass_aust2', "")
		kwargs.setdefault('phonetik1', "")
		kwargs.setdefault('phonetik2', "")
		kwargs.setdefault('phonetik3', "")
		kwargs.setdefault('plz', "")
		kwargs.setdefault('point_gastnr', 0)
		kwargs.setdefault('preis_doppel', 0)
		kwargs.setdefault('preis_einzel', 0)
		kwargs.setdefault('rabatt', 0)
		kwargs.setdefault('resflag', 0)
		kwargs.setdefault('segment1', 0)
		kwargs.setdefault('segment2', 0)
		kwargs.setdefault('segment3', 0)
		kwargs.setdefault('sonst_umsatz', 0)
		kwargs.setdefault('sprachcode', 1)
		kwargs.setdefault('startkur', "0000")
		kwargs.setdefault('startperiode', get_current_date())
		kwargs.setdefault('sternzeichen', "")
		kwargs.setdefault('steuernr', "")
		kwargs.setdefault('stornos', 0)
		kwargs.setdefault('telefon', "")
		kwargs.setdefault('telefon_privat', "")
		kwargs.setdefault('telex', "")
		kwargs.setdefault('trans_datum', None)
		kwargs.setdefault('tv_checkout', True)
		kwargs.setdefault('tv_pay', True)
		kwargs.setdefault('tv_see_bill', True)
		kwargs.setdefault('vorname_haupt', "")
		kwargs.setdefault('vorname1', "")
		kwargs.setdefault('vorname2', "")
		kwargs.setdefault('vornamekind', ["","","","","",""])
		kwargs.setdefault('wohnort', "")
		kwargs.setdefault('zahlungsart', 0)
		kwargs.setdefault('zimmer_min', 0)
		kwargs.setdefault('zimmeranz', 0)
		super(Guest, self).__init__(*args, **kwargs)
